### ISSUE TITLE
Move toggle_locale.js to React

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#1009]
# Description 

toggle_locale.js is a file in the Rails JS assets that is responsible for changing the language of the site whenever the user interacts with the language dropdown. Let's move this to client/app/widgets. We use Axios for REST in the client.

# Do you want to be the assignee to work on this?

**Comment by n1arash** [comment]
i'd like to work on this

**Comment by julianguyen** [comment]
Hey @n1arash, thanks for expressing your interest. We would love your help with this issue. Please check out https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack for next steps :)
