### ISSUE TITLE
Move most_focus method in application_controller.rb into its own helper

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#1011]
# Description 

Move most_focus method in application_controller.rb into its own helper. The motivation is to declutter application_controller and have better separation of concerns. Be sure to move the tests too.

Move top_three_focus and profile_exists? in this new helper too and make them private

# Do you want to be the assignee to work on this?

🚫

**Comment by sjakobi** [comment]
> Do you want to be the assignee to work on this?

I'd like to fix this! :)

**Comment by julianguyen** [comment]
Hey @sjakobi, thanks for expressing your interest. We would love your help with this issue. Please check out https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack for next steps :)

**Comment by jash-kothari** [comment]
If this is not being worked on would like to work on this.

**Comment by julianguyen** [comment]
@jash-kothari Please follow next steps mentioned above and then assign yourself to this issue.
