### ISSUE TITLE
Move tag_usage method in application_controller.rb into its own helper. 

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#1012]
# Description 

Move tag_usage method in application_controller.rb into its own helper.  The motivation is to declutter application_controller and have better separation of concerns. Be sure to move the tests too.

Let's move data_included? as well as a private method in the new helper.

# Do you want to be the assignee to work on this?

🚫

**Comment by Atul9** [comment]
@julianguyen I would like to work on this

**Comment by julianguyen** [comment]
Hey @Atul9, thanks for expressing your interest. We would love your help with this issue. Please check out https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack for next steps :)
