### ISSUE TITLE
Move get_stories method in application_controller.rb into its own helper. 

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#1013]
# Description 

Move get_stories method in application_controller.rb into its own helper.  The motivation is to declutter application_controller and have better separation of concerns. Be sure to move the tests too.

Move user_stories in this new helper too and make it private

# Do you want to be the assignee to work on this?

🚫

**Comment by jaimevelaz** [comment]
Hi @julianguyen, I would like to help with this one 😃

**Comment by julianguyen** [comment]
Hey @jaimevelaz, thanks for expressing your interest. We would love your help with this issue. Please check out https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack for next steps :)
