### ISSUE TITLE
Move moments_stats method in application_controller.rb into its own helper.

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#1014]
# Description 

Move moments_stats method in application_controller.rb into its own helper. The motivation is to declutter application_controller and have better separation of concerns. Be sure to move the tests too.

# Do you want to be the assignee to work on this?

🚫

**Comment by DamonClark** [comment]
I'd like to work on this!

**Comment by julianguyen** [comment]
@DamonClark Awesome! Feel free to assign yourself to the issue whenever you're ready :) Thanks!
