### ISSUE TITLE
Move user_created_data? from application_controller.rb into comments_helper.rb

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#1015]
# Description 

user_created_data? is just being used by comments_helper.rb let's move that there as a private method

# Do you want to be the assignee to work on this?

🚫

**Comment by jiradeto** [comment]
I am interested

**Comment by julianguyen** [comment]
Hey @jiradeto, thanks for expressing your interest. We would love your help with this issue. Please check out https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack for next steps :)

**Comment by jeccb** [comment]
Hi, can I do it too?

**Comment by julianguyen** [comment]
Hey @jeccb thanks for expressing your interest!  I'm not sure if @jiradeto is still interested in working on this. If not, it's up for grabs. Otherwise, there are other issues that are similar in terms of refactoring Rails code. I'm happy to point you to some if you can't find anything.

Please also check out [next steps](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack) for joining our contributor community :)

**Comment by julianguyen** [comment]
Alternatively you two could do some remote pairing on this issue. Two heads are always better than one :)

**Comment by asarbu** [comment]
hi 👋 I created a MR with the changes you requested
