### ISSUE TITLE
Replace pagination via Kaminari with infinite scroll/lazy loading in react

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#1016]
# Description 

Replace pagination via Kaminari with infinite scroll/lazy loading in react

Pages include: signed in home page, index pages for Moments, Strategies, Categories, Moods, and Medications

# Do you want to be the assignee to work on this?

Maybe, but if someone else what's to work on it - feel free to assign yourself

**Comment by woarewe** [comment]
Hello, @julianguyen! I would like to work on this

**Comment by 3minus1** [comment]
I'd love to work on this!

**Comment by julianguyen** [comment]
Hey @3minus1, thanks for expressing your interest. We would love your help with this issue. Please check out https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack for next steps :)

**Comment by Jacek-202** [comment]
@julianguyen Hi can i help with it?

**Comment by 3minus1** [comment]
@julianguyen Hey. I'm so sorry but I got really tied up with work, and I couldn't get time to complete this. 
Hoping @Jacek-202 can pick it up. Let me know if you need any help. :)
