### ISSUE TITLE
Secure notifications controller

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#1025]
# Description 

There was some really awesome progress being made in this [PR](https://github.com/ifmeorg/ifme/pull/316) to make the notifications controller more secure and add better test coverage. It never got finished, it would be great if someone could finish it up :)

# Do you want to be the assignee to work on this?

🚫

**Comment by tryantwit** [comment]
I can pick up work on this.

**Comment by julianguyen** [comment]
Hey @tryantwit, thanks for expressing your interest. We would love your help with this issue. Please check out https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack for next steps :)
