### ISSUE TITLE
Use Dependabot

### ISSUE THREAD

**Issue by greysteil** [ifmeorg/ifme#1026]
Really a question - @julianguyen, are you happy for me to add [Dependabot](https://dependabot.com) to this repo to get dependency update PRs?

**Comment by julianguyen** [comment]
Yay the welcome bot is working 😆 
Ooh I'm very open to it, it looks very promising. Thanks for the suggestion. Are these PRs automatic to recommend updates to the latest versions of packages/gems? I'm also guessing it doesn't automatically merge so someone could go in and fix something.

**Comment by greysteil** [comment]
Yeah, it'll create PRs to the latest version but won't automatically merge, so we'll be able to review. I've requested an install through the GitHub app interface - you should have an from GitHub saying you need to approve it and then I can take it from there.

**Comment by julianguyen** [comment]
Approved!

**Comment by greysteil** [comment]
Awesome! I'll take a look through the initial PRs when they come.
