### ISSUE TITLE
Add missing test coverage for medication_helper.rb

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#1051]
# Description 

Womp womp we're missing test coverage here. Let's go back and add it!

# Do you want to be the assignee to work on this?

🚫

**Comment by timorthi** [comment]
I can give this a go :)

**Comment by timorthi** [comment]
Did someone already work on this @julianguyen ?

**Comment by julianguyen** [comment]
Actually no it was medication_refill_helper.rb, sorry about that! It's still open!

**Comment by timorthi** [comment]
I won't be able to get on this as soon as I thought I could, so I'm gonna unassign myself and let someone else pick this up. Otherwise I'll reassign myself when I'm ready to work on it :)

**Comment by haleymnatz** [comment]
@julianguyen I'll take this on! I'm excited to have gotten a chance to contribute to ifme again. 🎉 

Also, thanks @timorthi for great communication about your contribution! I assigned myself an issue before and forgot to remove myself when I couldn't get to it :/ So thanks for not doing the same thing!

**Comment by julianguyen** [comment]
Yay @haleymnatz :D Thanks so much. Hope you're doing decent 💜
