### ISSUE TITLE
Adding missing test coverage for category.rb

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#1053]
# Description 

Womp womp we're missing test coverage here. Let's go back and add it!

# Do you want to be the assignee to work on this?

🚫

**Comment by Atul9** [comment]
I would like to work on this

**Comment by julianguyen** [comment]
Hey @Atul9, thanks for expressing your interest. We would love your help with this issue. Please check out https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack for next steps :) After that, assign yourself to the issue.

**Comment by julianguyen** [comment]
@felipemrvieira Can you follow the next steps above and then assign yourself to this issue? Thanks.

**Comment by thovt93** [comment]
@julianguyen I would like to work on this
