### ISSUE TITLE
Remove try in favor of safe navigation

### ISSUE THREAD

**Issue by DRBragg** [ifmeorg/ifme#1056]
# Description 

`try` is being used in multiple places throughout the app. Suggest refactoring to safe navigation to keep with Ruby standards

# Example

This:
``` ruby
@medication.try(:take_medication_reminder).try(:active)
```
Should look like this:
``` ruby
@medication&.take_medication_reminder&.active
```

# Do you want to be the assignee to work on this?

✅

**Comment by julianguyen** [comment]
Interesting, I didn't know it was better to use safe navigation over try. Now that I'm reading up on it, it makes sense! Great suggestion! Thanks!

**Comment by DRBragg** [comment]
Glad I could help. Safe nav is one of those random things I found while trying to improve my ruby skills. I love ruby's readability and the safe nav is another great example of it.
