### ISSUE TITLE
Only deploy to production (Heroku) via CircleCI if a git tag exists

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#1075]
# Description 

This is related to discussions involving [staging servers](https://github.com/ifmeorg/ifme/issues/1055). Before we set up staging servers, we should improve our production deployment process. Currently, we deploy every time there's a push to master. While this was okay in the past, there are certain times of the year where we get frequent (almost daily) merges to master (yay!)... which means A LOT of deploys. Sometimes we don't want to deploy right away if the change is minor. Setting up tags offers flexibility, we can decide on the spot whether we want to deploy the last x changes without having to work against a fixed deploy schedule.

We also record a [manual changelog](https://github.com/ifmeorg/ifme/wiki/Changelog) for major updates and often forget to update it. Using git tags and releases will also tackle that problem.

Let's also enforce [Semver](https://semver.org/) when it comes to versioning.

# Do you want to be the assignee to work on this?

🚫 This would be a great opportunity for someone who's interested! I'm happy to help (if needed) as I have experience writing CircleCI configs.

**Comment by tryantwit** [comment]
I'll take a crack at this. CircleCI 2.0 has support for [Git Tag Filters](https://circleci.com/docs/2.0/configuration-reference/#tags) so should be pretty easy.
