### ISSUE TITLE
Add support to close the Modal component with the escape key

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#1115]
# Description 

Add support to close the Modal component with the escape key

Please also write tests for this in Modal.spec.jsx 👼 

# Do you want to be the assignee to work on this?

🚫

**Comment by gowrimanoharir** [comment]
Hi, I would like to try this.

**Comment by gowrimanoharir** [comment]
@Julia Nguyen sorry yes got busy with work and missed to follow through on this. will work on this and create a pr by this weekend. I apologize again for the delay.

**Comment by MaanasArora** [comment]
@julianguyen Can I work on this one?

**Comment by julianguyen** [comment]
@MaanasArora Yeah go right ahead! Thank you!

**Comment by julianguyen** [comment]
Hey, @MaanasArora are you still working on this?

**Comment by harshlele** [comment]
is this issue still open?

**Comment by Gibbo3771** [comment]
I know it's only been 10 days, but is this been worked on at the moment? Had a look at your repo @ivillicana and seen a commit for it.

**Comment by Gibbo3771** [comment]
Not heard from self assigned person in 3 days and approaching 2 weeks, [I went ahead and done a PR](https://github.com/ifmeorg/ifme/pull/1383)
