### ISSUE TITLE
Convert toggle_locale.js to React

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#1116]
# Description 

Convert toggle_locale.js to React

# Do you want to be the assignee to work on this?

✅

**Comment by jm96441n** [comment]
I could possibly take this on, let me look a little more into it. Is `toggle_locale.js` a js library or something that was built?

**Comment by julianguyen** [comment]
@jm96441n I'm actually almost done (just have to write tests), thanks for offering though :) I'll add you as a reviewer when I'm done.

**Comment by jm96441n** [comment]
sounds good to me!

**Comment by jm96441n** [comment]
Oops, my bad, totally missed that you were assigned to this!

**Comment by julianguyen** [comment]
@jm96441n Would you be interested in https://github.com/ifmeorg/ifme/issues/1118? :D

**Comment by jm96441n** [comment]
I think I can handle that!
