### ISSUE TITLE
Convert get_location.js to React

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#1118]
# Description 

Convert get_location.js to React

Ideally, it would be great to get rid of the following in application.html.erb
```
<% if join_path? || update_account_path? %>
      <!-- Google Maps API -->
      <% google_maps_url = "https://maps.googleapis.com/maps/api/js?key=#{ENV['GOOGLE_API_KEY']}&libraries=places&callback=initAutocomplete" %>
      <link rel="preconnect" href=<%= google_maps_url %>>
      <%= javascript_include_tag google_maps_url, async: true %>
    <% end %>
```
and use the Google Maps API from the client side.

# Do you want to be the assignee to work on this?

🚫

**Comment by jm96441n** [comment]
I can pick this up

**Comment by baohouse** [comment]
This might be helpful.
https://github.com/yuanqing/load-google-maps-api
