### ISSUE TITLE
Add a "Add to Google Calendar" button on a group meeting event

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#113]
![screen shot 2016-05-02 at 4 53 34 pm](https://cloud.githubusercontent.com/assets/3010728/14971389/8e18e0c2-1086-11e6-9e4e-4d26036c379b.png)

For users that are Google authenticated, display a "Add to Google Calendar" button on each group meeting event the user is attending.

For an example on how to use the Google Calendar API, see `medications_controller.rb:66`

**Comment by JessRudder** [comment]
I'd be happy to take a pass at this.

**Comment by julianguyen** [comment]
@JessRudder, that would be fantastic! Can you send us an email at join.ifme@gmail.com so we can add you to our Slack?

Thanks ^^

**Comment by pcofilada** [comment]
@julianguyen Is there anyone doing this?

**Comment by julianguyen** [comment]
Nope! Feel free to work on this! @pcofilada. It's been implemented here https://github.com/julianguyen/ifme/issues/297 but it's currently broken :/ So you could potentially work on both!

Also please email join.ifme@gmail.com so we can add you to our Slack! Also don't forget to add yourself to the Contributors page :D

**Comment by pcofilada** [comment]
Ok got it. I will just work on the devise issue first and I will take a look on this @julianguyen

**Comment by julianguyen** [comment]
@pcofilada How is this going?

**Comment by jnamster** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(3) Add a "Add a Google Calendar" button on a group meeting event](https://trello.com/c/2FIlIQOu/24-3-add-a-add-a-google-calendar-button-on-a-group-meeting-event)

**Comment by cesargroening** [comment]
Hello,  this is my first attempt helping ,can i work on this issue ?

**Comment by julianguyen** [comment]
Hey, @cesargroening, can you email us at join.ifme@gmail.com so we can add you to our Slack? :)  I don't think @jnamster ever got around to this, I think it should be fine to work on.

**Comment by cesargroening** [comment]
For resolve this issue i have to add a new column in the meeting_members table.
   The new collumn name going to be "google_cal_id", it's for make a relationship between google event  and the event in **IFME**(meeting), with this, if the event is cancelled in **Google** calendar will appear as no scheduled in **IFME**  Is this OK ?

**Comment by yasirazgar** [comment]
I can work on this, will look into it coming weekend.
