### ISSUE TITLE
Setup pre-commit hook

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#1134]
# Description 

We want to hone down on formatting and consistency in our codebase, and not make folks reliant on CircleCI and Codeclimate builds.

Our pre-commit hook should include:
- `rubocop`
- `cd client && yarn lint`
- `rspec`
- `cd client && yarn test`

Currently, we ask translators to run this [online tool](https://onlineyamltools.com/prettify-yaml) to prettify our translation files. It would be great to set use a similar tool with similar settings (two space indentation) via the command-line and include it in the pre-commit hook.

# Do you want to be the assignee to work on this?

🚫

**Comment by ba1ash** [comment]
Hello @julianguyen. I want to do this issue.

**Comment by mjalkio** [comment]
Hi @ba1ash have you started to work on this? I'm also interested in the issue.

**Comment by mjalkio** [comment]
I started to look into this and I think there are a few obstacles to making it happen:

1. The project does not have a definitive development environment. This could lead to issues, for example, someone using a Dockerized setup might not be able to run the tests locally and would need a pre-commit hook that hit their container.
2. The `.git/hooks` directory can't be added to the repo, so there's no surefire way to ensure that developers setup the hooks.

It might still be valuable to create a pre-commit hook file and provide instructions on how to set it up (here? https://github.com/ifmeorg/ifme/wiki/Pull-Request-Practices), but I'm not sure how much value it will provide. What are your thoughts @julianguyen?

**Comment by julianguyen** [comment]
@mjalkio

1. A really good point about different dev environments! Hmmm, I think we want to support the local environment the most. To be honest, I've been wondering if we should deprecate our Vagrant and Docker support.

2. Why can't .git/hooks be added to the repo? O.o

**Comment by mjalkio** [comment]
The .git repo isn't versioned :(

https://www.viget.com/articles/two-ways-to-share-git-hooks-with-your-team/

**Comment by julianguyen** [comment]
^ @ScotianMan Oh noes

**Comment by julianguyen** [comment]
@mjalkio Thanks for explaining! Hmmm yeah let's stick with instructions on how to set up the hooks then!

**Comment by ScotianMan** [comment]
@julianguyen, There is a bug with detecting the private members. The github API didnt make that part easy lol. I will try and set up a test org on github tonight and sort it out. Sorry : - (

**Comment by ScotianMan** [comment]
can we disable the bot for now while I look into it @julianguyen ?

**Comment by julianguyen** [comment]
@ScotianMan That's fine by me! :) Thank you!
