### ISSUE TITLE
Update Webpack to support ES2015 such as spread operator

### ISSUE THREAD

**Issue by baohouse** [ifmeorg/ifme#1147]
# Description 

Right now the JavaScript codebase doesn't support spread operator.

# Do you want to be the assignee to work on this?

🚫

**Comment by bbulpett** [comment]
@baohouse I would like to work on this feature. I've submitted an email to [join the organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

**Comment by huoxito** [comment]
@baohouse it looks like the spread operator is already supported? I see it as a dependency: 
https://github.com/ifmeorg/ifme/blob/4a9747479b249e7878641514670650014fa9b449/client/yarn.lock#L649 

Chances are es2015 is already supported as well? This seems to compile just fine: (let me know if I'm missing something pls)

```diff
diff --git a/client/app/components/Story/index.jsx b/client/app/components/Story/index.jsx
index a30657f0..1bb306f7 100644
--- a/client/app/components/Story/index.jsx
+++ b/client/app/components/Story/index.jsx
@@ -94,6 +94,19 @@ export const Story = (props: Props) => {
     body,
   } = props;
   const condensed = !storyBy && !storyType;
+
+  const init = {
+    first: 1,
+  };
+
+  const second = {
+    ...init,
+    second: 2,
+  };
+
+  console.log('-------Spread Operator used here');
+  console.log(second);
+
   return (
     <div className={`story ${css.story}`}>
       {header(condensed, actions, draft, name, link)}
```

**Comment by baohouse** [comment]
@huoxito Ooh, thanks for checking. Can you also check spreading an array and make sure that works as well?

**Comment by huoxito** [comment]
@baohouse yep that works as well, I believe everything in [this article](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax) for example already works on current master 🚢

**Comment by baohouse** [comment]
Thanks for double-checking @huoxito, I appreciate it. I guess we can close this.
