### ISSUE TITLE
CSS Shared Classes / Styleguide

### ISSUE THREAD

**Issue by LMulvey** [ifmeorg/ifme#1149]
# Description 

Incorporate a presentational Styleguide section in Storybook that presents commonly used CSS classes for building out static pages/page elements matching the rest of the site. This could include:

- Grid helper classes (GridMany / GridItem, GridThree / GridThreeItem, etc)
- Typography - any preset classes for typography around the site
- General helper classes (div.spacer)

This could be a one-page presentation featuring a visual of the CSS class + the class names and when/where to use them. The intent is to speed up development for contributors who are new (me!) to the project and may not be familiar with all the design systems in place. This could quickly get them up to speed, or help them rapidly put pages together that play nicely with the rest of the site.

# Examples

[Starbucks Styleguide](https://www.starbucks.com/static/reference/styleguide/)
[Yelp Styleguide](https://www.yelp.com/styleguide)

# Do you want to be the assignee to work on this?

🚫 
(well, maybe, but this may be a good first issue/Hacktoberfest/for beginners issue)

**Comment by julianguyen** [comment]
This is a great suggestion! We should most definitely update our Storybook!

**Comment by alexmanzo** [comment]
I'm happy to give this a shot and get some work done on it.

**Comment by KatieOfCode** [comment]
Hello! Would I be able to work on this?

**Comment by julianguyen** [comment]
@KatieOfCode Yes! That would be great :D
