### ISSUE TITLE
Adding missing test coverage for QuickCreate widget

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#1158]
# Description 

Oh noes! Missing test coverage, let's fix that! It's also an opportunity to do any refactoring needed in the widget.

For an idea on how to spy and stub out Axios, see the Comments widget.

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by geekyrajshri** [comment]
Hi, can I take this issue to solve

**Comment by hmasila** [comment]
Let me give this a shot if no one is working on it 🤗

**Comment by julianguyen** [comment]
@hmasila Is this still being worked on?

**Comment by thumbsupep** [comment]
I can work on this!
