### ISSUE TITLE
Add missing test coverage for Notifications widget

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#1159]
# Description 

Oh noes! Missing test coverage, let's fix that! It's also an opportunity to do any refactoring needed in the widget.

For an idea on how to spy and stub out Axios, see the Comments widget.

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to join our [organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

**Comment by Gibbo3771** [comment]
@gitburd still working on this?

**Comment by Gibbo3771** [comment]
Gonna have to drop my progress on this, not had any self care time all week!

**Comment by gitburd** [comment]
This is my first contribution and I can't really figure it out. I need to
find someone to pair with me. I'm gonna post on slack.

**Comment by julianguyen** [comment]
Hey @gitburd I'm happy to pair with you, let's chat more on Slack!

**Comment by ashwanijha04** [comment]
Any updates on this? Can I help too?
