### ISSUE TITLE
Fix Dashboard actions CSS bug

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#1161]
# Description 

In languages like Vietnamese, where the translations for the words Profile and Account have two words, it breaks our UI for these buttons.

Let's fix this by letting each button take up the full width of the text it contains.

# Reproduction Steps

I saw this issue on my machine when the window width was 1280px.

1. Log in
2. Change language to Tiếng Việt

# Screenshots

In English:

![image](https://user-images.githubusercontent.com/3010728/46920446-417b0400-cfa3-11e8-8d70-1f45e0431eda.png)

In Vietnamese:
![image](https://user-images.githubusercontent.com/3010728/46920432-2b6d4380-cfa3-11e8-81ee-356fbbb4e0ed.png)

# Do you want to be the assignee to work on this?

🚫

**Comment by CSumm** [comment]
I can't seem to reproduce this, but I found an issue related to the language dropdown with text being white on white until you hover over them

**Comment by julianguyen** [comment]
@CSumm Oh, you probably have to decrease the screen width! Let me update the description with what width I saw this issue at.

Can you share a screenshot of the other bug you saw?

**Comment by CSumm** [comment]
I opened a new issue with this bug: https://github.com/ifmeorg/ifme/issues/1162

**Comment by thefifthisa** [comment]
Hi @julianguyen, I'd like to work on this!

**Comment by leejeannes** [comment]
Hey @thefifthisa - I'd love to take this if you're no longer. Let me know!
