### ISSUE TITLE
Refactor app/mailers/application_mailer.rb and add tests

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#1178]
# Description 

Refactor app/mailers/application_mailer.rb and add tests

# Do you want to be the assignee to work on this?

🚫

**Comment by toshitapandey** [comment]
I'll pick this one up.

**Comment by julianguyen** [comment]
Hey @toshitapandey, thanks for expressing your interest. We would love your help with this issue. Please follow these <a href="https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack
">next steps</a> to join our contributor community. Then you can assign yourself to this issue.

**Comment by toshitapandey** [comment]
Hey @julianguyen 
I am not able to assign this to myself. Not getting the option to type the name. Can you please take a look?

**Comment by toshitapandey** [comment]
@julianguyen Also, can you please advice what kind of refactoring are you looking forward to? I can see that the methods are really long but are you looking for breaking them down to chunks or is it something else?

**Comment by ludamillion** [comment]
@toshitapandey I'm quite new to this project but based on what I've seen most of the refactoring efforts highlighted in the issues are aimed at addressing the long methods currently wrapped in `rubocop:disable MethodLength` directives. That's definitely where I'd start.

**Comment by julianguyen** [comment]
Sorry for the late reply, @toshitapandey. Can you follow these [next steps](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack) for joining our contributor community?

As for refactoring tips,  like @ludamillion said, reducing the size of the methods is a good place to start. From there, you can find ways to simplify logic or remove unused logic.

Here's some good [general resources](https://github.com/ifmeorg/ifme/wiki/Learning-Resources#software-engineering) on refactoring.

Let me know if you need any help :)

**Comment by cpretzer** [comment]
Just writing to let you know that I'm still working on this.

**Comment by cpretzer** [comment]
Now with more coverage!
<img width="1888" alt="screen shot 2018-12-31 at 13 12 46" src="https://user-images.githubusercontent.com/3037127/50567829-55aae380-0cfe-11e9-8fc0-fca4f1e7eb1f.png">
<img width="1904" alt="screen shot 2018-12-31 at 13 13 00" src="https://user-images.githubusercontent.com/3037127/50567830-55aae380-0cfe-11e9-8ad6-618622916216.png">

**Comment by julianguyen** [comment]
Woooo this is so great @cpretzer! Thank you!!!
