### ISSUE TITLE
Adding missing tests for MomentsHelper

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#1183]
# Description 

Add missing tests! Use as an opportunity to refactor code (including getting rid of Rubocop disable comments like `# rubocop:disable MethodLength`)

# Do you want to be the assignee to work on this?

🚫

**Comment by rhiroyuki** [comment]
Can I do this one @julianguyen ? :)

**Comment by julianguyen** [comment]
@rhiroyuki Go ahead and assign yourself to the issue :D

**Comment by julianguyen** [comment]
I recommend moving out new_moment_props and edit_moment_props to a new helper i.e. MomentFormHelper

**Comment by gr1d99** [comment]
hi @julianguyen, can I pick this issue?

**Comment by bmwachajr** [comment]
Hi @julianguyen, I have reached out to @gr1d99 and I will be taking on this issue.
