### ISSUE TITLE
Adding missing tests for MoodsHelper

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#1184]
# Description 

Add missing tests! Use as an opportunity to refactor code (including getting rid of Rubocop disable comments like `# rubocop:disable MethodLength`)

# Do you want to be the assignee to work on this?

🚫

**Comment by Veith3n** [comment]
I can do this one 😊

**Comment by julianguyen** [comment]
@Veith3n Thanks for expressing your interest! We'd love your help with this. Please follow these [next steps](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack) to join our contributor community.

**Comment by emilyyz92** [comment]
Hi! I'm interested in helping with this. Has this issue already been assigned to someone or may I jump in?

**Comment by julianguyen** [comment]
Hey, @emilyyz92 looks like no one is working on this! Please follow these [next steps](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack) to join our contributor community and then you can assign yourself to the issue :)

**Comment by emilyyz92** [comment]
Awesome :)

**Comment by emilyyz92** [comment]
Hi @julianguyen! I started looking at this issue but saw that Veith3n already made a PR on this; although his / her change didn't seem to be merged. Not sure if there's additional issues on top of what they did? https://github.com/ifmeorg/ifme/pull/1194

**Comment by julianguyen** [comment]
@emilyyz92 Hmm yeah, @Veith3n hasn't updated the PR in a while. How far along are you with what you started working on? If you got pretty far, I'm fine with closing that PR. Sorry about that, yeah that person should have assigned themselves to the issue to avoid confusion.

**Comment by emilyyz92** [comment]
I see - sounds good, I can close the PR and open a new one once I finish up, thanks
