### ISSUE TITLE
Medications units for total and dosage can break in translated locales

### ISSUE THREAD

**Issue by matcha440** [ifmeorg/ifme#1264]
# Description 
If running in any local that has translated unit names for tablets, upon saving a medication the application fails to reload the Medications page.  In the logs it appears that the application is attempting to reference the translated value instead of the key name.

# Reproduction Steps
(This will use German as an example, but the steps can apply to any language that has the tablets unit translated)
**WARNING: Going through these steps I believe will render Medications unusable on that account, or at least until the data is manually corrected in the database.**
1. After logging in, change the language to `German`.
2. Go to the page labeled `Arzneimittel` and click `Neues Arzneimittel `.
3. Fill in all of the required fields, using `Tabletten` as the units for `Gesamt` or `Dosis`
4. Upon saving, you should then see that the Medications page will fail to load. 

Info from my logs when I tried this in German:
```
20:51:49 web.1    |   Rendering medications/show.html.erb within layouts/application
20:51:49 web.1    |   Rendered medications/_story_body.html.erb (1.6ms)
20:51:49 web.1    |   Rendered medications/show.html.erb within layouts/application (2.8ms)
20:51:49 web.1    | Completed 500 Internal Server Error in 8ms (ActiveRecord: 0.8ms)
20:51:49 web.1    |
20:51:49 web.1    |
20:51:49 web.1    |
20:51:49 web.1    | ActionView::Template::Error (translation missing: de.medications.units.Tabletten):
20:51:49 web.1    |     4: </div>
20:51:49 web.1    |     5: <div>
20:51:49 web.1    |     6:   <strong><%= t('medications.quantity') %></strong>
20:51:49 web.1    |     7:   <%= t('medications.units.display', count: local_assigns[:medication].total, unit: t("medications.units.#{local_assigns[:medication].total_unit}", count: local_assigns[:medication].total)) %>
20:51:49 web.1    |     8: </div>
20:51:49 web.1    |     9: <div>
20:51:49 web.1    |    10:   <% if local_assigns[:medication].daily? %>
```

# Screenshots

# Do you want to be the assignee to work on this?

✅ 
🚫

**Comment by julianguyen** [comment]
Thanks for reporting this! I'll take a look!
