### ISSUE TITLE
Nicer email template

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#127]
Email notifications has just been implemented, however the email template could use more styling. The template should match the CSS in the app.

This is what it currently looks like in gmail:
![screen shot 2016-05-16 at 4 03 59 pm](https://cloud.githubusercontent.com/assets/3010728/15306535/34f2c792-1b80-11e6-94ec-c4b707b6e41b.png)

This looks like a helpful guide: http://www.simonnordberg.com/creating-robust-email-templates-in-action-mailer/

**Comment by scroniser** [comment]
FYI - I'm going to take a swing at this one today at WSC :)

**Comment by kindlingscript** [comment]
Starting to work on this now ☺️ (and that article was a great starting-off point, thanks! 👏)

**Comment by andy5995** [comment]
Seems like it would be a good idea to make changing the sender name part of this PR. Presently emails come in as being from "smtp.sendgrid.net"

Yahoo sees it as spam (I tested an invitation with my Yahoo address), maybe changing the sender name or altering some of the headers would help prevent it from getting spammed?

I could probably handle this ticket, including the template issue above. @kindlingscript hi! :) Are you still working on this?

**Comment by HashNotAdam** [comment]
It doesn't look like if-me.org has SPF or DKIM records so, while the from address should absolutely be changed, the secret sauce will be creating a new DNS record.

**Comment by andy5995** [comment]
>Seems like it would be a good idea to make changing the sender name part of this PR. Presently emails come in as being from "smtp.sendgrid.net"

Looks like this will get addressed by #752

**Comment by francisbrito** [comment]
Hello,

I'd like to contribute into this project and thought this task could be a nice place to start if it is still relevant. I have read the article presented in the first comment and I _think_ I can do it.

By the way, I'm rather new to Ruby/Rails so all suggestions are welcome.

**Comment by aamarill** [comment]
@andy5995 Is this still needed? @francisbrito did you ever hear back from someone?

**Comment by francisbrito** [comment]
@aamarill no, I haven't.

I'm still willing to contribute if it hasn't been done yet.

**Comment by aamarill** [comment]
@francisbrito sounds good!
Hopefully @andy5995 or @baohouse can just quickly confirm this is still needed. 
Best of luck!

**Comment by andy5995** [comment]
@francisbrito I see you inquired several months ago. So sorry that you didn't receive a response. I'll post this ticket in the Slack chat room and request that some specifics get posted here.

**Comment by andy5995** [comment]
No, not yet. The admin has been on sick leave.

Are you on the Slack chat workspace or would you like an invite?

**Comment by francisbrito** [comment]
Currently I'm not part of the project's Slack. Would love to be, if possible

**Comment by andy5995** [comment]
I sent you an invite using the email listed on your GitHub profile. Actually I tried that last week. Is it in your spam folder by chance?

**Comment by tsara27** [comment]
@julianguyen Can I work on this issue?
I have free time now. 😺

**Comment by tsara27** [comment]
@julianguyen I hope you had great days. ❤️ 

Here's the template I've made for the email.
![screen shot 2018-11-20 at 16 44 24](https://user-images.githubusercontent.com/3486644/48764926-99640380-ece3-11e8-93ba-3b834a2265fc.png)

What do you think?

**Comment by julianguyen** [comment]
I also realized we can add an unsubscribe link in the footer! It should link to `edit_user_registration_path` and feel free to use use Google Translate the `Unsubscribe from emails` copy.

**Comment by tsara27** [comment]
> This looks great @tsara27! It's been up and down for me, thanks for asking. I hope things are decent with you 💜

@julianguyen Thank you Julia. I was having bad times a month ago. I was trying to believe that anything bad that I got was for a good reason and I was getting much much better from there. ❤️ 


> Oooh, beefing up the email templates. Thanks for working on this @tsara27!

Sure. Nice suggestions @nshki. I will do that. Thanks! 🎁
