### ISSUE TITLE
Create autosuggestions for categories when typing input on mobile in New Moment

### ISSUE THREAD

**Issue by CSumm** [ifmeorg/ifme#1285]
# Description 
Create autosuggestions for categories when typing input on mobile in New Moment.

# Reproduction Steps

A mobile phone is required to reproduce this issue.

1) Sign into if-me using a new or existing profile.
2) Navigate to Moments page.
3) Click on New Moment.
4) Scroll down to Categories input.
5) Observe what occurs when typing input into the Categories input.

Actual Result:
No autosuggestions occur when typing input into Categories input. May cause hindrance in user experience.

Potential Fix:
Add autosuggestions in a input dropdown that the user can select if it matches what they are typing. Users can also add their own to the list.

# Screenshots

![fam family](https://user-images.githubusercontent.com/31711543/48974735-3f8a7300-f02e-11e8-82fe-e63a6ffc267f.PNG)

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by LMulvey** [comment]
I'm interested in looking at this but a few questions:
1) Do the suggestions exist at all right now? I couldn't get them to work in mobile (obviously) or on desktop. 
2) Where are the suggestions supposed to be pulled from? The user's previously used categories? A pool of common categories?
3) If this is "new", is there any styling done for a feature like this that I could model after?

**Comment by julianguyen** [comment]
@LMulvey To answer your questions:
1. So the autocomplete only shows up if you have existing values.
2. We want to add the premade values even if they aren't created yet.
3. We don't need new styles, we can leverage what already exists.

Good questions :)

**Comment by LMulvey** [comment]
Thank you! I'll try and take on this issue 😄

**Comment by LMulvey** [comment]
Going to have to drop myself from this. I've had a few things come up that have taken away my free time. Sorry everyone!

**Comment by amarpathak** [comment]
Is it done ? I can take up this

**Comment by someotherkyle** [comment]
I'll take a look at this

**Comment by someotherkyle** [comment]
Was wrapping up some other stuff but I'm shifting my attention here now. Is there a collection of categories we would like to start with? Should I source popular categories from the db?

**Comment by julianguyen** [comment]
I think for privacy concerns, we shouldn't be sourcing through user data. We should use pre-made values. We actually have this feature on https://www.if-me.org/categories, https://www.if-me.org/moods, and  https://www.if-me.org/strategies when you don't have any posts created. There's a button that let's you add pre-made ones. We want to be able to do that from inside of the editor as well.

**Comment by someotherkyle** [comment]
I believe I've tracked it to https://github.com/ifmeorg/ifme/blob/master/client/app/components/Input/InputTag.jsx which has a //TODO at the top referring to 'react-autocomplete' being deprecated and recommending a switch to 'react-autosuggestion'. This issue may be above my experience level but that's how we learn, right? Seeing others take & abandon this issue makes me want to stick it out but I'm unsure where to go from here.

**Comment by julianguyen** [comment]
I'm going to close this issue in favour of https://github.com/ifmeorg/ifme/issues/659 which will recommend existing categories, moods, and strategies based on what you've written in your moments entry.
