### ISSUE TITLE
Long prose in yaml files is hard to work with

### ISSUE THREAD

**Issue by matcha440** [ifmeorg/ifme#1315]
# Description 
The yaml file has in some places entire paragraphs of text, which in order to be able to read while making modifications you have to scroll horizontally.  As another consequence, it can be hard to measure progress on a translation since not all lines are equal.  Yaml files do support multi-line text, so I think it is possible to break these up so they are easier to read.

For example, if we look at [this line](https://github.com/ifmeorg/ifme/blob/v6.3.0/config/locales/en.yml#L391), it could be done like this and it would still work I think
```yaml
      data_access_answer: |
        Data is not given or made accessible to any third party.
        Deleting your account will remove all of your data.<br><br>
        User data is analyzed within the app to provide customized recommendations.
```

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by harshlele** [comment]
Hey, I'm new to open source, and this issue looks like it's pretty easy to solve. Can i work on this?

**Comment by matcha440** [comment]
Yeah it seems pretty easy, but this has somewhat been a take it or leave it type thing for me.  Since word wrapping gets around this for the most part, maybe this isn't too important to have.  I'm still waiting for what others may have to say on the matter, though.

**Comment by julianguyen** [comment]
@anushkajj This issue is still available! Feel free to assign yourself to it and start working on it!

**Comment by anushkajj** [comment]
Hey! Will keeping the character limit to around 120 per line work?
I think this will prevent the problem of horizontal scrolling to read the files.

**Comment by GayathriVenkatesh** [comment]
@julianguyen @anushkajj I would love to help out with this issue! Let me know if this is something I can still work on :)

**Comment by julianguyen** [comment]
@anushkajj @GayathriVenkatesh Sorry for the late reply! I think 80 characters work! Feel free to work on this together

**Comment by GayathriVenkatesh** [comment]
Hi @anushkajj, could you please fill me in on your progress? I would like to help out with whatever's left.

**Comment by julianguyen** [comment]
@GayathriVenkatesh Great job doing this for en.yml! We'll want to do this for the other locales.
