### ISSUE TITLE
General refactoring of codebase

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#134]
- Refactoring models, views, controllers
- Improving test coverage
- Removing unneccessary files
- Whatever else you find :)

**Comment by julianguyen** [comment]
Would like to put title text in the following commit https://github.com/julianguyen/ifme/commit/73d6a9c3738034d0bcaad2195981973d4aec52b6 in en.yml. I tried doing this but it wasn't working.

**Comment by starbelly** [comment]
@julianguyen I'm definitely going to join in on this before doing anything else ( sans bug fixes ). The core must be sane, clean, and stable before anything else. I would actually recommend a feature freeze until this is done and all known bugs are squashed.

**Comment by calebthompson** [comment]
Agreed, within reason. I'd certainly avoid nice-to-have changes pending completion of a general overhaul that will make the project both safer and friendlier to new and existing contributors.

**Comment by starbelly** [comment]
After looking around last night, I think a complete freeze is in order. It doesn't seem like this app is any kind of mission critical status right now. With that said, it doesn't make any sense to squash bugs that will potentially become irrelevant post-refactor. 

Without going into detail:

* Refactor configuration ( e.g., gem files, initializers, etc. )

* Refactor schema and migrations

* Refactor models

* Refactor controllers

* Refactor views

* Refactor javascript

* Refactor CSS

 The refactoring definitely needs to be done in order, as changes will trickle up. We'll squash open issues as we go along the way. In addition we need to set some guide lines, style policies, etc. or this refactor in some ways will be for not. For example, IMHO we should aim to be rubocop complaint (within reason). In addition everyone needs to be following best practices and writing idiomatic ruby code. If you need help in this area, please reach out. 

  I'm going to hop on the slack channel later this evening for discussion and I'm going to open an issue for the refactoring of configuration.

**Comment by julianguyen** [comment]
Thanks for raising these concerns! I definitely agree that refactoring needs to be done. @kkelleey has been refactoring things for the Groups and Meetings models. @aayushpi expressed interest in refactoring the CSS. I will around tonight to discuss as well :)

**Comment by kkelleey** [comment]
@starbelly I can hold off on any more model, controller and view refactoring until the first two are finished. 

With regards to schema refactoring, @julianguyen should it be possible for a group to have more than one leader? If not, I suggest we remove the leader attribute from GroupMember and add a leader_id field to Group. That way we could get the leader of a group without joining through group_members.

**Comment by starbelly** [comment]
@kkelleey and @julianguyen I have some thoughts on redesigning the schema. Specifically all the parts before application specifics. It might be way too much for this project though, just to get a better handle on the scope of this project. Attached is something similar to what I have in mind. In the attached files everything starts with company, but that does not apply here, so just ignore the company references. Just want you guys to get a general idea of what I'm thinking in regards to the schema. This is pretty complicated, but it's designed for validation and longevity. The biggest caveat to using this schema is relies on all the states, counties, cities, zip codes being pre-populated. It would also need to be adjusted for the US and Canada (once again need clarification on scope of project).

![schema](https://cloud.githubusercontent.com/assets/8829116/15767022/2b20dabe-290a-11e6-85f1-1bae8ce8c160.png)

**Comment by julianguyen** [comment]
@kkelleey I believe it should be possible for a group to have multiple leaders. This feature is supposed to be an organizational tool for support groups (online/offline) and many of them have multiple facilitators!

**Comment by julianguyen** [comment]
@starbelly Thanks so much for raising this! Since we are aiming to be HIPAA compliant, we should not collect more information like home address. We want to anonymize the data as much as possible. Overall, the app doesn't rely on location and any other identifiable factors to function. It's a closed network for users to only connect with people they actually know. In the future, we might open this up and allow users to discover new people. But that's not a priority since the app is supposed to be a communication tool with loved ones. So ideally, it would be great if people around the world could use the app :)

I do not have a security background so I'm not quite sure why Devise isn't secure enough. Could to explain why briefly? Also, if we didn't use Devise... would we have to implement our own authentication system?

**Comment by julianguyen** [comment]
I think refactoring these two first is a good idea:
* Refactor configuration ( e.g., gem files, initializers, etc. )
* Refactor schema and migrations

Does anyone want to take this on? I can help as much as I can of course.

**Comment by starbelly** [comment]
@julianguyen I was already planning on taking those on, but there needs to be involvement from everyone on the design when it comes to the schema...
 
 Here is an updated ERD of the base schema:

![erd](https://cloud.githubusercontent.com/assets/8829116/15770660/0a16ba66-292b-11e6-9d0a-3fb8aca2110d.png)

**Comment by starbelly** [comment]
> @starbelly Thanks so much for raising this! Since we are aiming to be HIPAA compliant, we should > not collect more information like home address. We want to anonymize the data as much as possible. Overall, the app doesn't rely on location and any other identifiable factors to function. It's a closed network for users to only connect with people they actually know. In the future, we might open this up and allow users to discover new people. But that's not a priority since the app is supposed to be a communication tool with loved ones. So ideally, it would be great if people around the world could use the app :)


 Yeah, saw your message on slack. I must have been looking at schema for something else last night, I swore I saw address fields. We'll just forgot about that. In the comment above is an updated ERD. 


> I do not have a security background so I'm not quite sure why Devise isn't secure enough. Could you explain why briefly? :P Also, if we didn't use Devise... would we have to implement our own authentication system?

 The problem with canned authorization and authentication is primarily bloat. Besides being yet another gem in your app,  devise and similar packages have to work everywhere. The generic support brings with it lot of code that will never be run for your app or perhaps shouldn't run or even get loaded, but does. More code = more potential security problems, at least in this context. Aside from that, authentication and authorization usually require lots of customization, especially so if you're using a canned solution.  You spend more timing fighting the system imposed by the canned solution then getting things done. 

  I also think that it's better to have a full understanding of how the security mechanisms in your application work instead of depending the magic of third-party package, that's definitely a wee bit dangerous.

**Comment by julianguyen** [comment]
@starbelly In your proposed DB schema, I like the the idea of users have role assignments. I'm not sure what resource_traits and resource_actions are... could you explain what that means?

I personally do not have experience writing a authentication system that also allows for Google oauth. Perhaps we can hold off on that for later? I think we should focus our refactoring on the config/migration/etc. files and DB schema.

Would you like to work on refactoring the config/migration/etc. files first?

Hey @kkelleey, I think you can continue refactoring controllers and models. Let me know if that's a bad idea or if you want to work on something else :)

**Comment by starbelly** [comment]
@julianguyen The concept here is that users have roles.

Example:

* Resource is anything that is or appears to be resource from the outside world, for example moments, but could also be an arbitrary route, anything a user can access

* Resource can have actions such as CRUD on Moments

* Resources can have traits such as 'comments' or 'why' or 'fix'

* Traits can have actions just like resource similar to CRUD, but mostly limited to read and write
(i.e., a user must have the appropriate rights to read moment.fix or to change moment.why)

* Roles have defined resources are further defined by authorizations on said resources and furthermore authorizations on a resources actions, traits, and trait actions. 

* Users and groups can have resources as well, the system should look to user and group role authorizations if authorization can not be met via a top level role. You can look at the three, roles, user roles, and group roles as classes that inherit from the former. 

 I hope this answers some of your questions. I can provide examples later on. Should probably open a new issue on this. We need to discuss this a lot before going ahead with it and it's not something that has to be done _NOW_, I wanted to start the discussion first : )

**Comment by julianguyen** [comment]
Yeah I think a new separate issue for model refactoring needs to be created.  Thanks for explaining!
