### ISSUE TITLE
Include filters in the url of the Resources page

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#1372]
# Description 

It would be helpful to include the tags that are being filtered on our [Resources](https://www.if-me.org/resources) page. It makes it easier to share a link with someone who is looking for particular mental health resources.

Let's set this up using Rails so that we don't have to introduce react-router.

Example:

`https://www.if-me.org/resources?filter=directory&filter=therapy` would yield (vice-versa):

![image](https://user-images.githubusercontent.com/3010728/53049533-3140cd00-344c-11e9-8da2-7309d30072bc.png)

# Do you want to be the assignee to work on this?

🚫

**Comment by rhiroyuki** [comment]
Hi Julian!
This issue includes the `react` and `ruby on rails` labels, so I guess it's for the whole feature. Would it be OK if I tackle only the `ruby on rails` part? I'm not comfortable in developing in `react` yet :P

**Comment by julianguyen** [comment]
@rhiroyuki I think you'll need to inevitably modify the React component for Resources though. But you can try and keep us posted on where you end up?

**Comment by rhiroyuki** [comment]
Sure thing! I can give it a try :)
