### ISSUE TITLE
Inconsistent padding on forms with format controls

### ISSUE THREAD

**Issue by Gibbo3771** [ifmeorg/ifme#1373]
# Description 

When creating a new moment/category/mood/strategy, any form field that hosts the format controls has some inconsistent padding going on. I suggest that the padding be adjusted to prevent odd resizing to occur after the first character is typed. 

# Reproduction Steps

I would say it's a bug. Go to Moods, then new and in any form with format controls, click and you can see that the caret is placed. It's _barely_ inside the box, enter any character and it will fix. If you can backspace the character away, and see that the padding change remains consistent, until you backspace again and remove a phantom character.

# Screenshots
![padding-issue](https://user-images.githubusercontent.com/10871784/53096779-cf4d9980-3517-11e9-92d6-49707ead52d0.gif)

# Do you want to be the assignee to work on this?

🚫

**Comment by Gibbo3771** [comment]
Just an update on this, I have tested the current code across different browsers and this seems to be a problem in Firefox. Chrome is working fine, so not sure how to tackle it.

**Comment by ajquintero** [comment]
Currently trying to figure out the problem for Firefox.

**Comment by Gibbo3771** [comment]
> Currently trying to figure out the problem for Firefox.

Are you able to reproduce? I am running the following OS and Firefox version. I can't confirm the bug on Windows, as I don't have a windows machine at the moment.

- 4.19.24-1-MANJARO
- Mozilla Firefox 65.0.1
- i3 version 4.16.1

**Comment by ajquintero** [comment]
@Gibbo3771 I'm running on a Mac (OS 10.14.3) and Firefox 65.0.1. The issue is reproducing.

**Comment by vildevev** [comment]
Is anyone working on this? If not I'm interested.

**Comment by ajquintero** [comment]
@vildevev I'm looking into it again, but feel free to work on it as well!

**Comment by neon98** [comment]
@vildevev are you working on this? If not I'd want to work on this.
