### ISSUE TITLE
Deploy storybook site to production

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#1390]
# Description 

Currently, our storybook site is only accessible through the local development environment i.e. running `yarn storybook` in the client directory.

We want to deploy it to production as well and have it viewable at `https://www.if-me.org/design`.

We can do that by [exporting Storybook as a static app](https://storybook.js.org/basics/exporting-storybook/) and pointing the output to the new route.

Ideally, we want to this to happen in the build step in our CircleCI config so that we don't have to commit the output to master. 

# Do you want to be the assignee to work on this?

🚫 This would be a great issue to work on for folks interested in deploys! I'm happy to help if needed :)

**Comment by paschalidi** [comment]
@julianguyen @KatieOfCode please let me know if I could help with anything here.

**Comment by julianguyen** [comment]
@paschalidi maybe you could help review this PR: https://github.com/ifmeorg/ifme/pull/1391 and potentially pair with @KatieOfCode? :D

**Comment by paschalidi** [comment]
@julianguyen I will have a look tomorrow on the PR. Thanks for letting me know. 
Can you maybe give me an idea of what the goal of https://github.com/ifmeorg/ifme/pull/1391 is? Sorry but the description is not very clear to me?

**Comment by julianguyen** [comment]
@paschalidi Yeah the goal of this issue is to deploy a static version of the Storybook site (where we house our React components and CSS best practices) on production (at `https://www.if-me.org/design`).
