### ISSUE TITLE
Reporting abuse and harassment, blocking allies

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#14]
There needs to be a feature in place for doing so and a moderation system for that

# Requirements

- Being able to report a user by clicking a link from their profile or from a comment
- When that happens, that data is saved to a new table in the database (include the reportee user id and reported user id and an optional comments column)
- You would have to create the ability to make a User an admin account, I would use column as a flag in the db for that. 
- Any “admin” user and can go in and open a panel and block users
  - Admin users also see the emails of the users, so that they can email them for any follow-up
  - Make the link to this dashboard obvious in the header. I suggest maybe a smaller header above the current one that appears just for admin users
- Blocking users entails not being able to sign into their account and getting an email and message on the site that says their account has been blocked for violating Terms and Conditions (that is currently being worked on but mention it anyways :P)
- We don’t need to delete the account, so again set a column as a flag for the "block" state

For now, the only way you can add someone as an admin is through rails console. We don't need a UI for that. Definitely add documentation on how to do that in the README.

**Comment by estermer** [comment]
Is this issue still something you need help on? I can maybe try and tackle this

**Comment by julianguyen** [comment]
@estermer Yes that would be great! You can work on this as a more long term project :) We should talk more about this feature on Slack!

**Comment by estermer** [comment]
ok cool

**Comment by cartothemax** [comment]
@estermer  Has any work been done on this issue?  I was browsing through issues and noticed this had been sitting for a bit and thought I could help out with it?  I don't want to step on any toes though.  Thanks!

**Comment by estermer** [comment]
@cartothemax I got busy with work. You are more than welcome to tackle this. Thanks.

**Comment by cartothemax** [comment]
No worries @estermer.  I have had the same challenges myself.  @julianguyen would it be possible to assign this to me?  I am going to finish up https://github.com/julianguyen/ifme/issues/442 and then get this going as well.  Thanks!

**Comment by jarmstrng** [comment]
As this is a good-sized feature, I created a Project for it [here](https://github.com/julianguyen/ifme/projects/8?)

**Comment by eiguike** [comment]
Hello! I would like to help in this feature, how can I accomplish this?

**Comment by andy5995** [comment]
Hi @eiguike ! Thanks for your interest. If you send an email to join.ifme@gmail.com you will receive the details on how to join our _Slack_ development chat room. :)

**Comment by alvarocasadoc** [comment]
Is there anyone still working on this? I think I can help getting it done :)

**Comment by julianguyen** [comment]
Hey @alvarocasadoc, no one is! Feel free to work on it. Let's coordinate on Slack! :D

**Comment by camillevilla** [comment]
🎉Excited to announce that our [Rails Girls Summer of Code](https://railsgirlssummerofcode.org/) team, Team Rubies (@aSquare14 and @prateksha) will be working on this feature this summer. 🎉

@alvarocasadoc and I will help them with designing and implementing this feature. We look forward to collaborating with the community to deliver this feature to empower our users to create safe spaces. 

I'll be updating this comment with links out to related tickets as the summer goes on. 
#870: 'report user' button on user profiles
#871: 'report' button on comments
#873: notification email for banned users

 To be split out:
- [ ] admin interface (might need a design for this)

**Comment by alvarocasadoc** [comment]
@prateksha, @aSquare14 and I have added some additional notes on the blocking feature: 

**Banning feature**
- Add ‘ban user’ button to user profiles (only visible to admins)
- Add ‘banned’/’blocked’ flag to User model
- Check flag to prevent blocked users to log in

**Blocking feature**
- Create a new relationship to store blockings information.
- Add ‘block user’ button to user profiles.
- Implement new action to store the blocking information.
    - Maybe can test this feature both by UI and rails console.
- Deleting allyships when a new blocking is created.
    - Find allyship and destroy it.

- Hiding user from any user searches.
    - User B should not see user A profile.
    - User B should not see user A in user searches.
    - User A should not see user B profile completely, just an unblock option.

- Blocking in groups. Instant notification.
    - When user A blocks user B -> User A gets a notification with the list of the groups they both belong to and is asked to leave or stay in them. Also is told that their allyship will be lost (in case they were allies)

Also, tests should be written to make sure all these features are correctly implemented. 


Feel free to add any notes or thoughts!
