### ISSUE TITLE
Adding missing tests for GroupsFormHelper

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#1408]
# Description 

Looks like we're missing tests here! This can also be an opportunity to refactor the code itself! 🎉 

# Do you want to be the assignee to work on this?

🚫

**Comment by js-sapphire** [comment]
I would like to take this up.

**Comment by scw248** [comment]
Hi @julianguyen and @js-sapphire , is this still being worked on, or could I give it a try?

**Comment by js-sapphire** [comment]
Sure. Go ahead. @scw248

**Comment by scw248** [comment]
Thanks!
