### ISSUE TITLE
Improve accessibility for pre-made cards

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#1462]
# Description 

When you sign up for the site for the first time and navigate to the Categories page, you see the following pre-made categories which you can choose to add by hitting the "Add All" button.

<img width="765" alt="image" src="https://user-images.githubusercontent.com/3010728/56784834-67316300-67a7-11e9-8088-352870ab5c22.png">

If you hover over the text, you'll notice that they link to the `/categories` page. This is a confusing user experience and bad for accessibility.

For pre-made categories, moods, and strategies, let's remove the link while preserving the styling of the text.

Thank you to @toshitapandey for calling this out!

# Do you want to be the assignee to work on this?

🚫

**Comment by gr1d99** [comment]
I'm intrested @julianguyen, can I own it

**Comment by julianguyen** [comment]
That would be awesome @gr1d99! Thanks! Could you assign yourself to the issue?
