### ISSUE TITLE
Delete and Edit tooltips can be misconstrued as a button

### ISSUE THREAD

**Issue by toshitapandey** [ifmeorg/ifme#1463]
## Description 

When I go to `/categories` route after I have added some of the categories, I can edit or delete the categories that I have. As of now, the tooltip can be misconstrued as a button. It should look like info rather than a button. 

## Reproduction Steps

- Sign up (_if you haven't already_)
- Go to categories (_by clicking Categories on the left-hand side panel_)
- Click on "Add all" (_this will add all the listed categories to your categories_)
- Hover on "edit" or "delete" icon at the right-hand side of each category

### Current implementation: 
![image](https://user-images.githubusercontent.com/3788470/56784768-db075600-680f-11e9-8860-0f5ed548fda0.png)
### Expected implementation: 
![image](https://user-images.githubusercontent.com/3788470/56784900-7f899800-6810-11e9-9afa-0d979ec3cdc4.png)

For doing this, title attribute can be added to the anchor tag. 
e.g.
```
<a title="Some text that will show up when I hover over this link">
  My link
</a>
```
There can be better ways of handling this.

**Comment by 256hz** [comment]
I'd like to give this one a shot please!

**Comment by julianguyen** [comment]
We would love your help @256hz! Please assign yourself to the issue - thanks ^^

**Comment by 256hz** [comment]
I'm still working on getting the site running locally, I'll claim it as soon as I do, don't want to sit on it in case it takes me a while.  Thanks!

**Comment by 256hz** [comment]
I solved this in the tooltip CSS and made a pull request.   Hope this helps!
