### ISSUE TITLE
Add rubocop-performance

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#1473]
# Description 

Performance Cops has been removed from RuboCop 0.68. So we need to add the `rubocop-performance` gem!

In our `.rubocop.yml`, we need to add:

```yaml
require: rubocop-performance
```

More information: https://github.com/rubocop-hq/rubocop-performance

# Do you want to be the assignee to work on this?

🚫

**Comment by meanmachin3** [comment]
Closing down this issue, as [PR #1476](https://github.com/ifmeorg/ifme/pull/1476) solves it
