### ISSUE TITLE
%{icon} appearing on Deutsch version

### ISSUE THREAD

**Issue by fayepal** [ifmeorg/ifme#1479]
# Description 

%{icon} appearing on Deutsch (German) translation

# Reproduction Steps

1. Choose Deutsch in the languages dropdown
2. Click on the Momente, Kategorien, Stimmungen, Arzneimittel, Gruppen tabs

# Screenshots

<img width="1099" alt="image" src="https://user-images.githubusercontent.com/5814811/57366878-2ca4ce80-7188-11e9-8a8d-c4056e998c60.png">

# Do you want to be the assignee to work on this?

🚫

**Comment by adamjpena** [comment]
@fayepal seems the intention here is to do something like this:
`<%= raw t('moments.index.instructions', icon: t('moments.new')) %>`

However, this line of copy doesn't exist in any of the other languages, probably makes sense to remove it. Happy to fix this one either way.

**Comment by julianguyen** [comment]
@adamjpena Looks like you're right! It would be great to fix this. Thanks Adam :D
