### ISSUE TITLE
Documentation for docker installation needs update

### ISSUE THREAD

**Issue by Iphytech** [ifmeorg/ifme#1506]
# Description 
`docker-compose exec app rake db:create db:migrate` doesn't work because the container is not running correctly. [Link](https://github.com/ifmeorg/ifme/wiki/Installation)

# Reproduction Steps
`docker-compose run app rake db:create db:migrate` this is an alternative for the container to start running correctly.

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by hovancik** [comment]
Docs tell us to run `docker-compose up` and then `docker-compose exec ...` to create a DB and migrate. This wont work as `docker-compose up` will have error in app container as we have no database yet.

I think the docs should tell to set up in a slightly different way: 

`docker-compose build` to setup container
`docker-compose run ...` (which will start new container, as opposite to `docker-compose exec ...` which runs in existing one )

and then finally `docker-compose up` when everything is ready.

**Comment by lsfernandes92** [comment]
What @hovancik  said is correct. But also I found confusing the part that says:

run `docker-compose up` or open a shell using `docker-compose -f docker-compose.yml -f docker-compose.test.yml run --rm app
bash`"

**Comment by lsfernandes92** [comment]
What @hovancik said is correct. But also I found confusing the part that says:

run 
`docker-compose up`
or open a shell using 
`docker-compose -f docker-compose.yml -f docker-compose.test.yml run --rm app bash`

It's seems that these two commands are equal, but the first is to start the container and the second one is just to enter in the mentions container's(**docker-compose.yml** and **docker-compose.test.yml**) shell if needed.

And for those who are new I think it's worth to mention that Docker Compose has to be installed as well(for linux users).

**Comment by dhuang612** [comment]
Hey, I was wondering if anyone was actively working on getting the docker setup files updated?

New users are having issues getting up and running:

![NewUser](https://user-images.githubusercontent.com/49162249/73409236-aeb3c500-42cc-11ea-8971-2eda0de86b5e.png)

**Comment by PeasOfMind** [comment]
Ah sorry! I haven't touched this at all. Feel free to dive into it. I've unassigned myself.

**Comment by dhuang612** [comment]
@julianguyen 
Hey Julia,

I wanted to confirm, for making changes to the wiki do we just edit the document itself from github.com? Or is there another method?

Thanks

**Comment by julianguyen** [comment]
@dhuang612 Yeah we should update the Wiki! But if there's any changes that need to be done in the Dockerfile itself, we should also do that too!

**Comment by wigsters52** [comment]
Is this something that still needs worked on. I would love to help out!

**Comment by julianguyen** [comment]
@wigsters52 Sorry for the late reply! Yeah it looks like this still needs updating.

**Comment by andrew-schutt** [comment]
I updated the docs for installing via Docker here -> https://github.com/ifmeorg/ifme/wiki/Installation#docker

Thank you to everyone for the steps needed. I tested the steps locally after deleting all of my local Docker images successfully and tried to add clarity.
