### ISSUE TITLE
Address // eslint-disable-next-line import/no-cycle

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#1546]
# Description 

I introduced `// eslint-disable-next-line import/no-cycle` throughout the codebase after updating all of our npm packages including React, Flow, and ESLint. This was done so that our lint checks would pass.

We want to remove these comments and actually fix the cycle issue in the following files:
- [x] `/client/app/components/Form/DynamicForm.jsx` (@dhuang612)
- [x]  `/client/app/components/Form/index.jsx` (@dhuang612)
- [x]  `/client/app/components/Header/HeaderProfile.jsx` (@dhuang612) DONE
- [x]  `/client/app/components/Header/index.jsx` (@dhuang612) DONE
- [x]  `/client/app/components/Input/index.jsx` (@dhuang612) DONE
- [x]  `/client/app/components/Input/InputSwitch.jsx` (@dhuang612) DONE
- [x]  `/client/app/widgets/QuickCreate/index.jsx`

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by sharmilaraghu** [comment]
I am a beginner and I would like to work on this issue

**Comment by julianguyen** [comment]
Hi @sharmilaraghu, thanks for expressing your interest! Please follow these [next steps](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack)!

**Comment by someotherkyle** [comment]
I'm also interested in contributing but don't want to step on anyone's toes. Let me know if there's a constructive way for me to get involved.

**Comment by julianguyen** [comment]
@someotherkyle and @sharmilaraghu: I think you two could split up work based on these files:
* `/client/app/components/Form/DynamicForm.jsx`
* `/client/app/components/Form/index.jsx`
* `/client/app/components/Header/HeaderProfile.jsx`
* `/client/app/components/Header/index.jsx`
* `/client/app/components/Input/index.jsx`
* `/client/app/components/Input/InputSwitch.jsx`
* `/client/app/widgets/QuickCreate/index.jsx`

**Comment by someotherkyle** [comment]
I've found an unassigned issue that I'm going to focus on. If I can be of help here let me know and I'd be glad to.

**Comment by dhuang612** [comment]
Hi,
I was wondering if I could get an update on if there is any work left to be completed for this?

Thanks!

**Comment by someotherkyle** [comment]
Sounds good!

**Comment by ericlee1996** [comment]
Hi, beginner here.
Would love to tackle an issue/ help out if there's any left

**Comment by julianguyen** [comment]
Would looking at  `/client/app/components/Input/index.jsx` and `/client/app/components/Input/InputSwitch.jsx` work @ericlee1996? :)

**Comment by dhuang612** [comment]
created a PR #1584

**Comment by dhuang612** [comment]
Hi again,

I see one refactor left open
/client/app/components/Input/index.jsx
Could I take this one on too?

**Comment by julianguyen** [comment]
Go ahead @dhuang612! Thanks again :)

**Comment by dhuang612** [comment]
created PR #1587

**Comment by idrisakmal** [comment]
Hi there @julianguyen  Anymore available issues to solve? i'm happy to help

**Comment by someotherkyle** [comment]
@idrisakmal here you go! I've been busy and don't want to hold up progress

**Comment by aisayo** [comment]
Hi! Beginner here and was wondering if there is anything left to work on with this issue?

**Comment by dhuang612** [comment]
join us on slack if you have questions!

**Comment by julianguyen** [comment]
Hey @dhuang612 would be interested in finishing up `/client/app/components/Form/DynamicForm.jsx` and `/client/app/components/Form/index.jsx`?

**Comment by dhuang612** [comment]
@julianguyen Yes I can work on those!

**Comment by julianguyen** [comment]
Thanks so much @dhuang612 🎉 !!!

**Comment by dhuang612** [comment]
created PR #1609
