### ISSUE TITLE
Fix flakey toggle_locale_spec.rb test

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#1548]
# Description 

```
Failure/Error: expect(find(check_for_element, wait: 10)).to condition

Capybara::ElementNotFound:
  Unable to find css ".pageTitle"
./spec/support/page_transition_support.rb:15:in `change_page'
./spec/features/toggle_locale_spec.rb:33:in `block (4 levels) in <top (required)>'
```

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by guilhermekbral** [comment]
Good afternon @julianguyen. I was taking a look at this, and the spec is green here. Ran it against `master` branch.

Is there a specific branch in which the spec is broken? Is it fixed already?

**Comment by julianguyen** [comment]
Good question @guilhermekbral! One example is `44331`! It's not fixed yet!

Please [join](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack) our contributor community so you can assign yourself to issues!

**Comment by guilhermekbral** [comment]
Nice! Just sent the email! I'll take a look with that seed! Thanks for the info!

**Comment by tiffanyisapr0** [comment]
This appears to be fixed! @julianguyen can you confirm that? :)

**Comment by julianguyen** [comment]
@tiffanyisapr0 I don't think it's fixed! I had to re-build some PRs that were failing cause of it this week.  It's flaky so sometimes it passes.

**Comment by guilhermekbral** [comment]
I'm still working on this flaky spec. It's trickier than I expected!

**Comment by sbpipb** [comment]
True, I can attest that this one is indeed still happening

**Comment by leeacto** [comment]
I couldn't make the test "flakey" (intermittently failing), but I did see if consistently fail. An error was raised because it couldn't find the translation key. This key is not used anymore and was replaced with a hardcoded `Linebreak`.

Removing the translation attempt let the page load successfully and pass the test.

**Comment by julianguyen** [comment]
I think this error is still happening @leeacto :( It existed before we introduce the Chinese translations you fixed up the bug in :/

**Comment by leeacto** [comment]
Oh bummer. Thanks I'll look some more.

**Comment by julianguyen** [comment]
Example: https://app.circleci.com/jobs/github/ifmeorg/ifme/10363
