### ISSUE TITLE
Add "load more" button to Resources list

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#1556]
# Description 

Instead of infinite scroll (which is not the most accessible of experiences), let's add support for the "load more" button that currently exists on various pages (Moments, Categories, Moods, Strategies, and Stories feed) to the [Resources page](https://www.if-me.org/resources).

This button should appear as you scroll down the page and more content exists to load.

![Capture](https://user-images.githubusercontent.com/3010728/65365333-68878000-dbcd-11e9-861a-80c6d32d595d.gif)

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by KrDimitrov** [comment]
I'd be glad to help with that!

**Comment by neon98** [comment]
Hey @KrDimitrov, I've started working on this issue. You can help me If you wish to! 😄

**Comment by KrDimitrov** [comment]
No worries!

**Comment by Rajani169** [comment]
Hey!! can i contribute to resolve this issue??

**Comment by neon98** [comment]
hey @Rajani169 I've raised a PR for this issue. You can help me solve build errors 😄
