### ISSUE TITLE
Show password option

### ISSUE THREAD

**Issue by meanmachin3** [ifmeorg/ifme#1559]
# Description 
Add an option to show password. Not only this would avoid rewriting whole password in case of a single typo but also give an option to user see the password he is pasting.

# Screenshots
Possibly add something like an eye( 👁) to the password field.
<img width="385" alt="Screen Shot 2019-09-25 at 11 35 27 PM" src="https://user-images.githubusercontent.com/7353585/65709282-71110800-e05e-11e9-99eb-e26d0e7056df.png">

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by ashwanijha04** [comment]
Hey can you please assign this to me?

**Comment by ashwanijha04** [comment]
Also, I would need some help since this would be my first contribution. I have already read the contribution guidelines and run it in my local machine. Can you please tell me where in the client folder will I find this design component?

**Comment by meanmachin3** [comment]
@ashwanijha04 I am little caught with my midterms, I'd suggest [Joining slack](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack) and posting doubt there :D

**Comment by Rajani169** [comment]
Hey!! Can you still assign this issue to me?

**Comment by meanmachin3** [comment]
@ashwanijha04 Let me know if you are working on it. @Rajani169  could pick it up in case you aren't working

**Comment by ashwanijha04** [comment]
Please feel free to work on it @Rajani169.
Let me know if you'd like any help.

**Comment by SonuToor** [comment]
@ashwanijha04 hey are you still working on it? I could do this if you'd like.

**Comment by skenypatel** [comment]
Hi, can I take this up if this is not done yet?

**Comment by ThakurKarthik** [comment]
@ashwanijha04 if you are busy or currently not working on this issue,please unassign for the issue so other's can pick it up. 👍

**Comment by briceyokoyama** [comment]
I'll take a shot at this.

**Comment by skenypatel** [comment]
Hi, I'm giving it a shot.

**Comment by skenypatel** [comment]
Hi, I need some help around the project? Which file(s) needs to be changed for this, I can't seem to find component that needs to be modified?

**Comment by GayathriVenkatesh** [comment]
Hi @julianguyen ,
Is somebody working on this issue? I would like to take it up.
Thanks.

**Comment by julianguyen** [comment]
Feel free to assign yourself to it @GayathriVenkatesh!
