### ISSUE TITLE
Moments should have a date and time

### ISSUE THREAD

**Issue by alcoelho** [ifmeorg/ifme#1564]
# Description

Currently, you cant add a date and time to a moment. I think it would be best if date and time were required fields, so you can see a timeline of events and understand mood changes and other things.

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by janessatran** [comment]
Hi, can I work on this issue? :)

**Comment by julianguyen** [comment]
Thanks for filing an issue with us! So by default, Moments and Strategies keep track of the date of post creation and post update. These are fields you need to fill out.

Example:

STORY CARD:

<img width="616" alt="image" src="https://user-images.githubusercontent.com/3010728/66079380-ca72ae80-e518-11e9-9945-ec4583cdc3e3.png">

MOMENT PAGE:

<img width="739" alt="image" src="https://user-images.githubusercontent.com/3010728/66079489-073ea580-e519-11e9-8388-2eecf05ccba9.png">

The Medications page keeps track of date explicitly:

<img width="1297" alt="image" src="https://user-images.githubusercontent.com/3010728/66079440-e7a77d00-e518-11e9-924d-4e3e1c4b0003.png">

Going back to Moments and Strategies, I'm curious what you think the value of specifying exact dates can do. If it's a way to be able to reference an existing post, I think we could do that by adding the ability to tag posts.

Let me know what you think!

**Comment by alcoelho** [comment]
I was thinking of using moments as a mood tracker. For example, I got frustrated with something at 12 pm but I didnt think it was relevant, so I didnt care about it. At night, I feel sad. If I could tracks moments of the day, I could see a link between the bad event at 12 pm and my bad mood. 
That was just a silly example, but it's a good thing to be able to track events like that so you can understand yourself better

**Comment by julianguyen** [comment]
Thanks for clarifying!

In the current workflow you would do:

1. Post a new moment about an experience
 - Create a mood called "Sad" and tag it to this post
 - Create a category called "The Experience" and tag it to this post
2. Post another new moment about the same experience
  - Tag the existing mood called "Sad" to this post
  - Tag the existing category called "The Experience" and tag it to this post

You could then go to the page the category to view all related posts e.g. `https://www.if-me.org/categories/the-experience-[unique-hash-here]`

Something we can do to improve this is to make the tag components link to the Category and Mood pages:

<img width="726" alt="image" src="https://user-images.githubusercontent.com/3010728/66083149-94392d00-e520-11e9-851f-c820be2c0dee.png">

They used to before the redesign, but I think we forgot to add back that feature.

I think we could do better with UX to encourage people to organize their Moments and Strategies into appropriate Moods and Categories.

**Comment by PorterK** [comment]
Happy to attempt the reimplementation of that feature (linking back to the category) @julianguyen. Should I make a new issue? Seems like the conversation kind of drifted from the original request.

**Comment by julianguyen** [comment]
Hey @PorterK, so sorry for the late response! Yeah feel free to make a new issue and delete this one!
