### ISSUE TITLE
Portuguese (Brazil) translation needs revision

### ISSUE THREAD

**Issue by alcoelho** [ifmeorg/ifme#1565]
# Description

I was reading the pt-br translation and it has a few typos and untranslated lines. I can help with that since it is my native language.

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to join our [organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

**Comment by camillevilla** [comment]
Great, @alcoelho! Please take a look at our guide for translators here: 
https://github.com/ifmeorg/ifme/wiki/Translations

Are you a member of our Slack yet?

**Comment by alcoelho** [comment]
Hey! I sent an email to join.ifme@gmail.com, but I'm not on the project Slack yet.

**Comment by maugravena** [comment]
Hello @camillevilla 

I made some suggestions in your translation
