### ISSUE TITLE
Clicking a tag on the resources list should add it to the current filter

### ISSUE THREAD

**Issue by LMulvey** [ifmeorg/ifme#1581]
# Description

Clicking on a tag below a resource item should add it to the current filter. This would make it easier to find similar items based on keywords as you're browsing through the list.

[Resources Page](https://www.if-me.org/resources)

**Comment by janessatran** [comment]
Hi @LMulvey, I'm interested in working on this feature! May I be assigned to this issue?

**Comment by andrewjprice** [comment]
@LMulvey mind if I work on this?

**Comment by LMulvey** [comment]
@andrewjprice Not at all! I've gone ahead and assigned you :)
