### ISSUE TITLE
Care Plan Feature

### ISSUE THREAD

**Issue by LMulvey** [ifmeorg/ifme#1582]
**Help Me** Button 🤗

Users should have a Help Me Button visible on the screen at all times. When the user clicks the button, it takes them to a personalized resource/help page.

**Help Me** Page 📝

The Help Me Page would have a collection of bookmarked Moments and Strategies. Additionally, it would have extra fields such as contact information (name, email, phone number) as well as a safety plan (text area).

[Sub-task for #187]

**Comment by ankurprasad711** [comment]
Hi @LMulvey ,
I would love to take up this issue.
Can you provide me with details of how the Help me page should look.
Thanks

**Comment by ArushiSinghal** [comment]
Hi @julianguyen and @LMulvey  
I and @enazuma11 wants to work on this issue.

**Comment by LMulvey** [comment]
That's absolutely fine with me, I'll assign it to them :) 

I haven't had free time in months now :( My personal Mac died _**three separate times**_ and then I was bombarded with contract work so I've never made it around to it :(

**Comment by julianguyen** [comment]
I'm working on this feature through my latest "Learning Web Development through if-me.org" workshop I'm doing with the Code Cooperative.
