### ISSUE TITLE
Connect the blogs page to homepage.

### ISSUE THREAD

**Issue by adad20** [ifmeorg/ifme#1588]
The nav bar in the homepage is not in the blogs page which makes difficult for the user to interact with whole site.

**Comment by skenypatel** [comment]
Hi, can I work on this issue?

**Comment by julianguyen** [comment]
I don't quite understand what this issue is about. The blog page is on Medium which is separate form our site. We used to have a page that fetched all the blog posts onto our site but we found it better to link directly to Medium for the full experience.

**Comment by adad20** [comment]
Sorry it,s my mistake I haven't checked the URL of the blogs page.
