### ISSUE TITLE
CI tests don't detect missing tags

### ISSUE THREAD

**Issue by andy5995** [ifmeorg/ifme#1619]
If a new resource is added with a tag that's hasn't also been added to config/locale... , the CI tests don't catch it. After it's merged, it appears like this:

![image](https://user-images.githubusercontent.com/16764864/71381581-b1b6e980-2599-11ea-88ce-ed2c9abb8906.png)

**Comment by julianguyen** [comment]
Gonna close this issue cause there's no efficient way to automatically test for missing translations on rendered pages. Our automated tests only test for missing translations across the translation files.

The messaging that shows up should be enough. We should also be manually testing pages if we are making visual changes to it.

**Comment by andy5995** [comment]
> We should also be manually testing pages if we are making visual changes to it.

Ah, good point, thank you. I'll be sure to do that next time. I promise you, @julianguyen  ;)
