### ISSUE TITLE
Concrn (US) may need to be removed from the resource page

### ISSUE THREAD

**Issue by andy5995** [ifmeorg/ifme#1624]
Concrn (US) may need to be removed from the resources page. A message on [their site](https://www.concrn.org/) states:

>Concrn is no longer in operations as of December 2019. If you'd like to make a report in the San Francisco Bay Area about a person in crisis on the streets, call 911 and ask for the Crisis Intervention Team.

**Comment by sunguru98** [comment]
I think this has been closed right?

**Comment by andy5995** [comment]
Yah, completed by @isa3bel in #1625 :)
