### ISSUE TITLE
implement multi-column table for contributor list

### ISSUE THREAD

**Issue by andy5995** [ifmeorg/ifme#1632]
Anyone want to make a multi-column table for the [contributor list](https://www.if-me.org/contribute)?

![image](https://user-images.githubusercontent.com/16764864/72293149-82375200-3618-11ea-9c1d-2f4bb874303c.png)

So.. no commas.. the names divided up by 4 columns, 1 name per line, is what I was initially thinking. But UX details will probably need more input from @julianguyen

**Comment by mapra99** [comment]
@andy5995, @julianguyen I'd like to do it. I showed my interest in this issue and  #1611, but I'm waiting for an answer in #1611 because that one seems to be already assigned to someone else. So I would like to work on this one, or on both :smile: hehe

**Comment by andy5995** [comment]
@mapra99 You could start on this one anytime, thanks for the offer.

**Comment by GayathriVenkatesh** [comment]
Hi @mapra99, are you still working on this issue? If not, I would like to take it up :)
