### ISSUE TITLE
Automatically generate Refill date for new medication

### ISSUE THREAD

**Issue by GayathriVenkatesh** [ifmeorg/ifme#1638]
# Description
While adding a new medication, the refill field is mandatory. 
However, given the total no. of tablets and dosage per day, the refill date can be generated in the backend (rather than having the user calculate it). This date can be the default value for the field, and can be manually changed if necessary.

# Screenshots

![Screenshot from 2020-01-19 20-38-09](https://user-images.githubusercontent.com/32172764/72683428-4eb76480-3afd-11ea-94da-7f0e3d567226.png)

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by GayathriVenkatesh** [comment]
@julianguyen Do share your thoughts on this :)

**Comment by julianguyen** [comment]
Hey, @GayathriVenkatesh this is a really good observation and I think we should implement this feature! :D Thank you for playing around with it and suggesting this!

**Comment by GayathriVenkatesh** [comment]
Hi @julianguyen, could you tell me the command I need to use to access the input values of Total and Dosage? I tried a couple of things but it doesn't seem to work.
Here, when I try to print medication_field('total'), this is what gets displayed:

![Screenshot from 2020-01-21 09-38-25](https://user-images.githubusercontent.com/32172764/72774871-3e54d600-3c32-11ea-847f-a0d0ce1be308.png)

The value field seems to be nil even after entering a value.
What am I doing wrong?
