### ISSUE TITLE
Remove code duplication introduced by QuickCreate refactor

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#1640]
# Description

Let's remove the duplication introduced to refactor the QuickCreate widget component in order to remove cyclical import dependencies. Huge thanks to @dhuang612 for taking this on!

Code Climate now raises it as a [warning](https://codeclimate.com/github/ifmeorg/ifme/issues?category=duplication&engine_name%5B%5D=structure&engine_name%5B%5D=duplication) to fix!

@dhuang612, feel free to assign this to yourself if you have the bandwidth!

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by dhuang612** [comment]
Yeah I can take a look

**Comment by dhuang612** [comment]
never mind, assigned myself.
