### ISSUE TITLE
On resources page, focus changes incorrectly when tag is selected

### ISSUE THREAD

**Issue by andy5995** [ifmeorg/ifme#1645]
I wasn't sure how to title this ticket...

When I go to [the resources page](https://www.if-me.org/resources), and have this view:

![image](https://user-images.githubusercontent.com/16764864/72849814-35cdc100-3c6d-11ea-8627-8298fc60eb38.png)

and I click the "hotlines" tag on the left, it works, but the focus/page immediately changes to this:

![image](https://user-images.githubusercontent.com/16764864/72849928-880ee200-3c6d-11ea-8358-a3f1b6c60605.png)

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by Camboridesbikes** [comment]
I see what's happening. It seems the viewport essentially stays where it is on the page, but the page shrinks as the resources are un-populated. 

I will fork and set up the environment tonight!

**Comment by alekpentchev** [comment]
I’ve checked it yesterday and it works exactly as @Camboridesbikes wrote. 
But the question is - how it should then behave if the list of resources changes?

**Comment by julianguyen** [comment]
Thanks for bringing this up everyone!

@alekpentchev @Camboridesbikes I think we'll want to scroll up to the top of the page everytime we select a tag!

**Comment by alekpentchev** [comment]
@julianguyen good idea! :)
Because I don't see any activity since @Camboridesbikes activity I can start working on it. It should be a relatively easy task.

**Comment by Camboridesbikes** [comment]
I can take myself off. I see where and how to fix the source code, I've just been having trouble setting up the environment.

**Comment by Camboridesbikes** [comment]
I can take myself off. I see where and how to fix the source code, I've just been having trouble setting up the environment.

**Comment by julianguyen** [comment]
@Camboridesbikes Oh no! What kind of setup problems are you having? You can also post in our #setup channel on Slack.
