### ISSUE TITLE
Clean up DB queries in Profiles#index

### ISSUE THREAD

**Issue by leeacto** [ifmeorg/ifme#1660]
# Description

Looking at the Profile page, I can see many extra database hits that fetch from DB cache or get the same information. 
Ex. [Here](https://github.com/ifmeorg/ifme/blob/master/app/views/profile/index.html.erb#L15) The profile user is re-fetched from the database to check the location field. We already have the the user object, so re-fetching is unnecessary. 

The goal is to clean up the `/profile?uid=<uid>` endpoint to minimize repeat queries. This improvement will keep the database running smoothly as user counts increase (and for code quality).

# Screenshots
Same query twice below. Neither are needed.
![image](https://user-images.githubusercontent.com/2866605/74689515-101ad580-51a1-11ea-92d4-92701ee0d83c.png)

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by julianguyen** [comment]
This is a great optimization!  Thanks so much for taking this on 🎉🤩
