### ISSUE TITLE
[Feature suggestion] Creating web push notifications of credible content based on the categories, mood, and strategies a user select.

### ISSUE THREAD

**Issue by Megha-Pathak** [ifmeorg/ifme#1706]
### Description - **A feature we can include is having web push notifications.** 
These notifications will be related to customized encouraging messages for the user with links to credible information, podcast, videos, articles that can help them in dealing with their current categories, mood, and strategies. 
These web push notifications will enhance the User experience as well as making the whole website more contextual and useful.

**Comment by julianguyen** [comment]
I'm gonna close this because this is the project the selected RGSoC 2020 will be working on. Creating issues will be part of that work.

As discussed on Slack, please include what you've written here in your application :)
