### ISSUE TITLE
Add "New Moment" button to signed in home page

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#1710]
# Description

Let's make it easier for users to add their Moments!

Let's add the "New Moment" button on `/moments` to the home page. We only want this button to appear when the user is signed in and has stories in their feed.

# Screenshots

![image](https://user-images.githubusercontent.com/3010728/77859057-13e84180-71bc-11ea-933e-ed1484e9d29a.png)

When user is signed in and has items in their stories feed:

![image](https://user-images.githubusercontent.com/3010728/77859074-34b09700-71bc-11ea-8d3f-01256e32447b.png)

We do not want the button to appear when the user doesn't have items in their stories feed:

![image](https://user-images.githubusercontent.com/3010728/77859172-ab4d9480-71bc-11ea-868e-36a0ba09ccf4.png)

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by Manasa2850** [comment]
@julianguyen I would like to work on this :)
