### ISSUE TITLE
Fix warning in DynamicForm.spec.jsx

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#1724]
# Description

When running our automated React tests we get a warning from `DynamicForm.spec.jsx` related to unique keys. 

# Reproduction Steps

Run `yarn test -- client/app/components/Form/__tests__/DynamicForm.spec.jsx`. The tests pass but we get the following warnings:

```    console.error node_modules/react-dom/cjs/react-dom.development.js:88
      Warning: Encountered two children with the same key, `name-id`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
          in div (created by DynamicForm)
          in DynamicForm (created by _default)
          in _default (created by WrapperComponent)
          in WrapperComponent
```

We're not getting this issue in the implementation so there must a bug with the mocks.

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by renjithabby** [comment]
Hello there, I'd like to help with this. i have also sent an email to join.ifme@gmail.com. thanks.

**Comment by julianguyen** [comment]
@renjithabby Thanks! It would be great to get this fixed :) Once you accept the team invite, you can assign yourself to this issue!
