### ISSUE TITLE
Add ability to remove Facebook authentication for account

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#1733]
# Description

@Manasa2850 recently worked on setting up Facebook authentication. We'll also want to add the ability to remove FB authentication in user settings (`/users/edit`). 

We currently do this with Google authentication by allowing the user to set a password in order to eliminate their Google authentication.

![image](https://user-images.githubusercontent.com/3010728/80832221-1239e100-8ba1-11ea-89ff-8c3a1cd4c64f.png)

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by bianca93** [comment]
Hey @julianguyen going through unassigned issues to find something I can help with after being away for a while. Would like to take this one on 😄 if that's ok with you

**Comment by julianguyen** [comment]
That would be great @bianca93! Feel free to reach out on Slack in #dev if you have questions! @bmwachajr should also be able to help too :)
