### ISSUE TITLE
Toggle Resource Recommendations

### ISSUE THREAD

**Issue by S-Warmenhoven** [ifmeorg/ifme#1737]
# Description

Toggle the display of Resource Recommendations in Moment Post

# Screenshots
![toggle_resource_recommendations](https://user-images.githubusercontent.com/57923250/81218356-ecdb1780-8f92-11ea-850e-14719f0c3552.gif)

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by bmwachajr** [comment]
Hi @S-Warmenhoven can we close this issue?

**Comment by S-Warmenhoven** [comment]
Hi @bmwachajr 
Yes, we can.  Sorry if I was required to do that and didn't.  I'm still new to contributing to Open Source projects, and this was my first created issue, so I wasn't sure what the policy was and if I can just close issues for the project myself.  Should I just go ahead and do that or should I leave it for you to close?  Also, my team worked on issue #1713 and it is finished and merged.  However, that issue was created by Julia.  Do we leave it for her (as the creator of the issue) to close it, or do we as the assignees close it after it's completed?  Thank you in advance for your guidance.

**Comment by julianguyen** [comment]
No worries! Feel free to close it, if you made the issue you feel like the requirements have been completed.
