### ISSUE TITLE
Cursor doesn't change when hovering over medication details

### ISSUE THREAD

**Issue by enoralecuyer** [ifmeorg/ifme#1748]
# Description

The cursor doesn't change when hovering over the details of a new medication. To make this feature more accessible, I suggest to change the cursor to a type **pointer**.

On the New Medication page, the change is needed for:
- Strength/mg
- Total/tablets
- Dosage/tablets
- mm/dd/yyyy
- two check boxes Refill reminder email and Daily reminder email

# Screenshots
![Inked2020-05-12 15_31_15-Greenshot_LI](https://user-images.githubusercontent.com/48727972/81752500-688f0580-9466-11ea-9fe6-60c57a3a0995.jpg)

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by julianguyen** [comment]
I mentioned this already in Slack but I think we actually don't want the cursor type to be a pointer here.

The pointer cursor type should only be used on elements that are links. This custom select component is not a link. The native `<Select>` element actually uses the default cursor.

**Comment by enoralecuyer** [comment]
In terms of accessibility and usability, it is not easy to recognize that it's a multiple-choice selection. I actually missed it the first time I went to this page. 

If the decision is made to not change the pointer, it would be good to come up with another solution to make this feature more accessible and help the user not miss this important step.

What about having all the choices visible in a single line (either horizontal or vertical) and the user can select the option of their liking?

**Comment by julianguyen** [comment]
@enoralecuyer That's a great observation! I think improving the UX here is a good call. We would either:

1) Add a label to the existing component to indicate that there are multiple options
2) Change the component so that it's checkboxes

What do you think?

**Comment by GuillermoCoding** [comment]
Just joining in the conversation and following up on @julianguyen. For the second option you suggested, do you think radio buttons would be more appropriate instead of check boxes ? since the use should choose between`mg` OR `ml` and not have the ability to select multiple options ?

**Comment by enoralecuyer** [comment]
@GuillermoCoding I love your idea of using radio buttons! They are clear, easy to use and restrict to one option only. That sounds perfect to me!

**Comment by GuillermoCoding** [comment]
@julianguyen any more thoughts on this?  I can start tackling this feature

**Comment by julianguyen** [comment]
@GuillermoCoding Sorry for the late response! Yeah let's convert this to use radio buttons instead of a select menu :) Thanks for chatting about this!

**Comment by GuillermoCoding** [comment]
no problem, Sounds good!
