### ISSUE TITLE
Translated into Korean

### ISSUE THREAD

**Issue by dddw1234** [ifmeorg/ifme#1753]
We are conducting an open-source SW class team project of Kwangwoon University, a university in Korea. We want to contribute by translating this program into Korean.

**Comment by julianguyen** [comment]
This is sooo awesome! Thank you so much @dddw1234 for doing this!! :D Let me know if you need anything on Slack!

**Comment by dddw1234** [comment]
[[translated into korean] README.txt](https://github.com/ifmeorg/ifme/files/4666896/translated.into.korean.README.txt)

**Comment by dddw1234** [comment]
Next time, we are going to translate 4 yml files in the locale folder at once. Should I request to create a Korean translation branch separately? Or can I request a pull request directly to the master branch?

And I want to ask if there are any other files that need to be translated.

**Comment by dddw1234** [comment]
Next time, we are going to translate 4 yml files in the locale folder at once. 
We are an undergraduate students who are still learning GitHub. 
So it may be a rather silly question, Should I request to create a Korean translation branch separately? Or can I request a pull request directly to the master branch?

And I want to ask if there are any other files that need to be translated.

**Comment by julianguyen** [comment]
You're correct, we'll want to translate all the files in the `config/locales` folder. Yeah so you'll want to create a new branch for the Korean changes and then make a pull request into the master branch.

Let me know if you need any help, especially with Git. This is our [Git Workflow](https://github.com/ifmeorg/ifme/wiki/Git-Workflow).

**Comment by dddw1234** [comment]
The translation is complete, but applying the file seems to be outside the scope of what we can do.
I want to test it as written on the wiki, but I'm embarrassed because I haven't had any experience with Ruby (I'm trying to learn).

In addition, the result of the conversion from the "pretty ymal" page is strange for no reason.(
'(Single quote)Is often missing )

Can you suggest what we need to do in this translation work?

**Comment by dddw1234** [comment]
@julianguyen Can I get some advice?

**Comment by julianguyen** [comment]
@dddw1234 Sorry for the delayed response! Taking a look now, it's been a very busy few weeks for me.

**Comment by julianguyen** [comment]
@dddw1234 I can help with apply the files to the codebase. Where can I find your changes?

**Comment by julianguyen** [comment]
@dddw1234 Another thing I wanted to mention was that we feature our translators on our blog! This is an [example](https://medium.com/ifme/announcing-if-me-org-in-hindi-709baeabb9ad) of an interview we did with the person who did the Hindi translations.

I would love to feature you, but only if you would like to be featured! Let me know 💜

**Comment by dddw1234** [comment]
@julianguyen  Could you tell me how to conduct the interview?We will discuss this with our team and answer it as soon as possible.

And even though I did a couple of final reviews, I can see more awkwardness and mistakes after the translation is applied more than I thought. I'm sorry about this, and I'll take care of it quickly as well.

**Comment by julianguyen** [comment]
Yes @dddw1234 :D

In a Google Doc (which you give edit access to `join.ifme@gmail.com`), can you answer the following questions in both English and Korean? Feel free to also include pictures in the doc if you want to share any :)

1. Tell us about yourselves
2. How is mental health perceived and treated in Korean communities?
3. Why did you want to participate in translating if-me.org?
4. Were there any interesting challenges you came across while translating?

**Comment by dddw1234** [comment]
I sent you an email about some request and questions through my personal account.
