### ISSUE TITLE
Migrate from Enzyme to React Testing Library

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#1758]
# Description

We should migrate to React Testing Library as it's officially recommended by React and it's a lot more usable than Enzyme.

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by alekpentchev** [comment]
I can work on this! Does want to rewrite every component’s test file to use React Testing Library? Or do we want to focus on a specific set of components?

**Comment by julianguyen** [comment]
Yeah we'll want to get rid of Enzyme and replace it with React Testing Library. The good thing is that we don't need to rely on element classes or IDs to identify them in our tests. We can identify elements by their appropriate aria labels, text content, etc.

Let me know if you have any questions or need help along the way. I use this library in my day job and have some experience with it :P

**Comment by alekpentchev** [comment]
Thanks Julia for your support! I will probably need some onboarding in the topic of this library because I'm quite new to it. But I'm eager to work on it :)

Btw If someone else would like to jump in and to this in parallel, I'm absolutely ok with it!
