### ISSUE TITLE
Migrate client/app/widgets/QuickCreate/_tests_/QuickCreate.spec.jsx to use React Testing Library instead of Enzyme

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#1802]
# Description

We are deprecating Enzyme as our JS testing utility in favour of [React Testing Library](https://testing-library.com/docs/react-testing-library/intro). Thanks @alekpentchev for setting it up :)

Recommended Reading
* [Cheatsheet](https://testing-library.com/docs/react-testing-library/cheatsheet)
* [Common mistakes](https://kentcdodds.com/blog/common-mistakes-with-react-testing-library)

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by bennpham** [comment]
Curious if anyone is taking this one yet? I'm new to React although I've done a bit of VueJS on a Laravel project (but hadn't had adequate testing on that one).

**Comment by julianguyen** [comment]
@bennpham Nope feel free to take it! :)

**Comment by bennpham** [comment]
Hadn't had any progress on this since I'm unfamiliar with Enzyme and RTL testing at the moment. Hadn't been in the right head space to try to figure it out with the fires going around giving me some headaches. I'm going to unassign myself and grab one of the Rspec ones again.

**Comment by julianguyen** [comment]
No problem and stay safe @bennpham!

**Comment by MicahRamirez** [comment]
I'm working on the QuickCreate hooks migration. Based on that work the existing tests have broken and so I'm going to go ahead and rewrite these tests with RTL!

**Comment by julianguyen** [comment]
Awesome thanks Micah :)
