### ISSUE TITLE
Refactor spec/controllers/allies_controller_spec.rb to spec/request/allyship_spec.rb

### ISSUE THREAD

**Issue by bennpham** [ifmeorg/ifme#1819]
# Description

Controller Specs had been obsolete since Rails 5. It is best practice to create request spec instead of controller spec as recommended by the Rspec team.

Recommended Reading:

- [Stackoverflow Discussion in regards to Controller Specs vs Request Specs](https://stackoverflow.com/questions/40851705/controller-specs-vs-request-specs)
- [Medium article discussing request and controller specs](https://medium.com/just-tech/rspec-controller-or-request-specs-d93ef563ef11)

Resources on Request Spec formatting:

- [RelishApp](https://relishapp.com/rspec/rspec-rails/v/4-0/docs/request-specs/request-spec)

Original Issue: https://github.com/ifmeorg/ifme/issues/1815

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by esparta** [comment]
May I take this task?

**Comment by andrewhchang** [comment]
Hi @esparta! I'm actually in the middle of this - if you're keen, there's definitely a lot of other controller specs that need to be refactored :)

**Comment by esparta** [comment]
ohh my bad, I didn't see the assigment. Will move to other one.
