### ISSUE TITLE
Google Sign Up is not working

### ISSUE THREAD

**Issue by erickaorf** [ifmeorg/ifme#1844]
![Screenshot 2020-09-21 185622](https://user-images.githubusercontent.com/58405291/93832800-6de23500-fc3c-11ea-9677-d193e1b67163.png)
<!--[
 I tried signing up via google, it did not work. I got the above screen.

**Comment by julianguyen** [comment]
Thanks for reporting this! Is this happening on the live if-me.org site for you or in your development environment?

**Comment by adedayomoshood** [comment]
This happens on the live if-me.org site. Googling the issue, the App needs to be reverified to use Google oauth login

**Comment by julianguyen** [comment]
Oh no, I'll look into this. I wasn't able to reproduce this.

**Comment by julianguyen** [comment]
I think there was an outage with some Google Cloud services this week.

I got this message in the dashboard:

> We are currently experiencing service disruptions and are unable to provide quota information at this time.

**Comment by julianguyen** [comment]
Thanks, everyone for verifying! I just submitted the process to verify our app. In the past, we didn't have to do this but it looks like we have to now.  I'll keep everyone posted!

**Comment by julianguyen** [comment]
We've been verified! Could folks test whether they can sign in/up now? :)

**Comment by andrew-schutt** [comment]
Still had the same error for me 😅 Perhaps it takes a little while to take effect?

**Comment by julianguyen** [comment]
I hope so lol. I double-checked the [Google OAuth scopes](https://github.com/ifmeorg/ifme/blob/695f7af517c74bbab982453f75ebe8b0790c0747/config/initializers/devise.rb#L318) we set and they seem correct.

They're appearing in GCP.
![image](https://user-images.githubusercontent.com/3010728/95031238-bef51e80-0669-11eb-9ae4-f433f86dd954.png)

**Comment by julianguyen** [comment]
Turns out I need to go through another verification level to be able to use sensitive scopes (for the Calendar API). So I had to submit a video demonstrating how it's used in our app and do a short write-up on why we can't narrow down our scopes.

Our app was only verified on a "brand level" lol.

Here's [more info on verification levels and scopes for Google OAuth2](https://developers.google.com/identity/protocols/oauth2/scopes) if anyone is interested 💀 🤣

**Comment by andrew-schutt** [comment]
Come on Google!

![flipceral](https://user-images.githubusercontent.com/413224/95114964-590ca380-070a-11eb-980f-4e82c44bba80.gif)

**Comment by julianguyen** [comment]
@erickaorf @andrearosr @adedayomoshood What browsers were you using when encountering this error?

**Comment by adedayomoshood** [comment]
> @erickaorf @andrearosr @adedayomoshood What browsers were you using when encountering this error?

I used Chrome

**Comment by julianguyen** [comment]
Thanks! We've been approved! Please let me know if you're able to sign in/up or not!

**Comment by udayanshevade** [comment]
Worked for me! At first I got a 400 for a missing `client_id`, but then after a couple of minutes I refreshed and tried again and it went through (Mac, Chrome v85).

For reference:

![Screen Shot 2020-10-10 at 12 16 04 PM](https://user-images.githubusercontent.com/11330558/95663291-eed17580-0af2-11eb-97e3-2c2a07532b67.png)

**Comment by andrew-schutt** [comment]
Worked for me as well! Nice work!
