### ISSUE TITLE
Devise deprecation warnings 

### ISSUE THREAD

**Issue by andrew-schutt** [ifmeorg/ifme#1851]
# Description

When running the test suite locally I noticed some Devise deprecation warnings (see screenshot)

Based on the message it seems we need to change the way we are calling and rendering the devise error messaging from `<%= devise_error_messages! %>` to `<%= render "devise/shared/error_messages", resource: resource %>`

Here is a relevant link on the Devise repo https://github.com/heartcombo/devise/issues/5257

# Reproduction Steps

To reproduce this have the app setup locally and run the full test suite with `rspec`. You will notice the messages output in a couple of spots while running the tests. These messages are also being output when running the [tests in CI](https://app.circleci.com/pipelines/github/ifmeorg/ifme/875/workflows/7b729fb0-8485-4e7b-821d-3fb5155b3ca0/jobs/12879/parallel-runs/0/steps/0-117) as well 

# Screenshots

![Screen Shot 2020-10-01 at 6 54 02 AM](https://user-images.githubusercontent.com/413224/94806024-ef5f6300-03b2-11eb-8712-7deaaebb538f.png)

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by toshitapandey** [comment]
@julianguyen @andrew-schutt - picking up this issue.
