### ISSUE TITLE
Rename master branch as main

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#1853]
# Description

We can now rename master branches in GitHub to anything else, so we should do that! Let's rename it to main.

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by andrew-schutt** [comment]
Good call!
