### ISSUE TITLE
Requesting Indonesia Translation

### ISSUE THREAD

**Issue by thexdev** [ifmeorg/ifme#1855]
# Description

Hi, this is awesome application!

I'm planning to make the Indonesian translation for this project and i just start from the README.md :)

# Reproduction Steps

# Screenshots

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by julianguyen** [comment]
This would be amazing, thank you so much! :D

**Comment by flitzmare** [comment]
I'd love to work on this!

*I've sent the email to join the organization anyway :)

**Comment by julianguyen** [comment]
It would be great if everyone @thexdev, @flitzmare, and @rahmatullah5 could work on the translations together! We have [documentation](https://github.com/ifmeorg/ifme/wiki/Translations) on this translations process!

**Comment by rahmatullah5** [comment]
@julianguyen there is no README-ID.md file, can I create it in the next PR?

**Comment by julianguyen** [comment]
Yeah go ahead and do that!

**Comment by rahmatullah5** [comment]
1 more thing @julianguyen, should I add a link to Indonesian README.md in the other translated README.md files.
For the example is main README.md file include links to the other translated README files
![image](https://user-images.githubusercontent.com/16495060/94947459-e03df980-0507-11eb-8453-5bc8da76beb6.png)

**Comment by julianguyen** [comment]
Yes you'll want to do that @rahmatullah5!

**Comment by davidsantoso77** [comment]
i'm done sir . i'm added indonesian language to your readme-id.md , thanks sir

**Comment by rahmatullah5** [comment]
> i'm done sir . i'm added indonesian language to your readme-id.md , thanks sir

could you use my branch instead https://github.com/ifmeorg/ifme/pull/1865 ? And don't too much use google translate because it is kinda weird.

what do you think @julianguyen @davidsantoso77 ?

**Comment by thexdev** [comment]
Hi, it think you don't read my issue. I just make the readme for Indonesia translation and im done with it :)

**Comment by rahmatullah5** [comment]
I see @thexdev, Have you create the PR? if you haven't created it, you can PR to my branch instead then we can merge it to the main branch to avoid any conflicts.

**Comment by rahmatullah5** [comment]
Hi @julianguyen I'll continue to work on the translation for [devise](https://github.com/ifmeorg/ifme/blob/main/config/locales/devise.en.yml)

@thexdev @davidsantoso77 You can translate other files too that refer to this [documentation](https://github.com/ifmeorg/ifme/wiki/Translations), but to avoid any conflict again, please communicate with us which file that you want to translate in Indonesian in this forum.

Happy Coding

**Comment by prajogoatmaja** [comment]
Hello. I somewhat saw this issue. Do you still need any help for Indonesian translation? I can try helping with the i18n as well if you would like.

**Comment by julianguyen** [comment]
@prajogoatmaja We would love your help!!!

**Comment by prajogoatmaja** [comment]
I will continue this issue from [this PR](https://github.com/ifmeorg/ifme/pull/2010). Will update regularly

**Comment by julianguyen** [comment]
Re-opening this issue because we still need translations for `id.yml` and to implement the ability to toggle to Bahasa Indonesia in the UI (see [docs](https://github.com/ifmeorg/ifme/wiki/Translations)).

**Comment by rizkaluthfiani** [comment]
@julianguyen I have made my code, but I can't push the code or make the PR. What should I do?

**Comment by julianguyen** [comment]
@rizkaluthfiani What error messages are you encountering? Also, I can add you to our GitHub org!

**Comment by rizkaluthfiani** [comment]
My error is I can't push my local branch to this repository after searching the solution, I found that I need to be a part of your github organization to push my branch. Then what should I do in order to be a part of your organization?
