### ISSUE TITLE
Fix act warnings in Jest tests

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#1857]
# Description

If you run `cd client && yarn test`, you'll notice in the output the following warnings in various tests:

```
When testing, code that causes React state updates should be wrapped into act(...):

      act(() => {
        /* fire events that update state */
      });
      /* assert on the output */
```

Even though this doesn't block our tests from running and passing, we should fix our tests so that we use `act()` correctly.

Here's recommended [reading](https://kentcdodds.com/blog/fix-the-not-wrapped-in-act-warning) on how to address this issue with React Testing Library.

This warning is appearing in:
* `client/app/widgets/Comments/__tests__/Comments.spec.jsx`
* `client/app/components/BaseContainer/__tests__/index.spec.jsx`

`client/app/widgets/Resources/__tests__/Resources.spec.jsx` is an example, among some others, where `act()` is used correctly :)

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by sprakash57** [comment]
Is this available to pick up?

**Comment by meanmachin3** [comment]
@sprakash57 I am working on it
