### ISSUE TITLE
Care Plan Feature Foundations

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#187]
# Description

Recently thought about having a panic button feature, where you can add Strategies and certain words of encouragement (user and their allies). When a user is going through a rough time, they can press this button and view all these nice things.

Also, include links and numbers to hotlines and crisis services.

EDIT (10/2018): Recently gave this feature more thought I think the panic button should be a collection of bookmarked comments, Moments, and Strategies. From a DB standpoint, we would add a column `bookmark: boolean`.

We could have special user input fields for contact information (name/email/phone number) and safety plan (a user can write out their plan of reaching out for direct support, could just be a regular textarea field).

+1 to the idea folks have shared below about determining the correct crisis hotline number based on location.

Maybe calling it the panic button might be triggering or insensitive. So it's also worth exploring a better name e.g. rescue button, help me button, etc.

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by starbelly** [comment]
@julianguyen Where would the panic button be located in the UI? I assume it would be most beneficial if it was always within reach. That aside, let me make sure I understand the specification for this feature:

* User hits panic button
* Panic button sends request to sever
* Server looks up friends and allies, 
* Server fires off emails to friends and allies with link to the /strategies 

 Is this correct?

**Comment by julianguyen** [comment]
Good question @starbelly! I agree, it should be easy to use - so I'm thinking in the main navigation.

I was imagining it as, user hits the panic button and sees:
* A list of bookmarked Strategies is displayed e.g. user bookmarks a breathing exercise strategy
* A list of bookmarked Allies they can reach out to (I like the idea of that firing off emails to those allies, but what would be in that email? Would it be something like, "You should check up on [name here]?"
* A list of links to numbers to hotlines and crisis services

**Comment by starbelly** [comment]
@julianguyen Yeah, I'll take this on.

**Comment by julianguyen** [comment]
@starbelly Sounds good! If you wanna chat more, please message me on our Slack :)

**Comment by bshap93** [comment]
I'm pretty busy this week but I'd like to have this done before next.

**Comment by julianguyen** [comment]
Not a problem @bshap93! Thanks for keeping us posted :)

**Comment by shelleyvadams** [comment]
To really be useful, hotline and crisis/emergency numbers to display need to be determined based on the user's location.

The links below were also included in my first comment on #458, but this is probably a more appropriate place for them.

## Sources for hotline/crisis/emergency numbers
* International Association for Suicide Prevention's [directory of crisis centers/hotlines][iasp].
* International Telecommunication Union's database of emergency numbers for member countries: [ITU-T E.129 National-only numbers linked with emergency services and other services of social value][e129].

## Localization strategies
### User profile location field
Advantages:
* User-verified.

Disadvantages:
* Not available for users who haven't signed in.
* Location field may be blank.
* Despite auto-complete/suggest, free text (?) may not contain a recognizable location.

### IP geolocation
Example FOSS library: [ip2location-ruby][geoip] (MIT license).

Advantages:
* Doesn't require user login; allows displaying panic button to unregistered users.
* Not dependent on parsing user input.
* Country-based IP range assignment makes it very accurate at the national level.

Disadvantages:
* Potentially incorrect location for users accessing the site through VPN, Tor-based privacy browsers, etc.
* Privacy concerns?

[e129]: http://www.itu.int/net/itu-t/inrdb/e129_important_numbers.aspx
[geoip]: https://github.com/ip2location/ip2location-ruby
[iasp]: https://www.iasp.info/resources/Crisis_Centres/

**Comment by aleciavogel** [comment]
Is the panic button still in development? I've been doing a lot of work with gems like [Geocoder](https://github.com/alexreisner/geocoder) lately and would love to contribute to this feature

**Comment by starbelly** [comment]
@aleciavogel I'd say go for it 👍  I got lost in a giant code base for a year, so 😄

**Comment by aleciavogel** [comment]
It happens to the best of us 😉

Sounds great! I'll see what I can come up with and keep you posted.

**Comment by alexiamcdonald** [comment]
I actually saw a panic button on a website recently terrafem.se I think it was. You should have a look to get some ideas.

**Comment by aleciavogel** [comment]
@alexiamcdonald Hey Alexia, the domain you mentioned above is for sale

**Comment by pederjohnsen** [comment]
http://www.terrafem.org/ probably then? :)

**Comment by alexiamcdonald** [comment]
@aleciavogel yeah sorry it's the one @pederjohnsen mentioned. I was just trying to remember the name and didn't check it. whoop sorry.

**Comment by LMulvey** [comment]
Hey @julianguyen - I can take this one on over the next few weeks.
Before I get rolling, wanted to nail down a story here:

**Rescue Button**
1) User should have a _**resuce button**_ visible on the screen at all times (nav?)
2) When the user clicks the rescue button, it takes them to a rescue page
3) Rescue page has a collection of bookmarked Moments and Strategies
4) Rescue page additionally has a few special fields: contact information (name, email, phone number) as well as a safety plan (text area)

**Bookmarking**
1) Users can bookmark Moments and Strategies. This is identified by a column in the database for these items labeled `bookmark: boolean`
2) Users can click on a bookmark button on the Moment or Strategy they want to bookmark and it will add it to the bookmark list. Clicking the button again will remove the Moment or Strategy from the bookmark list (should it prompt for confirmation from the user?)

**Safety Plan & Rescue Information**
I feel like for this implementation to be effective, once we add these fields, all currents should be prompted/forced to fill out a minimal amount of information for this screen and given instructions as to what it is and how to use it. Just so nobody reaches for the rescue button when they need it and it's not being used to the full potential.

**Summary / Questions**
1) Should we implement a Rescue Button Information screen and force users to add this information?
2) Should removing a bookmark prompt the user? Or should it be a click-to-toggle bookmarks on and off?

Let me know your thoughts before I get going! Thanks :)

**Comment by julianguyen** [comment]
Ooh that would be awesome @LMulvey, thanks so much! :D

**Rescue Button**
1) User should have a _**rescue button**_ visible on the screen at all times (nav?)
  - This sounds good! I think we think about what term we want to use. I think Rescue and Panic Button could be potentially stigmatizing. Maybe we could just call it, "Help Me"
2) When the user clicks the rescue button, it takes them to a rescue page
  - Yes!
3) Rescue page has a collection of bookmarked Moments and Strategies
  - Yes!
4) Rescue page additionally has a few special fields: contact information (name, email, phone number) as well as a safety plan (text area)
  - Yes!

**Bookmarking**
1) Users can bookmark Moments and Strategies. This is identified by a column in the database for these items labeled `bookmark: boolean`
  - Yes!
2) Users can click on a bookmark button on the Moment or Strategy they want to bookmark and it will add it to the bookmark list. Clicking the button again will remove the Moment or Strategy from the bookmark list (should it prompt for confirmation from the user?)
  - Yes! I don't think we need a confirmation prompt since they can easily re-bookmark it.

**Safety Plan & Rescue Information**
I feel like for this implementation to be effective, once we add these fields, all currents should be prompted/forced to fill out a minimal amount of information for this screen and given instructions as to what it is and how to use it. Just so nobody reaches for the rescue button when they need it and it's not being used to the full potential.

- Sounds good. I think we should have a link to: https://www.if-me.org/resources?filter[]=suicide%20prevention as basic info. We already do this on the Footer page and on the Resources page.

**Summary / Questions**
1) Should we implement a Rescue Button Information screen and force users to add this information?
  - Oooh, we could! I think it could be a gentle reminder rather than mandatory.
2) Should removing a bookmark prompt the user? Or should it be a click-to-toggle bookmarks on and off? 
  - I think it should just be a toggle since it should be simple to re-toggle.

This is great! Feel free to make separate issues any sub-tasks you may need!

**Comment by drowvoloper** [comment]
Thank you for this great idea, I like it a lot! 

> Maybe calling it the panic button might be triggering or insensitive. So it's also worth exploring a better name e.g. rescue button, help me button, etc.

What about "calm button"?

**Comment by LMulvey** [comment]
I love that idea, @drowvoloper!
@julianguyen so you know this hasn't been abandoned–my Macbook started smoking last week and has had three visits to the repair shop now for separate issues... hopefully will have a working Macbook this week and can continue on these issues!

**Comment by julianguyen** [comment]
Thanks for the update and it's all good! That sucks to hear that and I hope things get fixed soon :)
