### ISSUE TITLE
Use stylelint for SCSS linting

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#1872]
# Description

We should add SCSS linting like we have linting for Ruby on Rails and React JS. Let's use [stylelint](https://github.com/stylelint/stylelint). 

We'll want to add a `"lint:stylelint"` script to our `client/package.json` and add it to our general `"lint"` script. 

Also note that we use SCSS in both Ruby on Rails and React, so the lint script will need to account for that.

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by andrewhchang** [comment]
I'll also begin working removing all stylelint warnings that it has generated in another branch :)
