### ISSUE TITLE
Setup Recaptcha After A Certain Amount of Failed Login Attempts

### ISSUE THREAD

**Issue by bennpham** [ifmeorg/ifme#1921]
# Description

Spunned off after merging https://github.com/ifmeorg/ifme/pull/1895. It'd probably be a nice feature to implement recaptcha after a certain amount of failed logins. I think 3 failed attempts would be a good time to ask user to correctly answer Recaptcha to make sure they're not a bot. 

## Additional Notes

Gem for Recaptcha: https://github.com/ambethia/recaptcha

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by seannemann21** [comment]
Hello, I started working on a PR, and I was wondering if you could provide any feedback as to whether this is what you had in mind? https://github.com/ifmeorg/ifme/pull/1936. I still need to add tests and clean up a few things, but the logic is mostly there. It was based off of https://github.com/heartcombo/devise/wiki/How-To:-Use-Recaptcha-with-Devise, but I had to add logic for the 3 failed attempts. One concern I have is if a user fails to login 3 times, prompting the recaptcha, then leaves before successfully logging in. The next time they come to the site, they won't see the recaptcha until they attempt to login again and fail (due to the request not having a recaptcha). Now, the form will reload with the recaptcha, but it's kinda an awkward experience since they'll have to reenter their username/password. This is probably a pretty rare scenario, though, so I'm not sure how much it matters

**Comment by bennpham** [comment]
> The next time they come to the site, they won't see the recaptcha until they attempt to login again since failed attempts are tied to emails, and we won't know their email until they attempt to login.

I like the cookie idea for this.

> Now, the form will reload with the recaptcha once they try to login with that email once, but it's kinda an awkward experience since they'll have to reenter their email/password

I'd prefer not to make the user experience discomforting for this matter especially since we eventually have 20 fails to lock. I think that'd be good enough. I'd rather not punish the user unfairly from a gimmick as long as other procedures are in place. Sometimes misspelling happens a lot multiple times, especially if you have a very long sentence for a password.

----

Random tangent unrelated to comments above even though I wrote this issue: I really dislike Google captcha lately on some sites I've seen. The whole click these images until all "buses", "bikes", etc no longer appears and follow up by another captcha with "click all street lights" gets pretty annoying. Sometimes I get them all correct and it still says "Invalid try again" which I'd waste a whole minute or 2 on :( . There were some old recaptcha from the past that were simpler and less of a nuisance.

**Comment by seannemann21** [comment]
Ok, yeah, I'll add the cookie! That should resolve the issue with the user not having a recaptcha if they leave and come back, so they shouldn't have to go through that awkward process of submitting the form only to realize they need to resubmit with the captcha. Unless, of course, they clear the cookie. Regarding the 20 fails to lock bit, do you think an attempted login without the recaptcha should count as a failed attempt?

Yeah, I know what you mean about recaptcha being a bit annoying. Recaptcha V2 seems to just show up with the "I am not a robot" checkbox oftentimes at least, which isn't too bad. It seems V3 works without the need for users to fill anything out and rates the user's likelihood to be a bot with a score by tracking activity, but this is has its flaws as well.

**Comment by bennpham** [comment]
I don't think the attempt without the captcha should count as fail login. I'd let Devise handle however it handles that if it does already. Not sure what happens if a user or bot refuse to submit the correct recaptcha (maybe their while loop just won't end? 🤷 )

> Recaptcha V2 seems to just show up with the "I am not a robot" checkbox oftentimes at least, which isn't too bad

I probably like V2 best. Is that new one I complained about V3? I'm not the biggest fan of it personally.

**Comment by seannemann21** [comment]
Yeah, Devise's suggestion for implementing a recaptcha is to prepend the `create` endpoint in the `SessionsController` with the recaptcha check and redirect back to the login form if the check fails, so a failed recaptcha check never actually gets processed by devised (so no failed attempt unless we explicitly increment it). As a result, yeah, basically the loop won't end, so they. can just keep trying to submit login requests.

V2 has both the "I'm not a robot" and "Click all of the pictures will hills or mountains" variants (I'm not sure what actually determines which one you see, while testing, I got both). Users don't actually see V3. You have to insert some code to signal to google that a user interaction has occurred, and then they'll return a score that shows how likely it is that the user is a bot based on all of their interactions with your site.

**Comment by seannemann21** [comment]
Sorry, I've been a bit busy over the last two weeks. I'm still working on this (finishing up tests). I'm hoping to have a PR ready to review sometime this week.
