### ISSUE TITLE
 Request for joining the organizatio

### ISSUE THREAD

**Issue by akshitagupta15june** [ifmeorg/ifme#1938]
# Description

# Reproduction Steps

# Screenshots

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by andrew-schutt** [comment]
Hello @akshitagupta15june! 

Be sure and checkout the guide for joining the community (https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack). Download Slack (https://slack.com/downloads) and then follow the steps for Joining Our Slack. If you want to start contributing you can check out the [wiki](https://github.com/ifmeorg/ifme/wiki) for more information to [contribute](https://github.com/ifmeorg/ifme/blob/main/CONTRIBUTING.md) and get begin as a [developer](https://github.com/ifmeorg/ifme/wiki/Developers) for the project.

**Comment by andrew-schutt** [comment]
Going to close this as well as the information for joining is in the wiki 👍
