### ISSUE TITLE
Add missing unit tests to the components

### ISSUE THREAD

**Issue by xunxdd** [ifmeorg/ifme#1967]
# Description
Most of the react components have great tests written. However not all of them, for example, ifme/client/app/components/Header/HeaderProfile. 

# Reproduction Steps
Check the repo, client/app/components.

# Screenshots

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by xunxdd** [comment]
i'd like to add some of the tests as my way to get familiar with the code base

**Comment by mikachan** [comment]
Hi @clchinara, are you still working on this or are there any specific unit tests you're already working on? I was going to help out but noticed you'd already assigned yourself to this.

**Comment by clchinara** [comment]
@mikachan Not yet, you can take this issue.

**Comment by xunxdd** [comment]
> @mikachan Not yet, you can take this issue.

Sorry, I intended to work on it. Then got super distracted, side tracked. 

I did start working on it a bit. And the branch is at https://github.com/ifmeorg/ifme/tree/add-components-tests. Though the team has done such a great job. Most of the components have great tests. And the two little tests I added are pretty trivial, I do not even know if they are really needed

**Comment by mikachan** [comment]
Ah I didn't see your branch, these are the two components I began with as well because like you say, there aren't that many missing. I've also started looking at the HeaderProfile component as you mentioned in the original issue.

Thanks for replying. I'll update as I make progress.
