### ISSUE TITLE
Add the ability to remove formatting when copying and pasting in editor

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#1987]
# Description

If you copy and paste text from another page/screen into our editor, the formatting of the text is copied like so:

![image](https://user-images.githubusercontent.com/3010728/120220239-4abb4c80-c1f1-11eb-99fe-3b4a14dd2e09.png)

By default, it would be preferrable to automatically remove HTML formatting.

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by nad0m** [comment]
@julianguyen How should we handle the case where the user copy and pastes a formatted text from the current editor?

**Comment by julianguyen** [comment]
@nad0m Good question! I think it should be copied and pasted as plaintext!
