### ISSUE TITLE
Error 500 when creating a moment without description

### ISSUE THREAD

**Issue by franpb14** [ifmeorg/ifme#2007]
# Description

When you try to create a moment without filling in the "write about it" part, the server returns a 500 error. The form should not be submitted with this field empty.

# Reproduction Steps

1. click on "new moment".
2. fill the title, "Name".
3. click on submit and you will see the error.

I have tested it on ubuntu 20.04 on both chrome version 92.0.4515.159 and Firefox 91.0.

# Screenshots

https://user-images.githubusercontent.com/70280187/129942515-fdb9d540-b185-47f5-a102-811f99d06aad.mp4

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by js-sapphire** [comment]
Can I take a dig at this ?

**Comment by julianguyen** [comment]
@js-sapphire Go ahead and please to assign yourself to this issue!
