### ISSUE TITLE
Fix Node warnings in React Jest tests

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#2033]
# Description

Fix the following Node warnings in React Jest tests:

```
(node:48372) UnhandledPromiseRejectionWarning: Error: Network Error
(node:48372) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
(node:48372) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

# Reproduction Steps

```
cd client
yarn test
```

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by AudreyKj** [comment]
I would love to take this in :)

**Comment by Tera15** [comment]
Hello! I'm curious if this issue still being actively worked on? If not, I would love to pick it up :)

**Comment by julianguyen** [comment]
@Tera15 Nope, feel free to assign yourself! Thanks :)

**Comment by Tera15** [comment]
🙏  Thank you :)

**Comment by timagixe** [comment]
@Tera15 @julianguyen hello. I was not able to reach someone at join.ifme@gmail.com. Please take a look on my fix for this issue https://github.com/ifmeorg/ifme/pull/2082 whenever you have a chance.

**Comment by julianguyen** [comment]
@timagixe Sorry, we didn't get your email. Could you try sending it again? I can add you to our GitHub org though.

Will take a look this week, thanks!

**Comment by timagixe** [comment]
@julianguyen, thanks, accepted. I have sent an email message once more time.
