### ISSUE TITLE
Contact | Security Issue

### ISSUE THREAD

**Issue by wsmi22** [ifmeorg/ifme#2052]
Dear ifme contributors,

I've tried to contact several of you through email, but got no response.
Please get back to me at: vulnerability@whitesourcesoftware.com.
It's about security issues found in your project.

Thanks,
Miriam

**Comment by julianguyen** [comment]
Thanks, @wsmi22! Took a look at the report, and I can put together GitHub issues for the concerns your team raised!

**Comment by wsmi22** [comment]
Hey @julianguyen 
Thanks for all the fixes!
Do you have any updates about the session expiration vulnerability?
Please let us know ASAP 🙏 
Thanks again and we appreciate your kind and fast collaboration! 😊

**Comment by julianguyen** [comment]
@wsmi22 I haven't fixed the session expiration vulnerability yet because I've been busy, but I will try to take a look later this week!
