### ISSUE TITLE
Insufficient session expiration

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#2058]
# Description

This is part of an audit that WhiteSouce did on our site (see: https://github.com/ifmeorg/ifme/issues/2052).

Our site does not properly invalidate a user’s session even after the user initiates logout. It makes it possible for an attacker to reuse the admin cookies either via local/network access or by other hypothetical attacks.

Vulnerable code: https://github.com/ifmeorg/ifme/blob/v.7.31.2/app/helpers/header_helper.rb#L53

# Reproduction Steps

In dev: Access the application by going to http://localhost:3000/users/sign_in and login with admin cred. Use [edithiscookie](https://www.editthiscookie.com/) extension and copy the cookie values and then logout of the application. Now, go to [editthiscookie](https://www.editthiscookie.com/) and import the copied cookies and refresh the page. After we refresh the page, we see that we are again logged in to the account.

1. Access the application by going to http://localhost:3000/users/sign_in and login with admin cred.

```
Email: admin@example.com
Password: passworD@99
```

![image](https://user-images.githubusercontent.com/3010728/145912654-409fbed4-8432-4d5f-9f6e-c98d95cbe064.png)

2.  Use edithiscookie extension and copy the cookie values and then logout of the application.

![image](https://user-images.githubusercontent.com/3010728/145912740-0c01dd39-49b5-4912-8536-2adfa477b6cb.png)

3. Now, go to editthiscookie and import the copied cookies and refresh the page.

![image](https://user-images.githubusercontent.com/3010728/145912795-fc6e7354-c75d-4a96-83a8-ad47eca8829c.png)

4. After we refresh the page, we see that we are again logged in to the account.

![image](https://user-images.githubusercontent.com/3010728/145912831-99ad1d27-424d-42e8-9db1-3a74914762e7.png)

Expected result: we should not be able to log back in with the copied cookies. They should be expired. We'll want to update configuration in the gem we use for authentication called Devise. This [post](https://stackoverflow.com/questions/12880623/how-to-set-rails-session-cookie-expiration-time-to-session) may be helpful!

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by wsmi22** [comment]
Hey @julianguyen and @tsara27 🙂 
Do we have an estimation for the fix release (when approximately it will be out)?
Thanks in advance for your collaboration 🙏

**Comment by julianguyen** [comment]
I'll just take this on to get this fix out the door. Our contributors have different schedules and busy schedules/full-time jobs/etc., including myself @wsmi22.
