### ISSUE TITLE
Update to latest Ruby (v3) and Rails (v7)

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#2116]
# Description

* Update to latest Ruby (v3) and Rails (v7)
* Refer to the [official guide](https://guides.rubyonrails.org/v7.0/upgrading_ruby_on_rails.html)

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by toshitapandey** [comment]
@julianguyen - I have assigned this issue to myself. Is it okay if I work on it?

**Comment by julianguyen** [comment]
Yess that would be great, thank you, @toshitapandey! Hope you're doing well 💜

**Comment by uzorjchibuzor** [comment]
@toshitapandey are you still working on this? I can pick it up instead if not.

**Comment by uzorjchibuzor** [comment]
@julianguyen I have started work on this pending when I get a reply from @toshitapandey , after the first step to upgrading, I have a question. Is there a reason cloudinary fails locally?

**Comment by julianguyen** [comment]
Hey @uzorjchibuzor I can just assign you to this since it's been a couple of weeks since it was originally assigned. 

Cloudinary fails locally if you don't set up the API keys for it, and that's okay. But you should generate one to test the full experience.

**Comment by uzorjchibuzor** [comment]
I will do that.
