### ISSUE TITLE
Add more tags to Popular Tags section on the Resources page

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#2117]
# Description

Add links to the "Addiction" and "Sexual Assault Survivors" tags to the Popular Tags section on the [Resources page](https://www.if-me.org/resources) 💜 

# Screenshots

![image](https://user-images.githubusercontent.com/3010728/193165612-6e560c81-8348-4c1a-a962-cd31a636f604.png)

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by julianguyen** [comment]
Closing this cause it looks like already have this in the popular tags section, sorry about that @skukhniy!

**Comment by jatinmark** [comment]
I am interested in this issue can you assign it to me.

**Comment by julianguyen** [comment]
@skukhniy Is working on this issue!

**Comment by jatinmark** [comment]
ok

**Comment by Omkar0803** [comment]
As it is taking much of a delay, can you assign this issue to me?

**Comment by julianguyen** [comment]
@jatinmark @Omkar0803 Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

**Comment by julianguyen** [comment]
@santhos-13 We want to add the "Addiction" and "Sexual Assault Survivors" tags.
