### ISSUE TITLE
Add visual indicator to a Story component for Moments that Secret Share is enabled

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#2144]
# Description

Secret share is the ability to generate a private link to a user's Moments post that can be accessed by non-users of the app. 

Users can generate a link by viewing their Moments post and hitting the "Secret Share" button.

Let's make it easier for users to know which posts they generated a secret share link for by adding a visual indicator to the [Story component](http://design.if-me.org/?path=/docs/components-story--all-props).

In this example screenshot, we are hovering over the Edit button.

![image](https://user-images.githubusercontent.com/3010728/194098100-d6af2e69-e694-4a0e-9dd9-1103d109b10b.png)

## Acceptance Criteria
* Add the following [icon](https://fontawesome.com/icons/key?s=solid&f=classic) to the end of the icons list with the tooltip label, "Secret Share link created" (Please use Google Translate to update the translations, it will be reviewed for accuracy later.)
* This icon will not be a link and just serve as a visual indicator.

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by januslinhc** [comment]
Hello, can I work on this issue?
