### ISSUE TITLE
Mobile Menu not Working

### ISSUE THREAD

**Issue by AlfieTitu78** [ifmeorg/ifme#2160]
Hi my site is https://iimexpo.co.uk/ 
Menu links are opening in desktop but links are not opening on mobile. When  I click to open pages from mobile navigation men u it is returning back to homepage. 

![Capture2](https://user-images.githubusercontent.com/48330336/194723069-60e0e144-fba2-4374-9dea-cf4d274c933a.JPG)
![Capture1](https://user-images.githubusercontent.com/48330336/194723067-1e13fff0-28bb-48fb-a682-10935d2c2beb.JPG)

I would appreciate if anyone can help me in this. 

Thank you
Rahman

**Comment by IM-TECHNO** [comment]
I can surely help you out !

**Comment by AlfieTitu78** [comment]
@IM-TECHNO  
Please help me to fix this issue
Thank you

**Comment by julianguyen** [comment]
Our app's link is if-me.org and not the one you posted. I'm going to close this issue.
