### ISSUE TITLE
can I translate it into Arabic?

### ISSUE THREAD

**Issue by 0xGhada** [ifmeorg/ifme#2177]
# Description

# Reproduction Steps

# Screenshots

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by julianguyen** [comment]
This would be awesome @PureGeekNerd! Here's info on our [Translations](https://github.com/ifmeorg/ifme/wiki/Translations) process!

Thank you for opening this issue with us! If you haven't already, please follow these [next steps](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack) to officially join our contributor community.
