### ISSUE TITLE
Confirmation/Error message after posting comment

### ISSUE THREAD

**Issue by scroniser** [ifmeorg/ifme#219]
Once someone hits the comment button, it would be great to have either a confirmation message that the message was posted or error message that the post failed for some reason (empty comment box, no internet connection, etc).

**Comment by nagmak** [comment]
Hi! is anyone still working on this?

**Comment by julianguyen** [comment]
@sophiexhe hey have you been working on this?

**Comment by julianguyen** [comment]
Hey @nagmak, feel free to pick this up!

**Comment by nagmak** [comment]
@julianguyen Sounds good, I'll keep you posted via Slack on any issues/updates soon.

**Comment by WWLChen** [comment]
Clarification: 
1. Write comment and click Comment button
2. Comment is posted
a. If posted with no error, comment appears
b. If posted with error, error message should appear
3. Error message content: "It appears your comment did not post." Along with error code, http status code or ?
List of http status codes: https://en.wikipedia.org/wiki/List_of_HTTP_status_codes,

**Comment by greggb** [comment]
I'll tackle this one for y'all. Is this the only place someone would be adding a comment? `ifme/app/assets/javascripts/add_comment.js `

**Comment by aSquare14** [comment]
Can I work on this @julianguyen  ?

**Comment by TangyOhio** [comment]
Hi, is this issue still open?

**Comment by julianguyen** [comment]
@TangyOhio It is, and you're welcome to pick it up. Here's more [info](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack) on how to get started with contributing.
