### ISSUE TITLE
[BUG]: Does not receive any confirmation email to complete the account registration.

### ISSUE THREAD

**Issue by Shawn-3604** [ifmeorg/ifme#2236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

**Register**
When the user register an account for the system, the system will send a confirmation email to validate the account.

However, the email had not receive and when the user register again, the email is said to be already taken.

![11](https://github.com/ifmeorg/ifme/assets/77117897/ba2e8281-2aae-4488-a3e2-9e5b2a55cda1)

### Expected Behavior

System will send a confirmation email to the user to complete the registration. 

### Steps To Reproduce

1. The actor will fill in the forms with necessary information.
2. The actor clicks on the ‘Sign Up’ button.

### Environment

```markdown
- OS: macOS Ventura 13.4
- Node: 18.6.0
- npm: 9.5.1
```

### Criteria for Completion

When the user clicks on the "Sign In" button, the system should send an email confirmation to the user to complete the registration

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the if-me community

**Comment by julianguyen** [comment]
Thanks for reporting this! Taking a look!

**Comment by julianguyen** [comment]
@Shawn-3604 The issue has been resolved! There was an update that had to be made in our Sendgrid dashboard! Can you re-test and let me know if you're still facing issues? Thanks!
