### ISSUE TITLE
[BUG]: Does not receive any email confirmation instruction to change the password.

### ISSUE THREAD

**Issue by Shawn-3604** [ifmeorg/ifme#2237]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

**Forgot Password**

When the user want to change their password for their existing account for the system, the system will send a email confirmation instruction.

However, the email had not receive and an error page is pop up.
![14](https://github.com/ifmeorg/ifme/assets/77117897/bbb88239-4660-4a54-a667-09c5f6d644ce)

### Expected Behavior

System will send a confirmation email to the actor to complete the process.

### Steps To Reproduce

1. The actor clicks on the ‘Forgot your password?’ button.
2. The system will redirect the users to a new page to fill in their email.
3. The actor will fill in the email.
4. The actor clicks on the ‘Send me reset password instructions’ button.

### Environment

```markdown
- OS: macOS Ventura 13.4
- Node: 18.6.0
- npm: 9.5.1
```

### Criteria for Completion

When the user clicks on the "Send me reset password instructions" button, the system should send an email confirmation instruction to the user to complete the process

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the if-me community

**Comment by julianguyen** [comment]
Thanks for reporting this! Taking a look!

**Comment by julianguyen** [comment]
@Shawn-3604 The issue has been resolved! There was an update that had to be made in our Sendgrid dashboard! Can you re-test and let me know if you're still facing issues? Thanks!
