### ISSUE TITLE
To change the footer on some specific page's

### ISSUE THREAD

**Issue by ManashAnand** [ifmeorg/ifme#2242]
### Is there an existing request for this feature?

- [X] I have searched the existing issues

### Is there a pain point in the app driving this feature request?

After serving this webapp for some time ,
I found a url https://medium.com/ifme  where the footer is not designed properly
![footer](https://github.com/ifmeorg/ifme/assets/91553087/98a2005f-be68-4bd5-9f9d-cf15fb47c290)

Making the UI/UX a bit harsh  to propogate to different pages.

### Desired Behavior

I would like to redesign the existing footer and add a good design to it

### Criteria for Completion

- [x] Will add a new footer with existing links for a seamless user experience

### Anything else?

Please assign me this issue,
So that I can start working on it.

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the if-me community

**Comment by julianguyen** [comment]
Thanks for creating an issue with us! So it looks like that footer is automatically rendered by Medium, and we have no control over it.
