### ISSUE TITLE
Making the navigation menu bar fixed

### ISSUE THREAD

**Issue by Amenawon** [ifmeorg/ifme#2271]
### Is there an existing request for this feature?

- [X] I have searched the existing issues

### Is there a pain point in the app driving this feature request?

It might be a good UX to have the menu navigation fixed as the user scrolls

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the if-me community

**Comment by shivansh84ya** [comment]
I would like to work on this issue. Could you please assign it to me?

Thanks!

**Comment by julianguyen** [comment]
Closing this as this is a duplicate of https://github.com/ifmeorg/ifme/issues/2155
