### ISSUE TITLE
Replace unmaintained `react-render-html` library

### ISSUE THREAD

**Issue by camillof** [ifmeorg/ifme#2326]
# Description

`react-render-html` is currently used in a few places, mainly in https://github.com/ifmeorg/ifme/blob/main/client/app/utils/index.js#L39.
But the library [is no longer maintained](https://github.com/hatashiro/react-render-html?tab=readme-ov-file#deprecation), and the last release [was 7 years ago](https://www.npmjs.com/package/react-render-html).

The owner itself recommends a few options: 

- [htmr](https://github.com/pveyes/htmr)
- [html-to-react](https://github.com/aknuds1/html-to-react)
- [react-html-parser](https://github.com/wrakky/react-html-parser)
- [html-react-parser](https://github.com/remarkablemark/html-react-parser)

But the only one with apparent recent activity (other than dependabot PRs) is [html-react-parser](https://github.com/remarkablemark/html-react-parser)

### References
- https://github.com/hatashiro/react-render-html?tab=readme-ov-file#deprecation

**Comment by camillof** [comment]
@julianguyen if you are ok with this, and the proposed replacement library, I'd like to work on it.

**Comment by julianguyen** [comment]
Yes of course, thanks @camillof !
