### ISSUE TITLE
Add more tests to meetings_controller_spec.rb

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#357]
Add more tests for this controller!

**Comment by cpanato** [comment]
I have some questions about this controller, how/who can help me?

**Comment by julianguyen** [comment]
@cpanato Can you email us at join.ifme@gmail.com so we can add you to our Slack? I would answer most of the questions :P

**Comment by rhiroyuki** [comment]
Hi I would like to help solve this issue... is the email above still valid? What is the process to submit a pull request in this project?

**Comment by andy5995** [comment]
Hi! Yes, that email is still valid.
