### ISSUE TITLE
JS tests for missing specs

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#363]
![wsc_opensourcehours](https://cloud.githubusercontent.com/assets/3010728/24170861/8127b1ba-0e3f-11e7-8b0b-dcfe8661b3b9.png)

- [ ] add_comment.js => AddCommentSpec.js
- [ ] application.js => ApplicationSpec.js
- [x] <s>character_count.js => CharacterCountSpec.js (@jnamster)</s>
- [ ] delete_comment.js => DeleteCommentSpec.js 
- [ ] form_processing.js => FormProcessingSpec.js
- [ ] medications.js => MedicationsSpec.js
- [x] <s>get_location.js => GetLocationSpec.js (@julianguyen)</s>
- [ ] mobile_tooltip.js => MobileTooltipSpec.js 

Make sure to use jasmine-jquery fixtures and matchers
Assign yourself to this issue and put your name beside the spec file you are working on.

**Comment by estermer** [comment]
how are we coming on this?

does this still need some help?

**Comment by julianguyen** [comment]
@estermer Edit the original comment I made and add your name to the spec(s) you will be working on! Also assign yourself to the issue :D

**Comment by nma** [comment]
suggestions on one thats easy to pick up?

**Comment by julianguyen** [comment]
@nma Medications and MobileTooltip are fairly easy ones to pick up! :D

**Comment by ThePedroPaulino** [comment]
Stiil trying to figure this out. Any tips ?

**Comment by jnamster** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(6) JS tests for missing specs](https://trello.com/c/09pzjz8z/29-6-js-tests-for-missing-specs)

**Comment by andy5995** [comment]
Time to close this? The log shows an associated PR was merged, but is this ticket complete?
