### ISSUE TITLE
Refactor code for setting up premade content

### ISSUE THREAD

**Issue by brunoocasali** [ifmeorg/ifme#410]
Hello everyone!

I facing with the #356 issue, and there and inside (moods, categories) controllers, I've found similar code, that just generate premade content. 

In my opinion, this premade content can be created in other place, like after a user to be generated for example... And the user can remove if it wants...

What do you think to refactor these peaces ?

**Comment by julianguyen** [comment]
Thanks for calling this out @brunoocasali! When you talk about refactor, do you mean reusing the logic to generate this premade content? Can you clarify? :)
