### ISSUE TITLE
Add ability to add premade content for Categories, Moods, and Strategies in Moments and Strategies editors

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#416]
Currently, the user can only add premade content for Categories, Moods, and Strategies on their respective index pages.

Example:
![image](https://cloud.githubusercontent.com/assets/3010728/21753468/f6aa7ba0-d5a2-11e6-93ef-893c82de0911.png)

We want to add premade content from the Moments and Strategies editor:
![image](https://cloud.githubusercontent.com/assets/3010728/21753466/dc62ad76-d5a2-11e6-9bc4-4732e9bd121d.png)

Either add this new button in the sidebar or in the modal after clicking "Add [...]"

We only want this button to show up there is no existing content.

### Cases:
Moments
* Categories
* Moods
* Strategies

Strategies
* Categories

**Comment by andela-oesho** [comment]
@julianguyen for clarity the add modal button should only appear if moods/strategies/categories.blank?

**Comment by julianguyen** [comment]
@andela-oesho Yep that is correct (for that user)!
