### ISSUE TITLE
More writing prompts for Moments

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#425]
# Description

We currently use static writing prompts in Moments.
![image](https://cloud.githubusercontent.com/assets/3010728/23581694/d36c5324-00cd-11e7-8014-d87b9c85acfe.png)

We want to add the ability to choose from a dropdown of writing prompts and have that saved in the user's Moment.

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by jnamster** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(4) More writing prompts for moments](https://trello.com/c/2Q6ki0qV/22-4-more-writing-prompts-for-moments)

**Comment by Paarmita** [comment]
@julianguyen can I work on this issue?
