### ISSUE TITLE
Add internationalization support for German

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#457]
The lovely Christine Wilhelmy from Indiegogo has volunteered to do this! The more help the merrier!

**Comment by indicatz** [comment]
I'm a native German speaker with no Ruby skills. Can I help with translating? What could be a good starting point?

**Comment by julianguyen** [comment]
Hey @indicatz, thanks so much for reaching out! We would love for you to contribute, you can email us at join.ifme@gmail.com and we'll add you to our Slack community <3

**Comment by pederjohnsen** [comment]
@julianguyen didn't want to create a new issue for this, just wondering if there are plans to translate to other languages than the ones already with issues created?

**Comment by julianguyen** [comment]
@pederjohnsen There most definitely, I've just been creating issues for languages that are currently being worked on, but in general, if you want to translate, feel free open an issue and assign yourself to. Or if you want to offer a suggestion you can still create an issue and maybe someone will see it and work on it :D Thanks for asking this.

Also! Please email us at join.ifme@gmail.com so we can add you to our Slack! :D

**Comment by alexiamcdonald** [comment]
@indicatz if you want to pair on this together and we could smash it out really quickly.

Are you in Germany because we could sync up a time to work together since I'm based in Stockholm? 😄

**Comment by andy5995** [comment]
I've been studying German off and on for about 3 years. Not fluent, but more than basic knowledge. I'll keep my eye on this ticket.

**Comment by desirottman** [comment]
Hallo! Ich kann Deutsch auch. Let me know how I can help - no Ruby skills but could be handy with some translations!

**Comment by andy5995** [comment]
I've recently realized how poor my German skills are. Unfortunately, I won't be able to help with this.

**Comment by marcelkalveram** [comment]
Hey there, I'm happy to help out with the German translation. I'm native German. If anyone has already made some progress on this, I'm happy to review as well.

**Comment by andy5995** [comment]
@marcelkalveram PR #633 may need some attention.

**Comment by marcelkalveram** [comment]
@andy5995 thanks, I'll take a look.

**Comment by marcelkalveram** [comment]
Had a look and the translation in `devise.de.yml` are all appropriate. I couldn't find `de.yml` in the PR though, which @cwilhelmy seems to have worked on.

I'm happy to take care of the remaining files to get this done.
