### ISSUE TITLE
Terms of Service

### ISSUE THREAD

**Issue by WWLChen** [ifmeorg/ifme#458]
Add a TOS, including emergencies and that the moments are not to be taken as medical advice, this site is about mental health storytelling, sharing personal stories and not being stigmatized. Examples, From: URL and excerpts below.

From: https://www.breakthrough.com/how-it-works/terms
- [ ] USE OF THE SERVICES IS NOT FOR EMERGENCIES. IF YOU THINK YOU HAVE A MEDICAL OR MENTAL HEALTH EMERGENCY, OR IF AT ANY TIME YOU ARE CONCERNED ABOUT YOUR CARE OR TREATMENT, CALL 911 OR GO TO THE NEAREST OPEN CLINIC OR EMERGENCY ROOM.
- [ ] IF YOU ARE CONSIDERING OR CONTEMPLATING SUICIDE OR FEEL THAT YOU ARE A DANGER TO YOURSELF OR TO OTHERS, YOU MUST DISCONTINUE USE OF THE SERVICES IMMEDIATELY, CALL 911, OR NOTIFY APPROPRIATE POLICE OR EMERGENCY MEDICAL PERSONNEL.

From: http://www.kpmhs.com/terms-of-service/

- [ ] The information on this website is provided for informational purposes only and shall not be construed or utilized as medical advice. Accessing or browsing this website and/or providing personal or medical information to KPMHS does not create a physician-patient relationship between you and KPMHS. Nothing contained in the website is intended to create a physician-patient relationship, to replace the services of a licensed, trained physician or health professional or to be a substitute for the medical advice of a physician or trained health professional licensed in your state. You should not rely on anything contained in the website and you should consult a physician licensed in your state in all matters relating to your health.
- [ ] The medical information on this website is provided “as is” without any representations or warranties, express or implied and KPMHS makes no representations or warranties in relation to the medical information on this website. Without limiting the generality of the foregoing, KPMHS does not warrant that (i) the medical information on this website will be constantly available, or available at all, or (ii) the medical information on this website is complete, true, accurate, up-to-date, or not misleading.
- [ ] You must not rely on the information on this website as an alternative to medical advice from your doctor or other professional healthcare provider. If you have any specific questions about any medical matter you should consult your doctor or other professional healthcare provider. If you think you may be suffering from any medical condition you should seek immediate medical attention. You should never delay seeking medical advice, disregard medical advice, or discontinue medical treatment because of information on this website.

**Comment by julianguyen** [comment]
Hey @WWLChen, I'd love to sync on this sometime! Are you still available to work on it? :)

**Comment by WWLChen** [comment]
Yes! Would love to sync up. Another person was interested as well. I think Linda was the name. 

Winnie

**Comment by julianguyen** [comment]
Awesome! Let's chat more on Slack then! :D

**Comment by shelleyvadams** [comment]
Two comments on the instructions to "call 911 or go to the nearest emergency room":

First, the 911 emergency number isn't a worldwide standard; emergency numbers vary by country. The International Telecommunication Union maintains a database, [ITU-T E.129 National-only numbers linked with emergency services and other services of social value][e129].

Localization is an obvious challenge, here are the first two approaches I thought of:
1. User profile location field -- should be accurate if the user is signed-in and the field is non-blank.
2. IP geolocation -- accurate at country-level in the majority of cases (exceptions include use of VPN to circumvent government censorship). IP2Location offers a [FLOSS library][geoip] (MIT license); there are probably others.

Second, perhaps beyond the scope of this issue (like "enhancement++"), could we direct users who are in crisis but not _immediate danger_ to hotlines or similar 24/7 resources (e.g., [crisistextline.org][text])? These help bridge the huge gap between non-urgent services, which can have a wait time of weeks or months, and emergency care. There's no international standards organization with a canonical list of these, but the International Association for Suicide Prevention has a [directory of crisis centers/hotlines][iasp], organized by continent.

[e129]: http://www.itu.int/net/itu-t/inrdb/e129_important_numbers.aspx
[text]: http://crisistextline.org
[geoip]: https://github.com/ip2location/ip2location-ruby
[iasp]: https://www.iasp.info/resources/Crisis_Centres/

**Comment by shelleyvadams** [comment]
One less legal concern:
According to [this Federal Trade Commission FAQ][faq], non-profit websites aren't required to comply with the _Children's Online Privacy Protection Act (COPPA)_.

I heard a story about kids and YouTube on the radio this morning and started wondering if this was something we needed to think about.

[faq]: https://www.ftc.gov/tips-advice/business-center/guidance/complying-coppa-frequently-asked-questions

**Comment by shelleyvadams** [comment]
On second thought l18n for emergency number, etc. might be more appropriate as part of the panic button feature, #187.

**Comment by julianguyen** [comment]
This is a great idea Shelley, let's do that then!
