### ISSUE TITLE
Can allies sign in with Google?

### ISSUE THREAD

**Issue by shelleyvadams** [ifmeorg/ifme#507]
When my family member followed the link in her ally invitation email to accept the invitation, she didn't see any way to sign up with her Google account, just a form to create a password.

Is it possible for an ally to sign in with Google, or only with a password?

**Comment by julianguyen** [comment]
Excellent question. Didn't realize this bug, but yeah, you can only sign up via password when you are given an allies invitation. Once you create an account with a password, and that account is a google account, you should be able to log in via Google auth. But we should allow users to join right away with Google auth.

**Comment by jnamster** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(3) Add Google auth support to accepting ally invites](https://trello.com/c/GczM7BHF/60-3-add-google-auth-support-to-accepting-ally-invites)

**Comment by SophieRoseMcDonald** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(3) Add Google auth support to accepting ally invites](https://trello.com/c/GczM7BHF/60-3-add-google-auth-support-to-accepting-ally-invites)

**Comment by alexiamcdonald** [comment]
Let me know if you need any help. @abrophy and I are working on other Google related issues.

**Comment by julianguyen** [comment]
@alexiamcdonald No one is working on this at the moment, so you could take it on :D

**Comment by alexiamcdonald** [comment]
Ok I'll take a look tomorrow. Maybe I can knock two birds out with one stone. 😄
