### ISSUE TITLE
Add tag filtering to Resources page

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#563]
The [Resources](https://www.if-me.org/resources) page is getting long and we want to best help point folks to mental health resources all over the interwebs. Let's add a feature to filter resources by tags (including languages that they're offered in).

You can find the designs for that page here: https://www.figma.com/file/RTjPkO0nSuJcMqqWLjeVdEof/if-me

**Comment by rarwolf47** [comment]
Is this being worked by anyone? I'd like to try my hand at it.

**Comment by baohouse** [comment]
@rarwolf47 Looks like it's assigned to @katrynmc ; you'll want to sync up with her and see where you can pick up some of the pieces.

**Comment by katrynmc** [comment]
@baohouse I'd say grab it, I haven't had the time lately - hadn't started

**Comment by andy5995** [comment]
@baohouse looks looks like you reassigned it to katrynmc instead of rarwolf47

**Comment by baohouse** [comment]
I can't assign it to @rarwolf47; probably he has to fork the project first?

**Comment by rarwolf47** [comment]
How about now?

**Comment by baohouse** [comment]
@julianguyen Would you have any luck with reassigning this? Not sure why I can't.

**Comment by julianguyen** [comment]
@rarwolf47 You can only assign collaborators of the repo to issues, I sent you an invite! You should accept via email!

**Comment by rarwolf47** [comment]
Done!

**Comment by aamarill** [comment]
@andy5995 I can work on this. Do we know, roughly, how we want this implemented? thanks!

**Comment by aamarill** [comment]
Unfortunately, I can't work on this at the moment. Thank you for expressing interest @seanmfox

**Comment by julianguyen** [comment]
@seanmfox Just case you don't find/notice it, we have an existing custom Input component which you can preview in Storybook that you can use.

**Comment by seanmfox** [comment]
Great, thanks!  In looking at past conversations, what was in mind for how the tag filtering should work?  In finding some past conversations, ideas being tossed around seemed to include dropdown, word cloud, and search box.
