### ISSUE TITLE
Add some info about EditorConfig in readme?

### ISSUE THREAD

**Issue by pederjohnsen** [ifmeorg/ifme#593]
I just noticed there is a `.editorconfig` file in the repo, but some editors (including the 2 I use) don't support those files out of the box. It might be nice to perhaps add some more info about it here https://github.com/julianguyen/ifme#style-guide even if just linking to this page: http://editorconfig.org/#download

It might help ensure new contributors don't use wrong indentation etc by mistake.

Also, I've not used `EditorConfig` before, but it looks like we are only applying the indentation etc rules to ruby files? Surely we want to apply it to more than just the ruby files?

**Comment by alexiamcdonald** [comment]
Great idea considering `rubocop` only takes into account ruby files.

We currently have no instructions or documentation apart from the added gem that `rubocop` exists in the project so we might have to make appropriate changes to reflect that in the instructions in the style guide.

Might be easier to add that for now if we are only considering ruby files.

**Comment by julianguyen** [comment]
We could set up a rake command run JSHint and Rubocop or add some kind of pre-commit hook that runs both of these.

An .editorconfig would be great! Would you be interested in working on this @pederjohnsen? :D

**Comment by HashNotAdam** [comment]
@julianguyen you only just asked me to remove Guard which does exactly this :laughing::laughing::laughing:

**Comment by julianguyen** [comment]
Oh dang. Hmmm we could reintroduce it! Thoughts everyone?

**Comment by pederjohnsen** [comment]
@julianguyen I wouldn't mind updating the `.editorconfig` file, but I'd need everyones input on what should be tied to the styling guide if not everything and if any type of file has "special requirements" compared to everything else.
