### ISSUE TITLE
not receiving daily strategy email reminders

### ISSUE THREAD

**Issue by andy5995** [ifmeorg/ifme#601]
I registered on if-me.org a couple days ago.

I set up a daily medi**c**ation reminder, and a daily medi**t**ation reminder.

I've received two me**d**ication reminders, but no me**d**itation reminders.

**Comment by baohouse** [comment]
@abrophy Is this possibly related to #586?

**Comment by abrophy** [comment]
I'm looking into this now,

**Comment by abrophy** [comment]
Tested this on the live site and I've been receiving reminder e-mails regularly, are you still encountering issues @andy5995

**Comment by andy5995** [comment]
Yes, still encountering issues. I've never received any meditation reminder emails.

In my account, the box to receive them is still checked.

I received mediCation reminder emails with no problem before I disabled them.

**Comment by andy5995** [comment]
Just verified again that the box is checked. Yes it is... but I've never gotten the reminders. Everyone else does though, eh?

**Comment by julianguyen** [comment]
I think I found the issue, for some reason, the scheduler we have on production was not set up for running the rake task `send_perform_strategy_reminders`. Just set this up now. The next due task will be sent out `Oct 7 13:30 UTC`. @andy5995 could you let me know if you received anything then?

**Comment by andy5995** [comment]
Working!

**Comment by julianguyen** [comment]
Omg thank glob haha. Thanks for checking!
