### ISSUE TITLE
linking to international pages to increase search engine indexing

### ISSUE THREAD

**Issue by andy5995** [ifmeorg/ifme#622]
On the home page, if crawl-able links were added to the ES and BR pages, that would help provide results in those languages to people who read and speak those languages. Would a change like that be worth making?

Current Google ES search results for **site:if-me.org salud mental**
https://www.google.es/search?q=site%3Aif-me.org+salud+mental&oq=site%3Aif-me.org+salud+mental

**Comment by andy5995** [comment]
@localhostpedro All of these results from Google BR are in English.

https://www.google.com.br/search?source=hp&q=site%3Aif-me.org&oq=site%3Aif-me.org

Do you have an opinion on what I wrote in the top post? How about @esBeee ?

**Comment by andy5995** [comment]
And if I wasn't clear, I was thinking of links that can be crawled by search engines.

For example..  if-me.org/es  would be a mirror or alias to the es pages. Search engines would be able to spider all those pages from a link on if-me.org.

Yes, it would add to the clutter, unfortunately, but maybe the language links could be made very small (a single horizontal layout, as I see it), and the current drop-down box would remain as-is. The small-font links would just be there for search engines to crawl through.

If subdomains can be made for free, then probably es.if-me.org would be preferred over if-me.org/es

**Comment by zawmoelwin** [comment]
I personally think subdomain approach is better suited as there will be less changes. 
If we just want to be crawled by google bot, we can actually put display hidden div and some javascript to change it to display inline to an event that will be very hard to be triggered.

https://webmasters.stackexchange.com/questions/27060/do-search-engines-see-comments-in-the-source-code-as-a-backlink

**Comment by andy5995** [comment]
> I personally think subdomain approach is better suited as there will be less changes.
> If we just want to be crawled by google bot, we can actually put display hidden div and some javascript to change it to display inline to an event that will be very hard to be triggered.
> 
> https://webmasters.stackexchange.com/questions/27060/do-search-engines-see-comments-in-the-source-code-as-a-backlink

Is that the plan then?

**Comment by andy5995** [comment]
This was closed without discussion? Was it deemed to be not a good idea?
