### ISSUE TITLE
Fix styling in Moments graph

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#639]
![image](https://user-images.githubusercontent.com/3010728/30500260-66ecf0b2-9a12-11e7-8c39-344b1b1ff723.png)

* Use the Lato font for this graph

**Comment by julianguyen** [comment]
@carmenwright Would you be interested in picking this up as your first PR? :D

**Comment by carmenwright** [comment]
Yes I would.

**Comment by jacobkjhan** [comment]
Hey! Is this issue possibly still open for contribution? Thanks!

**Comment by carmenwright** [comment]
It's still open. I haven't been able to work on it.

**Comment by abbyck** [comment]
I can get this done  and I'm complete noob to contributions. Please, someone can guide me?

**Comment by sriordan9** [comment]
Hi there! I’m new to open source contributions and would like to try helping on this if no one has updated the font yet. I have tried setting up ifme to see if I could even get it running before I volunteered to help, but when trying to start the server using `bin/start_app` it just exits with “code 1”. Terminal seems to attempt starting the server but the last thing I see is: 
![image](https://user-images.githubusercontent.com/26680784/32854354-580c8240-ca0c-11e7-97d2-41c63c9bb9ba.png)
Any help would be really appreciated!

**Comment by extremelypenguin** [comment]
is this issue still open? I'd like to work on this

**Comment by tyrantdavis** [comment]
Is this issue open? 

Regards

**Comment by aamarill** [comment]
Hello,

I am looking to make my first open source contribution. Is this a good issue to take on?
If not, feel free to point me other issues that might be good for someone that's new to open source.
Thanks!

**Comment by baohouse** [comment]
@aamarill Feel free to take it on.

**Comment by baohouse** [comment]
Yeah, that is correct, just change graph's font to Lato. I believe we're using chart.js, so if there's anything in the documentation there that mentions overriding base font, that's where I'd look, because I think the charts are rendered using canvas element I think, so CSS wouldn't really work.

**Comment by aamarill** [comment]
@baohouse thanks so much for the clarification, that helps me out a ton. 
So, we want to change the font of the "Moments" graph only correct (vs. all graphs on the site)?

**Comment by baohouse** [comment]
There's only one graph, which is in "Moments", so technically, changing it _is_ changing all graphs on the site, lol.

**Comment by aamarill** [comment]
@baohouse lol! ok, so I think I figured it out. There's two ways of doing it. Changing all fonts in a "global" way via something like `AllChart.defaults.global.defaultFontFamily = 'lato';` or by individually setting the properties of the graph when building it like

```javascript
<AreaChart
              xtitle={this.props.xtitle}
              ytitle={this.props.ytitle}
              data={this.props.data}
              colors={colorSchemes}
              library={{
                 scales: {
                    xAxes: [{
                      ticks: {
                        fontFamily: desiredFont
                      }
                    }]
                  }
              }}
            />
```

Is there a preferred way? Many thanks!

**Comment by baohouse** [comment]
@aamarill Let's do global way!

**Comment by aamarill** [comment]
Hey @baohouse thanks for all of your help so far!
I am pretty much done and are running tests. Do you have any suggestions on where and/or how it would be best to create the test for the new font? Is a test necessary for this change?

Any insight is much appreciated.

**Comment by baohouse** [comment]
@aamarill Documentation was old. The repo was moved a few months ago.

**Comment by baohouse** [comment]
Thanks for your work @aamarill! You're welcome to join the ifme slack community. Would you like to join?

**Comment by aamarill** [comment]
@baohouse I would love to be part of the slack community! If you have any other newbie-friendly issues, feel free to point me to them.  Unfortunately, I haven't used React before, so it'd be best to avoid those for now 😄. Otherwise, I'll start looking to see what else I can help with.

**Comment by baohouse** [comment]
@aamarill Email me at 4228012+baohouse@users.noreply.github.com and I'll invite you.

**Comment by aamarill** [comment]
@baohouse I got this 
<img width="687" alt="screen shot 2018-05-17 at 7 26 48 am" src="https://user-images.githubusercontent.com/29871004/40183872-b6c3cca4-59a3-11e8-83c1-046b7432d9fa.png">

**Comment by baohouse** [comment]
code@baohouse.net
