### ISSUE TITLE
Pull Requests HOWTO

### ISSUE THREAD

**Issue by andy5995** [ifmeorg/ifme#649]
@julianguyen  I added a page to the wiki.

 https://github.com/julianguyen/ifme/wiki/HOWTO:-Pull-Requests

 If you like it, a link to it can be added in the README.md (heading: Committing work -> pull requests), or the wiki page can be integrated into the README

I adapted the instructions from one of my existing projects, and I think it's mostly all good, but definitely could use a review by anyone here.

**Comment by architapatelis** [comment]
@julianguyen if you'd like I can add the Pull Request Instructions directly to README.md or to [Workflow.md](https://github.com/julianguyen/ifme/blob/master/WORKFLOW.md) under the `Committing Work` section. I also found a minor typo in the [wiki](https://github.com/julianguyen/ifme/wiki/HOWTO:-Pull-Requests), `Periodically, you'll need the sync your repo with mine (the upstream).`  You have to change **the** to **to**. Please let me know when you have the time, thanks!

**Comment by dippersauce** [comment]
I think it would be best to add it to WORKFLOW.md, since we just finished reorganizing the documentation so everything wasn't piled into the README.md.

**Comment by v27u27** [comment]
Can anybody tell me, what exactly has to be done to resolve this issue, because i want to contribute, and just for your information i am a beginner in open source contributions.

**Comment by architapatelis** [comment]
@dippersauce @julianguyen I made a pull request earlier today, please have a look and let me know if anything needs fixing. Thanks in advance!

**Comment by ginna-baker** [comment]
This issue looks ready to close

**Comment by julianguyen** [comment]
Aha you're right, let's do that! :) Thank you!
