### ISSUE TITLE
Translation bug for Portuguese

### ISSUE THREAD

**Issue by SophieRoseMcDonald** [ifmeorg/ifme#665]
Translation bug for Portuguese 
```ActionView::Template::Error (translation missing: ptbr.date.formats.long):
1: <%= ::TimeAgo.created_or_edited(local_assigns[:data]) %>
2: <% if local_assigns[:data].category.count > 0 %>
3:   <br>
4:   <strong>

app/services/time_ago.rb:11:in `formatted_ago'
app/services/time_ago.rb:18:in `created_or_edited'
app/views/moments/_info.html.erb:1:in _app_views_moments__info_html_erb__673145105344836068_70307964841260'```

**Comment by localhostpedro** [comment]
Checking this one....

**Comment by julianguyen** [comment]
@localhostpedro Any updates on this?

**Comment by localhostpedro** [comment]
@julianguyen yes I am : Changing my computers and reorganising my projects.  Be ready for tomorrow, top.

**Comment by zawmoelwin** [comment]
Can anyone elaborate more on how to replicate the issue?

After trying to replicate the issue(cannot replicate the issue), but  found another bug , language locale translation missing. 
"translation missing: ptbr.datetime.distance_in_words.less_than_x_minutes"

How to recreate: Sign in. Change the app language to Portuguese. Create new moment by clicking on + sign novo memento. Fill the form and create the moment.  The created moment shows the message.
