### ISSUE TITLE
using _new instead of _blank for target attribute or getting rid of _blank completely

### ISSUE THREAD

**Issue by andy5995** [ifmeorg/ifme#676]
I understand why you use target="_blank" for external links.

Does this happen in every browser?

Here's the potential problem:

1. from if-me.org, click external link. It opens the link in a new tab
2. from if-me.org, click a different external link. It loads in the same tab as the previous link, thereby taking the user away from the page of the first link (and maybe the user didn't want that page to be changed).

I think it would be better if each external link opened in it's own tab. Not sure if "_new" is compatible with the latest HTML5 spec though. According to this it's not:

https://stackoverflow.com/questions/4964130/target-blank-vs-target-new

So I'd suggest using an equivalent, or doing away with "_blank" altogether. It seems to me that the usage of "_blank" is a little outdated, less sites designed that way, and now users can decide if they want a new tab or window by using the right click -> open in new window || middle mouse button. I think the "_blank" option was more relevant before browsers had that option. Basically, omitting the "_blank" allows the user to choose (freely) if they want a new tab or window open.

**Comment by julianguyen** [comment]
Thanks for bringing this up. The most upvoted answer in that StackOverflow post you share actually says to use `"_blank"`. We've been using that instead of `"_new"`. We should be consistently using `"_blank"` for external pages, that's worth putting in our style guide. 

Did you actually encounter the potential problems you raised?

**Comment by andy5995** [comment]
Yes.

I'm using Firefox 55.0.3 on Debian Linux 9.

**Comment by andy5995** [comment]
It also happens on [Chromium](https://www.chromium.org/)

> Version 61.0.3163.100 (Developer Build) built on Debian 9.1, running on Debian 9.1 (64-bit)
