### ISSUE TITLE
Add error messages to form submissions with required fields missing.

### ISSUE THREAD

**Issue by jeffreyroy** [ifmeorg/ifme#682]

**Comment by jeffreyroy** [comment]
Error reporting is inconsistent at the moment.  Each form should display a clear error message if required fields aren't filled in.

**Comment by julianguyen** [comment]
@jeffreyroy are you still working on this? :)

**Comment by vedipen** [comment]
Hey @julianguyen!
I can get this done if that's cool!

**Comment by seannam** [comment]
So this is done and should be marked closed?

**Comment by julianguyen** [comment]
Oooh yeah @seannam you're totally right! Thanks for calling this out! I shall close it!
