### ISSUE TITLE
Redesign homepage icons and use SVGs instead

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#685]
Let's re-design these:
![image](https://user-images.githubusercontent.com/3010728/31092148-53de3f1e-a762-11e7-83a6-242acf310ac9.png)

We also have other unused icons we should redesign as well. Let's use a similar outline style as the original icons as well. https://github.com/julianguyen/ifme/tree/master/app/assets/images

**Comment by dippersauce** [comment]
There's a lot of problem with the originals and I agree we should redesign them. The current ones have inconsistent line weights and scaling.

**Comment by faraazahmad** [comment]
There's a site called The Noun Project. They have LOTS of icons with PNGs and SVGs. Here, take a look
https://thenounproject.com/search/?q=book
