### ISSUE TITLE
Redesign Story cards 

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#686]
Requirements
- Redesign these cards so that it isn't cluttered with text
- Make post author distinctive, include circular avatar 

### Desktop/Tablet:
![image](https://user-images.githubusercontent.com/3010728/31095701-9facf9e2-a76e-11e7-9927-8fb9a3085185.png)

### Mobile:
![image](https://user-images.githubusercontent.com/3010728/31095782-dcb2e716-a76e-11e7-827d-bd19779553ea.png)

### Desktop/Tablet:
![image](https://user-images.githubusercontent.com/3010728/31095711-a92715f2-a76e-11e7-9090-179a1b813c90.png)

### Mobile:
![image](https://user-images.githubusercontent.com/3010728/31095729-b6735356-a76e-11e7-8ac5-368769208e03.png)

**Comment by asiahoe** [comment]
Hi @julianguyen I'm interested in working on this for hacktoberfest! 😄
