### ISSUE TITLE
Check the feasibility of using React-draft-wysiwyg editor in place of CkEditor

### ISSUE THREAD

**Issue by nma** [ifmeorg/ifme#687]
Component under consideration

- https://jpuri.github.io/react-draft-wysiwyg/#/

Why?

In support of #659 , the newer component implements hash tag functionality as this is a more modern requirement in WYSIWYG editors. The task would appear as follows:

- [ ] Load react-draft-wysiwyg into the React Client App side by side
- [ ] Check the options on the new component (disable hashtags to start, etc)
- [ ] Wire the data entry into the new wysiwyg editor
- [ ] Regression test with existing entries

**Comment by julianguyen** [comment]
We're using this now! WOoooo
