### ISSUE TITLE
App redesign

### ISSUE THREAD

**Issue by nshki** [ifmeorg/ifme#691]
## EDIT (Oct 26, 2017)

Designs have been ported to Figma and the latest can be viewed [at this link](https://www.figma.com/file/RTjPkO0nSuJcMqqWLjeVdEof/if-me).

## Overview

The need for a full app redesign was discussed and we are currently working on rethinking it from the ground up. This thread originally started in the Slack community, but we are going to start documenting it in GitHub.

## Initial Mockups

The following are some mockups of the homepage I created to explore a visual direction. The color scheme is likely going to stay the same as the current app, but I added pink/blue variation as well. Using a simple, line-based visual language to convey openness and focus. This style would be used throughout the entire app. The font used will likely be Lato to stay consistent with the logo.

![ifme-redesign-home-1](https://user-images.githubusercontent.com/1121087/31249695-4c128a3e-a9e6-11e7-9492-98986eed4307.png)
![ifme-redesign-home-2](https://user-images.githubusercontent.com/1121087/31249701-51a63266-a9e6-11e7-80ff-19461e393890.png)
![ifme-lato-og-colors](https://user-images.githubusercontent.com/1121087/31249707-5472004c-a9e6-11e7-883c-ccef43a47db0.png)
![ifme-lato-og-colors-2](https://user-images.githubusercontent.com/1121087/31249712-56302e90-a9e6-11e7-8e64-cb712e8b9ab3.png)

## Next Steps

- [x] Rethink stories, you, and document icons
- [x] Design menu
- [x] Put Sketch files somewhere where people can collaborate on them (open to suggestions here!)

And of course, design everything else :)

**Comment by nshki** [comment]
Iterated some more on the original idea.

- Sticking to a palette based off of original site colors
- Using "About", "Blog", "Resources", and "Sign In" as nav links for not logged in users (thinking about a sidebar once a user is logged in for the rest of the app)
- Added _if me_ logo front and center
- Added latest blog posts
- Redid icons for "features" section
- Moved original line illustrations into background
- Added circles around contributor avatars
- Added "Resources" link in footer

![home-v3](https://user-images.githubusercontent.com/1121087/31321234-8f99c486-ac50-11e7-8f29-bd95a42bae6d.png)

Feedback is welcome! Will be exploring "logged in" screens next: moments, strategies, medications, groups, allies, etc.

**Comment by julianguyen** [comment]
This looks amazing so far! Thanks for this 🎉 

Looks like we should start off with redesigning our non-mandatory signed in pages. Wondering if the join link would appear in the header navigation when we navigate away from the homepage.

Also would it help to have headings in the footer to provide context for each column?

**Comment by nshki** [comment]
@julianguyen Ah, for the join link, I'll go ahead and adjust the last nav item so that it's "Sign in / Join." Also, I'll go ahead and add headings for each footer column to mirror the current site!

Do you have any preference for the next screen to be designed? Was thinking of tackling moments.

**Comment by julianguyen** [comment]
Moments would be a good feature to do since it's the main one.

@asiahoe expressed interest in redesign the story cards that are used throuhgout the site https://github.com/julianguyen/ifme/issues/686

Maybe you two could collaborate? :)

**Comment by rheupler** [comment]
I would love to work on actually building these designs to the existing site, if no one has committed. Or if it's being done, let me know if I can help in any way!

**Comment by nshki** [comment]
@rheupler We will likely have some dev planning discussions (either in Slack or somewhere in GitHub) once the redesigned screens are ready to be developed! We'll loop you in when we're there.

@julianguyen Sounds good. 😄

**Comment by nshki** [comment]
Some more design progress. Finishing up the non-mandatory pages @julianguyen mentioned above before tackling logged in screens (moments, strategies, etc.). Will have a go at the resources page next.

## About
![about](https://user-images.githubusercontent.com/1121087/31419761-9fba7394-ae0b-11e7-90be-a84271b4201d.png)

## Blog
![blog](https://user-images.githubusercontent.com/1121087/31419765-a56c9718-ae0b-11e7-9fec-be043bd51aa2.png)

**Comment by julianguyen** [comment]
Wow I love the designs on the static pages! I'm wondering for our signed in pages whether we should using black text on white background to display Moments etc.

**Comment by julianguyen** [comment]
Also do you think the colour contrast is enough for the selected link in the header? Should we be using `#D0E799`? Same for the colour contrast with the author name in the Blog mockup?

**Comment by julianguyen** [comment]
@rheupler Can you email us at join.ifme@gmail.com so we can add you to our Slack? :D Thanks for expressing interest :D

**Comment by nshki** [comment]
@julianguyen For moments cards etc. I'm definitely planning on using a black on white or some variant of it!

For active links in the nav, I could try playing with adding another visual indicator other than color to make it more clear. #D0E799 looks a little off in the header unfortunately. I can brighten up the author name just a smidge.

Also, for blog posts, what do you think about adding posted date as well?

**Comment by nma** [comment]
@nshki  This is super cool, love the visual revamp 🥇

**Comment by nma** [comment]
As for next steps, I was thinking we can start slicing out sections/components and start an UI components library akin to what many folks are doing using React + StoryBook e.g https://hackoregon.github.io/component-library/

As for how we want to do that, do we want a separate NPM package to import into the main rails app? Or do we want to centralize it all inside the main app? @julianguyen @baohouse @nshki ?

**Comment by nshki** [comment]
@nma Love that idea. I'm on board. I think I want to vote for keeping all components centralized in the main app unless we are willing to build a full API on the Rails side (to allow for separate front and back end repos). Building the components in a separate repo / package feels strange if we aren't building all the screens there as well. I can definitely be convinced otherwise though.

**Comment by nma** [comment]
@nshki I think that writing a full API on Rails at this moment is an anti-goal. My original thinking was that components could be worked on separately from the main app, and might be easier to contribute to, but after thinking about it more, creating two pull requests for each repo might not be natural workflow for most people. 

We can build it into the main app, and its pretty easy to pull it out later if we need it. So centralized to start?

**Comment by nshki** [comment]
@nma Centralized to start sounds good to me.

---

As a general update, Sketch documents have been ported over to Figma, and @asiahoe and I will be collaborating on the designs moving forward.

Let's hold off on building the component library until the designs are somewhat finalized, since a lot can still change.

**Comment by nshki** [comment]
Another update. Since designs have been ported to Figma, I'll be able to share using links from this point forward (hurray!).

You can catch the latest in design land with [this link](https://www.figma.com/file/RTjPkO0nSuJcMqqWLjeVdEof/if-me). I'll update the original comment to show this and a screenshot is attached as well.

<img width="923" alt="screenshot 2017-10-26 22 57 09" src="https://user-images.githubusercontent.com/1121087/32086109-066740c6-baa1-11e7-8bab-586981e52613.png">

**Comment by timofonic** [comment]
@nshki @asiahoe Thanks! It looks nice! Any news?

**Comment by nshki** [comment]
@timofonic Thanks! We're still cranking away at the design. You can see the latest [at this link](https://www.figma.com/file/RTjPkO0nSuJcMqqWLjeVdEof/if-me).

**Comment by nshki** [comment]
@nma @baohouse I apologize about the delay in updates! December was a crazy time for me and I had a hiatus due to an injury.

I think we can go ahead and start development on the redesign, although not everything is complete yet. Basic atomic components are more or less defined, and I think in-browser development will give us the flexibility we need for design decisions that require more group contextual knowledge.

What do you all think?

**Comment by julianguyen** [comment]
Latest designs look fantastic! Looks like we can start creating issues for the basic atomic components! I think its' a good idea to build out the smaller components first, it would also get us using React more :D

**Comment by nshki** [comment]
Just for easy access, here is the link to the Figma document: https://www.figma.com/file/RTjPkO0nSuJcMqqWLjeVdEof/if-me

---

Alrighty! Now that it's verified that **registered** Figma users (don't worry it's free for individual accounts) can click around and view CSS properties (colors, dimensions, etc. thanks to @baohouse and @julianguyen), I think we're ready to move forward! Any illustrations that need to be exported should be exportable from the Figma document as SVGs. Please ping me if for some reason that is not working for you.

I'll get a start on creating separate issues for components we can start building.

**Comment by baohouse** [comment]
![screen shot 2018-04-12 at 12 31 06 pm](https://user-images.githubusercontent.com/4228012/38699645-73d489f4-3e4d-11e8-8d6d-f2b619ca93c5.png)

Worth noting on tablet, the UI component interaction is different than mobile. So tablet is in between mobile and desktop.

**Comment by AllanOcelot** [comment]
Colourwise I'd highly advise against using the red colour so much, it's overpowering. 

I'd advise a steel blue / neutral grey colour.

In the latest screenshot for instance, we are using the red on a 'give feedback' icon - but users will always instinctively associate red with a negative action, and thus red should be reserved for such things.


One could use the arguments of 'the colour represents our current branding' etc - but thats what this is, a large redesign, I would use it as an opportunity to establish a solid and consistent colour palette.

The overall direction is solid though and I think many of the layout changes are good and justified.
