### ISSUE TITLE
Split off language-based assets into their own JavaScript files

### ISSUE THREAD

**Issue by baohouse** [ifmeorg/ifme#726]
# Description

Right now our main JavaScript file contains all language bundles. This isn't a huge performance problem right now, but we'll want to start thinking of splitting off the language bundles to load only what we need.

May have to think about how JavaScript is loaded so we don't run into dependency and load-order issues.

---
Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by baohouse** [comment]
This improvement could probably be done as part of #719

**Comment by julianguyen** [comment]
We should definitely do this! Another neat optimization is only loading the translations needed for a page.

**Comment by son-vyas** [comment]
@baohouse @julianguyen , I would like to give this a try. We you make me understand what it is to be done, since I am a new beginner

**Comment by anushkajj** [comment]
Hi! I am a beginner and would like to make my first contribution. 
Is this issue still available?
