### ISSUE TITLE
Integrate automated security testing with Snyk

### ISSUE THREAD

**Issue by sexybiggetje** [ifmeorg/ifme#737]
Snyk.io offers automated security testing. I saw this being used on a few other repositories on github. They provide free services to open source projects.

Maybe it could be integrated like circle-ci.
https://snyk.io/

**Comment by julianguyen** [comment]
Wow, this looks awesome, thanks for suggesting this! Anyone feel free to pick this up!

**Comment by sexybiggetje** [comment]
>  Some repos require GitHub administrator privileges before they can be added to Snyk

@julianguyen So I think it's best if you add this. Just sign in, press get started for developers, and add the project.
And optionally add the badge to the README.md

**Comment by abhishekr700** [comment]
Hi, is someone working on this ? I would like to try my hand on this

**Comment by pederjohnsen** [comment]
As a side note, github has similar features now already built in: https://github.com/blog/2470-introducing-security-alerts-on-github though it seems using Snyk.io would still be a good choice as it seems to have much more vulnerability data available etc.

**Comment by CSumm** [comment]
Is this issue still open?

**Comment by greysteil** [comment]
@CSumm looks like this is still open.

I'd also like to recommend [Dependabot](https://dependabot.com), the tool I've built to automatically create dependency update PRs. It can be put in security-only mode, and only create security related PRs, or can create PRs for all updates. You can see some of the PRs it has created on other repos [here](https://github.com/pulls?q=is%3Apr+author%3Aapp%2Fdependabot+is%3Aclosed).

I've just submitted a PR to get ifme running using Rails 5.1.6. Once that's merged, I'd love it if you considered running Dependabot on this repo to keep its dependencies up-to-date and secure.

❤️

**Comment by sexybiggetje** [comment]
Except for maybe @greysteil comment about his dependabot this ticket is quite obsolete. Snyk doesn't provide anything github now doesn't. At the time of writing Github didn't launch this feature yet.

I'm closing this issue. If one wants to take a stab at something related, a new issue can be created.
