### ISSUE TITLE
Refactor Moments and Strategies to React components

### ISSUE THREAD

**Issue by dbarner1** [ifmeorg/ifme#766]
- [ ] Refactor Moments
- [ ] Refactor Strategies
- [ ] Update test for Moments
- [ ] Update test for Strategies

**Comment by julianguyen** [comment]
@dbarner1 How is this coming along? :)

**Comment by dbarner1** [comment]
Oh boy. Sorry, can't get to this because of crazy bandwidth issues. :/ :/ :/

Hope to get back to this in a few months. Sorry :(
