### ISSUE TITLE
Refactor for Readability & Separation of Concerns.

### ISSUE THREAD

**Issue by aleciavogel** [ifmeorg/ifme#772]
While doing some refactoring tonight, I noticed a lot of stuff that could be cleaned up as far as models, associations, and overall separations of concern go and thought I should create an issue to discuss this.

**A couple of examples:**
- the foreign key for a user is `userid` instead of `user_id`? (Not sure if there's a specific reason for this, but it struck me as slightly out of the ordinary)
- there's no index in the tables for userid ([here's why they're important](http://bamboolab.eu/blog/rails-postgresql-index-btree-gin-gist))
- `Moment.where(userid: user.id).all.recent` should just be `user.moments.recent`, etc
- I see negated methods like `!@something.blank?` used a lot in the views. `@something.present?` is usually preferred for readability reasons and does the same thing (more info on these ruby methods [here](https://pramodtech.quora.com/nil-empty-blank-present-in-Ruby-on-Rails))
- There's queries happening in the view sometimes that I'd like to eliminate. For instance, [this line](https://github.com/aleciavogel/ifme/blame/site-title/app/views/groups/_form.html.erb#L50) has a `User.where` statement. From my experience, it's usually best to keep everything that queries the DB in the model as much as possible.

I hope this doesn't come across as too nit-picky, especially since I'm new to contributing here. I really like the idea of this project, especially since it reminds me of 7CupsOfTea, and would love to help as much as I can.

I'm more than happy to take on this task if you're on board with it.

**Comment by julianguyen** [comment]
@aleciavogel I am totally on board with this! Thank you for all this all out! Can you email us at join.ifme@gmail.com so we can add you to our Slack? :)

**Comment by nshki** [comment]
Closing this issue, please refer to #839 and #841 (which captures remaining tasks) for further progress on refactoring!
