### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by panjim** [ifmeorg/ifme#776]
Hi everyone, i joined the french translation team few days ago.
I saw that many people worked on the translation for a while, but i couldn't find any of the documents to contribute, or at least do some proofreading...

We need those 4 docs:
-devise.fr.yml (from I18n)
-devise_invitable.fr.yml (trad. of devise_invitable.en.yml)
-fr.yml (trad. of en.yml)
-kaminari.fr.yml (trad. of kaminari.en.yml)

if you know something about it please tell me, before i translate everything an other time.

**Comment by inesbenomar18** [comment]
Hi, I'd love to contribute to the French translation team! 👋🏼

**Comment by hugodahl** [comment]
I'd be happy to help with the French translations as well if there is any more need for it

**Comment by julianguyen** [comment]
@hugodahl We definitely need help, it's not being worked on at the moment.

Thanks for expressing your interest. We would love your help with this issue. Please follow these [next steps](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack) to join our contributor community.

**Comment by simtaxx** [comment]
hey, i want to help you for tgis, how can i help ?

**Comment by julianguyen** [comment]
@hugodahl @simtaxx This is our [process](https://github.com/ifmeorg/ifme/wiki/Translations) on translations. Please follow these [next steps](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack) to join our contributor community.

**Comment by CCoupris** [comment]
Hi I translated the file "kaminari.fr.yml" but I'm a new member of GitHub so I don't know exactly how to upload the file in the project. Could you help me please ?
