### ISSUE TITLE
[Component] Button

### ISSUE THREAD

**Issue by nshki** [ifmeorg/ifme#777]
## Overview

We are looking for an awesome human to build this out as a React component, preferably within Storybook. You can view and get details (colors, dimensions, export SVGs, etc.) by visiting [the Figma designs](https://www.figma.com/file/RTjPkO0nSuJcMqqWLjeVdEof/if-me?node-id=65%3A618) and creating a free account.

This is part of the app redesign (#691).

## Screenshot from [the Figma document](https://www.figma.com/file/RTjPkO0nSuJcMqqWLjeVdEof/if-me?node-id=65%3A618):

![screenshot 2018-01-09 at 6 06 45 pm](https://user-images.githubusercontent.com/1121087/34747835-e1e1d8d6-f567-11e7-9884-58393221f6cf.png)

**Comment by trishla08** [comment]
@nshki can I try this?

**Comment by nshki** [comment]
@trishla08 Still completely open! If you open the Figma document and create an account, you'll be able to navigate through screens and also see a page that contains components individually. The task would be to create a React component (ideally in Storybook) that can render each variant of the button -- this could be done by passing additional props or class names.

Let me know if that makes sense!

**Comment by trishla08** [comment]
@nshki hi! I made the component, hopefully it is what you wanted. For some reason, I just can't get storybook to work and my terminal keeps showing errors. 

Anyway, this is what my react component made. It will return all 5 buttons.
![image](https://user-images.githubusercontent.com/27439626/35239908-d2a7c95a-ffd7-11e7-81a3-86b99a58fec1.png)

If it's good enough, I can make a PR, let me know!

**Comment by nshki** [comment]
@trishla08 Great! There might be a couple nitpicky things but go ahead and open a PR so we can review in detail. :)

Would be ideal if we could help you get Storybook setup properly as well. If you could make sure to [allow changes from maintainers](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/), that would amazing!

**Comment by trishla08** [comment]
Made a PR with edits allowed.

**Comment by trishla08** [comment]
@nshki just noticed the checks seem to be failing.. Codeclimate is failing since my code contains 2 similar classes but that is a consequence of having similar buttons. I have no idea why CircleCI is failing..

**Comment by nshki** [comment]
@trishla08 First off, thanks so much for your contribution! :)

Julia (the founder) is actually in the process of building out a component, so would it be alright if I get back to you after she makes a PR? It should give us a good baseline for naming conventions, component architecture, styling methods, etc. It'd also be good to help you get up and running with Storybook.

I'll start writing comments in your PR (#791) from this point forward!

**Comment by amarpathak** [comment]
@nshki  Is the Issue Still Open ? Its seems like  more than one month has passed and Its not merged . So If possible can I take this issue ?

**Comment by nshki** [comment]
@amarpathak Hi there! @trishla08 is currently working on this in her PR. If there is any more work to be done, you could perhaps sync with her.
