### ISSUE TITLE
[Component] Input

### ISSUE THREAD

**Issue by nshki** [ifmeorg/ifme#778]
## Overview

We are looking for an awesome human to build this out as a React component, preferably within Storybook. You can view and get details (colors, dimensions, export SVGs, etc.) by visiting [the Figma designs](https://www.figma.com/file/RTjPkO0nSuJcMqqWLjeVdEof/if-me?node-id=65%3A618) and creating a free account.

This is part of the app redesign (#691).

## Screenshot from [the Figma document](https://www.figma.com/file/RTjPkO0nSuJcMqqWLjeVdEof/if-me?node-id=65%3A618):

![screenshot 2018-01-09 at 6 17 13 pm](https://user-images.githubusercontent.com/1121087/34748185-543c8650-f569-11e7-930c-1c9a7aa48c50.png)

**Comment by Seunadex** [comment]
@nshki Can this issue be closed since it has been done or any reason we still want it opened?

**Comment by nshki** [comment]
@Seunadex Nope you're quite right, this can be closed now. :) Resolved with #792!
