### ISSUE TITLE
[Component] Radio Button

### ISSUE THREAD

**Issue by nshki** [ifmeorg/ifme#779]
# Description

We are looking for an awesome human to build this out as a React component, preferably within Storybook. You can view and get details (colors, dimensions, export SVGs, etc.) by visiting [the Figma designs](https://www.figma.com/file/RTjPkO0nSuJcMqqWLjeVdEof/if-me?node-id=65%3A618) and creating a free account.

This is part of the app redesign (#691).

## Screenshot from [the Figma document](https://www.figma.com/file/RTjPkO0nSuJcMqqWLjeVdEof/if-me?node-id=65%3A618):

![screenshot 2018-01-09 at 6 18 41 pm](https://user-images.githubusercontent.com/1121087/34748230-8e311f10-f569-11e7-9531-024d0f885ac6.png)

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by aSquare14** [comment]
I'd like to work on this issue!

**Comment by nshki** [comment]
Take it away @aSquare14! :)

**Comment by aSquare14** [comment]
What symbol should come up in checkbox after clicking? Also is the checkboxradio a button or input?

**Comment by nshki** [comment]
@aSquare14 It's a custom shape, as shown in the mockups and the screenshot posted above!

**Comment by aSquare14** [comment]
Okay ! I wanted to be sure, when I click on it, should it change state and a get filled up. And on clicking again should it be restored to original? Does it have state ?

**Comment by nshki** [comment]
@aSquare14 You should be able to do it using a standard `<input type="checkbox">`! You can hide the actual input and have neighboring elements change visually using sibling selectors in your styles.

e.g.
```css
/* ... */

.checkbox__input {
  display: none;
}

.checkbox__input:checked + .checkbox__mark {
  /* ... */
  display: block;
}
```

**Comment by aSquare14** [comment]
Thanks ! Will work on it ! Pretty helpful.

**Comment by aSquare14** [comment]
One Question ! When I click on it, what should pop up on the radiobutton ? A tick or it should look like CheckBoxRadioChecked?

**Comment by nshki** [comment]
@aSquare14 It should look like `CheckBoxRadioChecked` you're exactly right.

**Comment by aSquare14** [comment]
Hey ! Radiobuttons and Checkboxes are different! You asked me to use a checkbox but issue is named radiobutton ! Which one should I use ? 
also I got the basic thing working !

**Comment by nshki** [comment]
@aSquare14 It should look like the `CheckBoxRadio` mocks! Please see the original screenshot as well if you aren't sure which component you should be building for this issue.

**Comment by aSquare14** [comment]
Okay ! From the original mocks, my understanding is that I should be
building a radiobutton and not a check box !  On it!

**Comment by aSquare14** [comment]
https://github.com/ifmeorg/ifme/issues/780
Since the above is a checkbox , I think this issue requires a radio-button ! Hence, will have to use a `<input type="radio">` .

**Comment by nshki** [comment]
@aSquare14 Ah you know what, now that I go back and look at the Figma documents, I definitely made this unclear. If you could, would you be able to have the component generate both a checkbox and radio based on a prop that gets passed?

**Comment by aSquare14** [comment]
Yes , I can do that ! On it !

**Comment by aSquare14** [comment]
@nshki  Code is getting messy . Can I create two components in this PR ?
1. Radiobutton
2. Simple Checkbox 
Because I have to use different logic for both of them. Radio is mutually exclusive while user can select as many checkboxes he/she wants.

**Comment by nshki** [comment]
Yep, that sounds good to me!

**Comment by aSquare14** [comment]
I have restarted working on it !

**Comment by skenypatel** [comment]
Hey, is this still on hold off?

**Comment by nshki** [comment]
@skenypatel Great question! I assume that since the label is still present, it's still on hold. Going to loop in @julianguyen here, as she'll have the best context to provide an answer for you.

**Comment by lazio** [comment]
Hey guys, is this one available to pick up? I hope I can help with it

**Comment by nshki** [comment]
Hey @lazio, thanks for checking in! This issue is still on hold, so it's not ready for pick up.

**Comment by lazio** [comment]
ok, I get it. Thanks for letting me know

**Comment by julianguyen** [comment]
I'm gonna close this issue because adding custom components for radio buttons and checkboxes creates an unnecessary abstraction that requires us to put more effort to make it accessible.
