### ISSUE TITLE
[Component] Switch (Checkbox)

### ISSUE THREAD

**Issue by nshki** [ifmeorg/ifme#780]
## Overview

We are looking for an awesome human to build this out as a React component, preferably within Storybook. You can view and get details (colors, dimensions, export SVGs, etc.) by visiting [the Figma designs](https://www.figma.com/file/RTjPkO0nSuJcMqqWLjeVdEof/if-me?node-id=65%3A618) and creating a free account.

This is part of the app redesign (#691).

## Screenshot from [the Figma document](https://www.figma.com/file/RTjPkO0nSuJcMqqWLjeVdEof/if-me?node-id=65%3A618):

![screenshot 2018-01-09 at 6 20 24 pm](https://user-images.githubusercontent.com/1121087/34748273-c7e96b54-f569-11e7-89d7-761851a49eba.png)

**Comment by julianguyen** [comment]
@ariperez how is this coming along?

**Comment by ariperez** [comment]
Julia...apologize for the delay, I wanted to finish it up before I took off
on vacation last week, but that didn't happen. Working on it now and will
have an update by end of weekend.

**Comment by aSquare14** [comment]
@ariperez  Are you working on this? If not, can I take it up ?

**Comment by ariperez** [comment]
@aSquare14 , I'll go ahead and assign to you.  Took on more than I can handle at this point. :(

**Comment by aSquare14** [comment]
@ariperez No worries. Thanks!  :)

**Comment by DomitriusAnthony** [comment]
Would like to take this on if I can!

**Comment by aSquare14** [comment]
Go ahead!  I'm presently working in something else :)

**Comment by DomitriusAnthony** [comment]
Thanks @aSquare14 ! You're throwing me my first PR :)

**Comment by prateksha** [comment]
@nishki Is anyone working on this? If not, I would like to work on it.

**Comment by nshki** [comment]
@prateksha I'm not quite sure if anyone's actively working on the issue at the moment. If @DomitriusAnthony can confirm within a few days that would be ideal, but if not, you can go ahead!

**Comment by julianguyen** [comment]
I'm going to finish up this feature

**Comment by aSquare14** [comment]
Cool
