### ISSUE TITLE
[Component] Resource

### ISSUE THREAD

**Issue by nshki** [ifmeorg/ifme#783]
## Overview

We are looking for an awesome human to build this out as a React component, preferably within Storybook. You can view and get details (colors, dimensions, export SVGs, etc.) by visiting [the Figma designs](https://www.figma.com/file/RTjPkO0nSuJcMqqWLjeVdEof/if-me?node-id=65%3A618) and creating a free account.

This is part of the app redesign (#691). This also will incorporate another component #782.

## Screenshot from [the Figma document](https://www.figma.com/file/RTjPkO0nSuJcMqqWLjeVdEof/if-me?node-id=65%3A618):

![screenshot 2018-01-09 at 6 24 47 pm](https://user-images.githubusercontent.com/1121087/34748419-6732c8f4-f56a-11e7-869a-90258ef1ee50.png)

**Comment by Seunadex** [comment]
@nshki @julianguyen Kindly give more clarity to this, i seems not to fully get how it should be?

**Comment by nshki** [comment]
Just as a public FYI, we had a discussion regarding the above question over Slack. The Figma mockup of the resources page was referenced for context.

**Comment by baohouse** [comment]
@nshki Is it the case that the tags and the author are optional, and that it's possible to have:
1. both visible
2. tags visible only
3. author visible only
4. neither visible

**Comment by Seunadex** [comment]
From what I'm aware of, it is either the tags or the author which is the only difference between the two components, @nshki can do more justice to that.

**Comment by baohouse** [comment]
@nshki For this component, is author and tags mutually exclusive, or can both exist simultaneously?

**Comment by nshki** [comment]
@baohouse In the designs I only used the tags for external resources and authors for internal ones, but it makes sense to be able to have both tags and authors co-exist. Sorry about the late reply, by the way!

**Comment by Seunadex** [comment]
This is completed and can be closed now
