### ISSUE TITLE
[Component] Dropdown

### ISSUE THREAD

**Issue by nshki** [ifmeorg/ifme#784]
## Overview

We are looking for an awesome human to build this out as a React component, preferably within Storybook. You can view and get details (colors, dimensions, export SVGs, etc.) by visiting [the Figma designs](https://www.figma.com/file/RTjPkO0nSuJcMqqWLjeVdEof/if-me?node-id=65%3A618) and creating a free account.

This is part of the app redesign (#691).

## Screenshot from [the Figma document](https://www.figma.com/file/RTjPkO0nSuJcMqqWLjeVdEof/if-me?node-id=65%3A618):

![screenshot 2018-01-09 at 6 26 41 pm](https://user-images.githubusercontent.com/1121087/34748471-abedac2a-f56a-11e7-9220-3e5c2f9a1234.png)

**Comment by pederjohnsen** [comment]
I might want to take this one on, just gotta get storybook setup etc first :)

**Comment by nshki** [comment]
Take it away @pederjohnsen! :)

**Comment by pederjohnsen** [comment]
@nshki I'll try get storybook setup within the next couple of days and give it a go :tada:

**Comment by pederjohnsen** [comment]
I didn't get to jump on this as soon as I had hoped :(. If someone else would like to pick it up please feel free to, though if nobody does I'll jump on this as soon as I'm able to!

**Comment by Seunadex** [comment]
@pederjohnsen I will be helping out with this

**Comment by Seunadex** [comment]
@nshki The PR for this issue has been merged, it can be closed now
