### ISSUE TITLE
[Component] Card

### ISSUE THREAD

**Issue by nshki** [ifmeorg/ifme#785]
## Overview

We are looking for an awesome human to build this out as a React component, preferably within Storybook. You can view and get details (colors, dimensions, export SVGs, etc.) by visiting [the Figma designs](https://www.figma.com/file/RTjPkO0nSuJcMqqWLjeVdEof/if-me?node-id=65%3A618) and creating a free account.

This is part of the app redesign (#691). This incorporates another component #782.

## Screenshot from [the Figma document](https://www.figma.com/file/RTjPkO0nSuJcMqqWLjeVdEof/if-me?node-id=65%3A618):

![screenshot 2018-01-09 at 6 28 35 pm](https://user-images.githubusercontent.com/1121087/34748517-ea577f54-f56a-11e7-95a1-99de177a00d6.png)

**Comment by nshki** [comment]
@julianguyen I'm gonna assign you #782 as well since this component uses a subcomponent, if you don't mind!

**Comment by julianguyen** [comment]
I'm still working on this :) Things have been busy these past few weeks. I'm going to aim to finish this up this weekend! Sorry folks!

**Comment by dhaval0894** [comment]
Hi @nshki, @julianguyen! Is this still open? I can take this up if @julianguyen haven't started on this :)

**Comment by julianguyen** [comment]
@dhaval0894 I actually started working on it in this branch `moment-card`, haven't gotten a chance to finish cause I've been super busy, but you're totally welcome to take over it. The only think I have left to do is add the tags.

**Comment by dhaval0894** [comment]
Thanks, @julianguyen. I'd be glad to.
