### ISSUE TITLE
[Component] Profile Modal

### ISSUE THREAD

**Issue by nshki** [ifmeorg/ifme#786]
## Overview

We are looking for an awesome human to build this out as a React component, preferably within Storybook. You can view and get details (colors, dimensions, export SVGs, etc.) by visiting [the Figma designs](https://www.figma.com/file/RTjPkO0nSuJcMqqWLjeVdEof/if-me?node-id=65%3A618) and creating a free account.

This is part of the app redesign (#691).

## Screenshot from [the Figma document](https://www.figma.com/file/RTjPkO0nSuJcMqqWLjeVdEof/if-me?node-id=65%3A618):

![screenshot 2018-01-09 at 6 29 59 pm](https://user-images.githubusercontent.com/1121087/34748559-27050b1a-f56b-11e7-82e9-f0f001e8973f.png)

**Comment by f3mshep** [comment]
I would like to take this issue!

**Comment by HeyStevenXu** [comment]
Hey @f3mshep , just wanted to ask if you were still working on this component! I can work on this if you've been busy- just let me know :)

**Comment by DomitriusAnthony** [comment]
Would love to help!

**Comment by LachlanRidley** [comment]
Hi @nshki, I'm having a go at making this component and I was just wondering at what stage I should make a pull request? Is it better to do it early so that I can get feedback or should I wait until it's done to my satisfaction? Thanks :)

**Comment by nshki** [comment]
@LachlanRidley Feel free to submit a pull request whenever you'd like! I generally only review PRs when the author(s) feels that it's done though. :)

**Comment by LachlanRidley** [comment]
Perfect, thanks :)

**Comment by LachlanRidley** [comment]
@baohouse, thanks, I've done that

**Comment by aSquare14** [comment]
I'm taking this up ! :D
