### ISSUE TITLE
[Component] SideNav

### ISSUE THREAD

**Issue by nshki** [ifmeorg/ifme#787]
## Overview

We are looking for an awesome human to build this out as a React component, preferably within Storybook. You can view and get details (colors, dimensions, export SVGs, etc.) by visiting [the Figma designs](https://www.figma.com/file/RTjPkO0nSuJcMqqWLjeVdEof/if-me?node-id=65%3A618) and creating a free account.

This is part of the app redesign (#691).

## Screenshot from [the Figma document](https://www.figma.com/file/RTjPkO0nSuJcMqqWLjeVdEof/if-me?node-id=65%3A618):

![screenshot 2018-01-09 at 6 31 20 pm](https://user-images.githubusercontent.com/1121087/34748597-57d1a500-f56b-11e7-8635-bc9b025bd9f4.png)

**Comment by stevenpeniche** [comment]
I would like to claim this issue

**Comment by nshki** [comment]
@stevenpeniche Take it away!

**Comment by stevenpeniche** [comment]
I'm a newbie and I think I might have bitten off a bit more than I can chew. I'm going to have to drop this one. Apologies 😅

**Comment by nshki** [comment]
@stevenpeniche No worries!

**Comment by CSumm** [comment]
Hey I worked on the sidenav. I tried to make it color coding with the theme of the website

**Comment by nshki** [comment]
@varshika15 Appreciate it! It seems like @CSumm is already working on this, though, so perhaps you two could coordinate and tag team this.

**Comment by CSumm** [comment]
Hi its nearly done but I can have you check it out and see if you can improve it. Im always accepting help. Contact me directly and I can send you the code Im working with.

**Comment by CSumm** [comment]
Or via Slack (which might be easier)

**Comment by SoonaMata** [comment]
@CSumm I can definitely try to help you if you want to send it to me! In the meantime I'll be working on it as well!

**Comment by CSumm** [comment]
Hi! I'm working with @GeoDoo on my version of it. We could all assign a time to work on it. The major issue I have is with flow annotation. Send a message on slack and I can send you what I have so far.
