### ISSUE TITLE
[Component] Footer

### ISSUE THREAD

**Issue by nshki** [ifmeorg/ifme#788]
## Overview

We are looking for an awesome human to build this out as a React component, preferably within Storybook. You can view and get details (colors, dimensions, export SVGs, etc.) by visiting [the Figma designs](https://www.figma.com/file/RTjPkO0nSuJcMqqWLjeVdEof/if-me?node-id=65%3A618) and creating a free account.

This is part of the app redesign (#691). This incorporates another component #784.

## Screenshot from [the Figma document](https://www.figma.com/file/RTjPkO0nSuJcMqqWLjeVdEof/if-me?node-id=65%3A618):

![screenshot 2018-01-09 at 6 32 30 pm](https://user-images.githubusercontent.com/1121087/34748628-7eb52098-f56b-11e7-89cd-dab9407a9844.png)

**Comment by Seunadex** [comment]
Hi @nshki I'll like to take this up if no one is working on it yet.

**Comment by nshki** [comment]
@Seunadex That would be great! This component incorporates one other component (#784), but feel free to start this one.

**Comment by Seunadex** [comment]
@nshki Concerning the dropdown on the lower left of the footer ,do I need to add that or will it come from the reusable dropdowns in another issue?

**Comment by nshki** [comment]
Ideally the dropdown should be built in a separate PR first, and then incorporated into this one!

**Comment by Seunadex** [comment]
@nshki Also i'm issue getting to use the image in the text on the lower right of the footer

**Comment by Seunadex** [comment]
@nshki I'm trying to raise a PR now, but i'm getting the `can't automatically merge` error

**Comment by nshki** [comment]
@Seunadex Don't worry about the background images, those are simply a part of the brochure page backgrounds. The background color of the footer should just be a slightly transparent shade with no images.

The error might be because you don't have the latest changes pulled down. Make sure you pull down the latest changes from the original repo.

**Comment by Seunadex** [comment]
@nshki , @julianguyen  I have a PR up kindly review and let me know if you have any feedback
