### ISSUE TITLE
[Component] Header

### ISSUE THREAD

**Issue by nshki** [ifmeorg/ifme#789]
## Overview

We are looking for an awesome human to build this out as a React component, preferably within Storybook. You can view and get details (colors, dimensions, export SVGs, etc.) by visiting [the Figma designs](https://www.figma.com/file/RTjPkO0nSuJcMqqWLjeVdEof/if-me?node-id=65%3A618) and creating a free account.

This is part of the app redesign (#691).

## Screenshot from [the Figma document](https://www.figma.com/file/RTjPkO0nSuJcMqqWLjeVdEof/if-me?node-id=65%3A618):

![screenshot 2018-01-09 at 6 34 01 pm](https://user-images.githubusercontent.com/1121087/34748681-b55b8790-f56b-11e7-9f25-f9c3684b33c6.png)

**Comment by DanielAmah** [comment]
@nshki  I will like to take this up if no one is working on it.

**Comment by nshki** [comment]
@DanielAmah Take it away, Daniel!

**Comment by kedpak** [comment]
Is this issue still up? I would like to work on it.

**Comment by Seunadex** [comment]
@kedpak its yours

**Comment by prox07** [comment]
Can I take this up? I can design it.

**Comment by prox07** [comment]
Hey I can fix this if anyone could assign it to me.
