### ISSUE TITLE
A proposal logo 

### ISSUE THREAD

**Issue by 0relmely** [ifmeorg/ifme#790]
Hi !
Congratulation for the project  , I want share a proposal logo .

Link to see a full develop . Thanks
https://steemit.com/utopian-io/@orelmely/contribution-proposal-logo-to-ifme-community-for-mental-health

**Comment by ajithmel** [comment]
this is okay, maybe make something that looks more health related, like adding a brighter red color

**Comment by julianguyen** [comment]
Thanks for sharing this! I'm open to changing our logo (I designed the current one). We would definitely have to brainstorm more. I don't think you're on our Slack yet @gitgamer! Email us a join.ifme@gmail.com and we'll add you! We can chat more there!
