### ISSUE TITLE
Incorporating facebook

### ISSUE THREAD

**Issue by aSquare14** [ifmeorg/ifme#795]
# Description

- We can write a general sessions controller function and integrate login with Facebook.
- It is better to have both options as some people prefer using facebook login and will be motivated to share about If-me on their facebook.

- Also,we can give the user an option of sending their facebook friends invites to the website in "Allies" section.

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by aSquare14** [comment]
presently @steffanibrasil and I are working on it.

**Comment by baohouse** [comment]
Still need to add if-me.org to the domain whitelist in the Facebook app. @stefannibrasil has control over it I believe.

**Comment by baohouse** [comment]
We did a merge into production, but I had to disable and revert the PR #856 because of an authorization flaw in which logging in gave you access to other people's posts. We'll need to investgate the cause of that and perhaps use a staging environment for testing.

**Comment by baohouse** [comment]
If there's anyone who can look into the authorization issue, as I don't have much experience in the whole backend architecture.

**Comment by julianguyen** [comment]
Holding off for now since Facebook recently faced security vulnerabilities with their oauth service.

**Comment by stefannibrasil** [comment]
hi, all! I want to get back to contribute to ifme. Do you think I can continue on this? Thank you :)

**Comment by julianguyen** [comment]
@stefannibrasil Feel free to! That would be great, I would just watch out for any security issues.

**Comment by stefannibrasil** [comment]
great, I'll get back to this, then, thank you, @julianguyen :)

**Comment by julianguyen** [comment]
OAuth service issues have been resolved! This issue is up for grabs :)
