### ISSUE TITLE
Reminder for taking medicine

### ISSUE THREAD

**Issue by aSquare14** [ifmeorg/ifme#797]
In the "Medications" section. We can ask the user the frequency and days in a week when they have to take meds.

Then on the specified days, we can send them a reminder mail. This will ensure that the users take meds on time.

Can be implemented using SendGrid SMTP or ActiveMailer.

**Comment by yasirazgar** [comment]
@julianguyen @aSquare14
I would like to work on this.

I investigated a bit and came up with the following 
1. Already there is an daily reminder option, additional weekly option should be added (I believe monthly option is not needed).
2. Need to modify the dosage option in medication, maybe like, 
     daily_dosage - array - [0,0,0] (morning, afternoon, night)
     weekly_dosage - array - [0,0,0,0,0,0,0]
if all are 0's in weekly_dosage, then we can conclude that the medication is daily dosage else it is weekly.
3. I think we can modify the existing TakeMedication reminder a bit accordingly and use it.

Please let me know your thoughts. Once confirmed, I will start working on this.

**Comment by julianguyen** [comment]
This sounds good to me. I would start with implementing weekly reminder first and then have a separate PR for the type of dosage per day. I'm not sure how much detail we want to add to the dosage field and how common that is.

Also! Please email us at join.ifme@gmail.com and I'll add you to our Slack where we can discuss stuff further :)

**Comment by yasirazgar** [comment]
@julianguyen, I have implemented weekly_reminder in https://github.com/ifmeorg/ifme/pull/832,
Do we need daily reminder based on dosage time (morning, afternoon, night), is that needed or can we leave it.

**Comment by swastikbanerjee07** [comment]
What are the works left to be done in this issue?
Is there any way I can contribute?

**Comment by aSquare14** [comment]
Hi! @swastikbanerjee07 Someone has already sent a PR on this. Maybe you could find another issue ! Let me know if you need help finding .

**Comment by julianguyen** [comment]
@swastikbanerjee07 So @yasirazgar did open a PR for this but it never got merged. There's merge conflicts right now. Maybe you could help review it and resolve them if Yasir is unable to do so.

https://github.com/ifmeorg/ifme/pull/832

**Comment by swastikbanerjee07** [comment]
@julianguyen Thanks!
Sure. I would look into it.
