### ISSUE TITLE
Adding Hyperlinks in FAQ section

### ISSUE THREAD

**Issue by aSquare14** [ifmeorg/ifme#799]
The bold texts in purple eg. "Moments" can be made as hyperlinks. So,if the user clicks on it he/she will be directed to the respective sections.It will make the page more interactive and navigation easy !

**Comment by f3mshep** [comment]
I would like to claim this issue!

**Comment by f3mshep** [comment]
How should I style the Hyperlinks? I have attached a screenshot with three different styles.

![crop](https://user-images.githubusercontent.com/20713700/36126981-f6769ce2-100f-11e8-9e54-1e2b16c776a4.gif)

**Comment by f3mshep** [comment]
Just opened a PR for this [issue](https://github.com/ifmeorg/ifme/pull/810)

**Comment by Transvivor** [comment]
@f3mshep Love the top on, the teal with the underline. It makes it stand out and is the most colorblind friendly.
