### ISSUE TITLE
UI fix

### ISSUE THREAD

**Issue by aSquare14** [ifmeorg/ifme#800]
![img20180205032124-01](https://user-images.githubusercontent.com/22938709/35782848-d0e4f50a-0a24-11e8-9504-5aaf2a913118.jpeg)

On moving cursor over "We <3 Foss", it shows weird behaviour. This can be fixed !

**Comment by andre-lfa** [comment]
This part has a css cursor property

![screenshot_1](https://user-images.githubusercontent.com/33098462/35971850-acc88e7c-0cb6-11e8-8358-60d3783f33ff.png)
![screenshot_2](https://user-images.githubusercontent.com/33098462/35971851-acf4760e-0cb6-11e8-801f-0cb8c91ba4b3.png)

According to the W3C website, this property has support for this browser's: 

![image](https://user-images.githubusercontent.com/33098462/35973236-dafc82c6-0cbb-11e8-96f9-c0162e506e5f.png)


I've tested in Firefox, Chrome and IE and looks normal to me, what is your browser?

**Comment by aSquare14** [comment]
I have chrome in Ubuntu 16.04.

**Comment by aSquare14** [comment]
I have Google Chrome !

**Comment by prateksha** [comment]
When you move the cursor over We <3 Foss, the cursor changes to a question mark. This is confusing for the user as the line is not a hyperlink nor does it have any special property. It is simply text.
So, by changing 
```
.yes_title{  cursor: default;
}
```
I would like to change the behavior of the cursor as it hovers above "We <3 Foss."

**Comment by julianguyen** [comment]
Thanks for calling this out, I'm cool with updating the cursor to default. We could just remove that css property entirely and it will default to the default setting.

**Comment by aSquare14** [comment]
Cool ! I'll do it !

**Comment by Aseged** [comment]
Is this fixed already? If not I could have a look as i am trying to get into FOSS @aSquare14

**Comment by aSquare14** [comment]
@Aseged it is fixed! Good luck with other issues :)
