### ISSUE TITLE
Search feature in Resources

### ISSUE THREAD

**Issue by aSquare14** [ifmeorg/ifme#806]
I think we can work on a search bar in Resources that filters out articles based on tags. Will be helpful to people looking to read articles on specific issues.

Or maybe make a separate list of tags where articles are listed by tags.

**Comment by CSumm** [comment]
Im currently doing a crash course on React, but would like to do this if there hasnt been any takers

**Comment by GeoDoo** [comment]
@CSumm Are you working on this? Do you need any help?

**Comment by CSumm** [comment]
Hi @GeoDoo, I have the script written but would like to get some help refactoring it to include annotations and such. I can send you what I have so far and maybe we can work on it together. It functions its just needs to be written to annotate props and a few fixes here and there.

**Comment by CSumm** [comment]
My apologies, i thought this was the sidenav issue. You can do this one.

**Comment by Seunadex** [comment]
Hey @GeoDoo, how is going with this issue?

**Comment by GeoDoo** [comment]
hey @Seunadex sorry for holding it so much time! I was super busy! I removed my face hahaha

You can take it if you want! Sorry again for the delay

**Comment by andy5995** [comment]
@nickeyvee , thanks for the offer. I see you made it 11 days ago. Are you still interested? We're a little behind here but that happens from time-to-time. :)

**Comment by julianguyen** [comment]
Deleting this cause it's a duplicate of #563
