### ISSUE TITLE
Add instructions after new PRs have been merged.(StoryBook)

### ISSUE THREAD

**Issue by aSquare14** [ifmeorg/ifme#814]
As a newbie, after the merging of a PR, I was unable to run storybook. I was then advised to run `yarn install` for it to work. 

Could we add a line in the wiki preferably here [https://github.com/ifmeorg/ifme/wiki/Common-Dev-Environment-Errors](url) ?

- **If Storybook doesn't work after merging of new PR .**
`yarn install` is used to install all dependencies for a project. This is most commonly used when you have just checked out code for a project, or when another developer on the project has added a new dependency that you need to pick up. 
Please run this command after you make your local repo upto date with upstream.

**Comment by julianguyen** [comment]
Hey thanks for bringing this up @aSquare14 <3 I think you we could just add a `yarn install` step to this [document](https://github.com/ifmeorg/ifme/wiki/Design).
