### ISSUE TITLE
Requesting for Hindi Translation 

### ISSUE THREAD

**Issue by aSquare14** [ifmeorg/ifme#830]

**Comment by julianguyen** [comment]
Ooh this would be awesome, is this something you would be able to work on or know someone who could work on it?

**Comment by aSquare14** [comment]
@julianguyen Even though my native language is Hindi, I think I lack the technical knowledge of Hindi to translate pages. I will definitely look around for people and get back to you. 
Can we tackle this after 3rd March?

**Comment by julianguyen** [comment]
That would be fantastic, thanks so much. Also, good luck with exams!!! 🤓 📚 🎉 🍀

**Comment by varshika15** [comment]
Hey I am from India! I would love to work on this issues.

**Comment by toshitapandey** [comment]
@julianguyen Is someone working on this or can it be picked up?

**Comment by julianguyen** [comment]
@toshitapandey OMG yes we would loveeeee your help!
