### ISSUE TITLE
License link missing from footer

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#833]
The license link disappeared from our footer :O
![image](https://user-images.githubusercontent.com/3010728/36645516-cee69416-1a1e-11e8-847d-27f94ac70e5e.png)
This is happening on Mac OS X Sierra on the latest build of Chrome.

**Comment by aSquare14** [comment]
I figured out the problem . The line was deleted during translation ! In en.yml also line is missing.

**Comment by Seunadex** [comment]
@aSquare14  yeah, figure that out too and currently working on it, but what i'm yet to figure out is why when its written like this `license_subtitle: 'Licensed under %{licence_name}'` does not work . the `license_name` is not displayed

**Comment by Seunadex** [comment]
Ok it works for the page but doesn't work for the react component on storybook

**Comment by julianguyen** [comment]
Ooh thanks @aSquare14 and @Seunadex for quickly investigating this <3

**Comment by julianguyen** [comment]
Quickly fixed the bug here: https://github.com/ifmeorg/ifme/pull/835
@Seunadex can address the footer React component in another pull request!
