### ISSUE TITLE
Refactor classes and methods that are too long

### ISSUE THREAD

**Issue by nshki** [ifmeorg/ifme#840]
From #839, many classes and methods were wrapped with `# rubocop:disable MethodLength` and `# rubocop:disable ClassLength` to temporarily make Rubocop happy. Those are all great indicators of refactoring opportunities.

Let's break those classes and methods up into smaller pieces. Could be a good opportunity to apply [DHH's controller development methodology](http://jeromedalbert.com/how-dhh-organizes-his-rails-controllers/) for controllers?

Files that could use this attention:
- [x] `controllers/application_controller.rb`
- [x] `controllers/allies_controller.rb`
- [x] `controllers/groups_controller.rb`
- [x] `controllers/moments_controller.rb`
- [x] `controllers/categories_controller.rb`
- [x] `controllers/omniauth_callbacks_controller.rb`
- [x] `controllers/strategies_controller.rb`
- [x] `controllers/moods_controller.rb`
- [x] `controllers/meetings_controller.rb`
- [x] `helpers/application_helper.rb`
- [x] `mailers/application_mailer.rb`
- [x] `models/user.rb`

**Comment by stefannibrasil** [comment]
I and @aSquare14 are working on #795 and I did a small refactor on the `controllers/ominiauth_callbacks_controller.rb` and on `model/user.rb`. We are planning to open the PR this week.

But I would like to work more on refactoring others too when we finish this one :)

**Comment by keitheous** [comment]
I would like to have a go at some of these. Let me get the system up and running, then I'll dive into this. Thanks =)

**Comment by Bennet11** [comment]
Hi there, i would also like to try and help on some of these. Is someone already assigned to this?

**Comment by nshki** [comment]
Hi @Bennet11, both @stefannibrasil and @keitheous are working on some at the moment. Perhaps you all could coordinate! We have a Slack channel, which may be the best way to communicate with other contributors. If you'd like to be a part of it, please email join.ifme@gmail.com.

**Comment by keitheous** [comment]
Awesome! Lets get in touch on slack so we do not git conflict. Will you notify me when you're on slack @Bennet11 ? 

I have plans to work with @tsara27 this Sunday on some of the controllers here.

**Comment by Bennet11** [comment]
@nshki Sorry I was not able to respond immediately. I was able to get in touch with Julia last night and she already invited me to join the slack channel

@keitheous that's great to hear! I'm on slack right now my name there is @JohnV

**Comment by nshki** [comment]
@rhiroyuki Go for it!

**Comment by knittingdev** [comment]
I would love to tackle `controllers/moments_controller.rb`

**Comment by nshki** [comment]
@knittingdev Thanks so much! Go for it!

**Comment by jaspervanbrian** [comment]
Can I contribute on this? Willing to work!

**Comment by nshki** [comment]
@jaspervanbrian Absolutely. :D Might need to loop @julianguyen in to get you in on the Slack channel.

**Comment by jaspervanbrian** [comment]
Can I claim this issue? I'm working on it now

**Comment by nshki** [comment]
@jaspervanbrian Of course. I unfortunately am not able to assign you directly, but once you're on the Slack channel and get added as a member to the repo, you'll be able to be assigned.

**Comment by jaspervanbrian** [comment]
I'm on the Slack channel now hehe

**Comment by julianguyen** [comment]
@jaspervanbrian Just added you to our ifmeorg team so after you accepted the invite, you can assign yourself to the task! But yes feel free to take on this task :) Thanks for your interest!

**Comment by jaspervanbrian** [comment]
thanks y'all 😃

**Comment by hmasila** [comment]
Hello, I would like to work on `meetings_controller` if that's still available

**Comment by julianguyen** [comment]
@hmasila Hey Hannah that would be great! Thanks so much :)

**Comment by bmwachajr** [comment]
I will take a go at this issue @julianguyen @nshki

**Comment by julianguyen** [comment]
Woo go right ahead, thanks @bmwachajr 🎉

**Comment by bmwachajr** [comment]
Hi @nshki,

I think it would be a good idea to refresh this list.

✅ The following controllers as they have already been refactored:
*  controllers/groups_controller.rb 
*  controllers/categories_controller.rb 
* Moods controller #866 
* Meetings controller #1080 
*  mailers/application_mailer.rb #1325 

The one other controller that needs refactoring(I am working on this one) is :
* controllers/strategies_controller.rb

Cc @julianguyen

**Comment by julianguyen** [comment]
Updated! Thanks for calling this out @bmwachajr :D
