### ISSUE TITLE
Rename some foreign keys and review database indexes

### ISSUE THREAD

**Issue by nshki** [ifmeorg/ifme#841]
This is spinning off of #839 and #772. Many tables in the database are using foreign keys such as `userid`, `groupid`, and the like. While this works, it's definitely out of the ordinary as @aleciavogel mentioned, so let's rename those to look more like `something_id`. I think this would potentially remove the need for `foreign_key: ___` in many models as well.

Additionally, let's review what columns are being indexed in the database and add additional indexes on columns that make sense.

**Comment by tsara27** [comment]
I am sorry for the delay. If you want to see the progress, you can see on my forked branch.
https://github.com/tsara27/ifme/tree/issue-841-rename-foreign-keys

**Comment by nshki** [comment]
@tsara27 Awesome, thanks! When it's ready for a comprehensive review, please open a PR and assign me and Julia to be reviewers. :D

**Comment by stvtortora** [comment]
@nshki  I noticed that their hasn't been an update on this issue in a while. Is it currently being worked on? If not, I'd like to! :)

**Comment by nshki** [comment]
@stvtortora As far as I know, it doesn't seem like it's being actively worked on at the moment. Feel free to take it!
