### ISSUE TITLE
[Component] Heading(s)

### ISSUE THREAD

**Issue by nshki** [ifmeorg/ifme#846]
## Overview

We are looking for an awesome human to build this out as a React component, preferably within Storybook. You can view and get details (colors, dimensions, export SVGs, etc.) by visiting [the Figma designs](https://www.figma.com/file/RTjPkO0nSuJcMqqWLjeVdEof/if-me?node-id=65%3A618) and creating a free account.

This is part of the app redesign (#691).

## Screenshot from [the Figma document](https://www.figma.com/file/RTjPkO0nSuJcMqqWLjeVdEof/if-me?node-id=65%3A618):

![screenshot 2018-03-10 at 12 05 24 pm](https://user-images.githubusercontent.com/1121087/37244780-d170b5a8-245b-11e8-88f8-94c196c3df05.png)

**Comment by aSquare14** [comment]
I'd like to claim this issue :)

**Comment by nshki** [comment]
All yours @aSquare14!
