### ISSUE TITLE
[Component] Blockquote

### ISSUE THREAD

**Issue by nshki** [ifmeorg/ifme#847]
## Overview

We are looking for an awesome human to build this out as a React component, preferably within Storybook. You can view and get details (colors, dimensions, export SVGs, etc.) by visiting [the Figma designs](https://www.figma.com/file/RTjPkO0nSuJcMqqWLjeVdEof/if-me?node-id=65%3A618) and creating a free account.

This is part of the app redesign (#691).

## Screenshot from [the Figma document](https://www.figma.com/file/RTjPkO0nSuJcMqqWLjeVdEof/if-me?node-id=65%3A618):

![screenshot 2018-03-10 at 12 05 54 pm](https://user-images.githubusercontent.com/1121087/37244795-08239dd6-245c-11e8-8f08-b0d82673bddc.png)

**Comment by varshika15** [comment]
I am willing to work on this issue!

**Comment by nshki** [comment]
@varshika15 Take it away!

**Comment by varshika15** [comment]
Yes take it away!
