### ISSUE TITLE
[Component] Pagination Bullets

### ISSUE THREAD

**Issue by nshki** [ifmeorg/ifme#848]
## Overview

We are looking for an awesome human to build this out as a React component, preferably within Storybook. You can view and get details (colors, dimensions, export SVGs, etc.) by visiting [the Figma designs](https://www.figma.com/file/RTjPkO0nSuJcMqqWLjeVdEof/if-me?node-id=65%3A618) and creating a free account.

This is part of the app redesign (#691).

## Screenshot from [the Figma document](https://www.figma.com/file/RTjPkO0nSuJcMqqWLjeVdEof/if-me?node-id=65%3A618):

![screenshot 2018-03-10 at 12 06 07 pm](https://user-images.githubusercontent.com/1121087/37244808-3af8c06a-245c-11e8-855e-4794943c9b04.png)

**Comment by anGie44** [comment]
i'd like to claim this issue! how can i join & contribute? sent an email to the join.ifme

**Comment by cartothemax** [comment]
Hey @anGie44! 👋 

Thanks for jumping on this. Be sure to take a look at the contributing doc if you haven't https://github.com/ifmeorg/ifme/blob/master/CONTRIBUTING.md

And I am guessing that someone will get back to you shortly regarding getting added to the Slack channel. Might just be a little delay 😃 

In the mean time though feel free to get going on this work and feel free to ask any questions on the issue. Hope that helps!

**Comment by nshki** [comment]
@anGie44 Great, take it away! I echo what @cartothemax says as well! I believe @julianguyen will add you as a collaborator/member so you can be assigned this task soon. :) Feel free to start though!

**Comment by prateksha** [comment]
@nshki Just wanted to clarify something. When we click/hover on Pagination 2 and 3 , should it change state to look like 1?

**Comment by ludamillion** [comment]
Not sure just how important this still is but I took a swing at it. The PR is here => https://github.com/ifmeorg/ifme/pull/1261

**Comment by julianguyen** [comment]
Closing this cause we got rid of pagination.
