### ISSUE TITLE
[Component] Avatar

### ISSUE THREAD

**Issue by nshki** [ifmeorg/ifme#849]
## Overview

We are looking for an awesome human to build this out as a React component, preferably within Storybook. You can view and get details (colors, dimensions, export SVGs, etc.) by visiting [the Figma designs](https://www.figma.com/file/RTjPkO0nSuJcMqqWLjeVdEof/if-me?node-id=65%3A618) and creating a free account.

This is part of the app redesign (#691).

## Screenshot from [the Figma document](https://www.figma.com/file/RTjPkO0nSuJcMqqWLjeVdEof/if-me?node-id=65%3A618):

![screenshot 2018-03-10 at 12 06 14 pm](https://user-images.githubusercontent.com/1121087/37244817-5351d89a-245c-11e8-80c1-18bb1a1501fb.png)

**Comment by GeoDoo** [comment]
@nshki Hi! I think I could possibly help out your cause! Could I tackle this one here? I think I need ot follow the CONTRIBUTING guide in order to get started, right?

**Comment by julianguyen** [comment]
Hey @GeoDoo that would be great! Could you email as at join.ifme@gmail.com so we can add you to our Slack? Thank you!

**Comment by GeoDoo** [comment]
@julianguyen Already did! Check it out!

**Comment by nshki** [comment]
Take it away @GeoDoo!

**Comment by GeoDoo** [comment]
@nshki Thanks, but I cannot assign myself to it! Are you sure I am part of the organization? :)

**Comment by nshki** [comment]
@GeoDoo That's not something I have control over unfortunately! @julianguyen can you add him to the org when you have time? :D

**Comment by GeoDoo** [comment]
Haha... just saw the invitation!! Assigned already!
