### ISSUE TITLE
When user is not logged in, cursor should be set as default or a message should pop up, "You must be logged in to use this feature"

### ISSUE THREAD

**Issue by aSquare14** [ifmeorg/ifme#852]
When I clicked on the "if-me" logo without logging in, I felt like it was supposed to do something. It just acts as a static logo when not logged in! Should we make this clear to the user ? 
![whatsapp image 2018-03-12 at 13 43 06](https://user-images.githubusercontent.com/22938709/37272057-7319bf9e-25fb-11e8-8342-4286b9c318e1.jpeg)

**Comment by yasirazgar** [comment]
@aSquare14 I think its is a valid behavior, usually on clicking the logo user will be directed to the root path. Eg. If the user is in About/Resources page on clicking the logo user will be sent to the home page.

I thought of removing the link if the user is already in home page, but if you see all the links in the app, they behave in the former way.

What do think ? let me know your thoughts.

**Comment by aSquare14** [comment]
Yes, you're right ! I am closing the issue :)
