### ISSUE TITLE
Reports: implement a 'report user' button on user profiles

### ISSUE THREAD

**Issue by alvarocasadoc** [ifmeorg/ifme#870]
This includes:
- Creating a 'report user' button that shows a modal with a form for adding additional notes.
- Submitting and saving the report to the database through a new action: `allies_controller#report`. (#14)
- Mailing the reported user to notify them that they've been banned and their case is being reviewed with a new mailer. (#873)

**Comment by aSquare14** [comment]
We're starting with this @alvarocasadoc @camillevilla !

**Comment by aSquare14** [comment]
@alvarocasadoc  Can you give us some idea on how to add modal ? We are struggling with it ! :P

**Comment by alvarocasadoc** [comment]
A modal is simply an interface component that displays content and temporarily blocks interactions with the rest of the view. You can handle this by simply creating a div that toggles its visibility based on a user interaction like clicking a button or a link. This can be easily done with a div and a button that triggers this visibility toggle function. 

Here you can find a basic example of this behaviour (which can be also animated, of course): https://www.w3schools.com/howto/howto_js_toggle_hide_show.asp

I've seen that you also took #786, so maybe you could take a look at https://github.com/reactjs/react-modal to see an example of a react component for a modal or maybe it can be integrated into the project.

Are you planning to implement it as a new component?

**Comment by aSquare14** [comment]
Oh okayy. For now I am not making a react component. Will first figure out the back-end and how to integrate this modal form with back-end. Later on maybe make a React Component !
