### ISSUE TITLE
Error test #UserCreatesAMedication

### ISSUE THREAD

**Issue by stefannibrasil** [ifmeorg/ifme#875]
After opening the PR #856, CircleCI started these showing 2 errors:  `Failure/Error: page.execute_script "#{element}[0].scrollIntoView(false)"`

It looks like the element hasn’t loaded yet by the time scrollIntoView is invoked. We probably need to assert the element exists first before we call scrollIntoView on it.

**Comment by nshki** [comment]
It seems that race conditions have already been handled by @baohouse as seen in PR #856. Closing! 🎉
