### ISSUE TITLE
Create admin user privileges re: blocking and reporting

### ISSUE THREAD

**Issue by camillevilla** [ifmeorg/ifme#901]
This ticket relates to #14 

- We need to create the ability to make a User an admin account
- Store the information as a column in the database
- New admins are created via the rails console by maintainers with access to the production server
- Add documentation (How do you become an admin? How is an admin added? Might split this off into a different ticket later). 

See #861 for the report management dashboard

**Other questions:**
- What admin privileges should a group leader have? Can a group leader remove block

**Comment by ScotianMan** [comment]
I can knock this out if its still a priority.. I see devise is being used for authentication but has anything been added at all in terms of authorization yet? I usually like to use CanCanCan, once added we can make admins all powerful and spin other issues of this to lock down the authorization of other users actions.  Or is authorization outside of the scope of this issue and a simple "admin" boolean field on the user table is enough?

**Comment by ScotianMan** [comment]
I will wait to start until  we can discuss a little 👍
