### ISSUE TITLE
Storybook not working due to latest commit

### ISSUE THREAD

**Issue by prateksha** [ifmeorg/ifme#912]
- [The latest commit modified the Stories.helper.jsx file.]( https://github.com/ifmeorg/ifme/blob/729ec2c2025a631ed1fcbdd9293223d67cab801b/client/app/stories/Stories.helper.jsx)
- The following lines were removed
`export function 
withSource(el: Node) {
  return withInfo()( () => el);
}
export {
   SingleColumnLayout,
 };
export default withSource;`
This lead to storybook not finding the function "withSource" and it failed to load. Screenshot is attatched below.
![screenshot from 2018-07-06 14-19-43](https://user-images.githubusercontent.com/32712346/42369591-0d915988-8128-11e8-8b7a-51f15447a671.png)

**Comment by baohouse** [comment]
withSource is no longer required. It has been removed from all *.stories.jsx files.

https://github.com/ifmeorg/ifme/blob/729ec2c2025a631ed1fcbdd9293223d67cab801b/client/app/stories/Avatar.stories.jsx
