### ISSUE TITLE
Profile page not rendering empty profile picture element correctly in Firefox

### ISSUE THREAD

**Issue by StaphSynth** [ifmeorg/ifme#924]
# Description 

I came across this today in Firefox (61.0.1):
<img width="703" alt="screen shot 2018-07-29 at 4 40 48 pm" src="https://user-images.githubusercontent.com/20519886/43364138-d7589d76-9357-11e8-8ca3-b3acb40be43b.png">

In Chrome it looks like this:
<img width="756" alt="screen shot 2018-07-29 at 5 01 19 pm" src="https://user-images.githubusercontent.com/20519886/43364143-ee40caa4-9357-11e8-90e4-badc1500e2be.png">

There are two issues here: (1) The rendering error of the empty circle in Firefox when you don't have a profile pic; and, (2) rendering `undefined` when you haven't set a location.

# Reproduction Steps

Create a test account and don't set a location or profile pic, then view the profile page in Firefox.

# Do you want to be the assignee to work on this?

🚫  It's not that I don't want to, it's that I have my hands full with other project issues atm.

**Comment by julianguyen** [comment]
I think, `undefined` is showing up because locally you haven't set up [Google Maps API](https://github.com/ifmeorg/ifme/wiki/Installation#google-api). But we should still handle that case in dev environments don't use this API.
