### ISSUE TITLE
Prepare application.html.erb for new app designs

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#932]
# Description 

In preparation to convert static pages to [new designs](https://github.com/ifmeorg/ifme/issues/691)

* Update Header, Footer
* Home page

# Do you want to be the assignee to work on this?

✅

**Comment by Essential** [comment]
I'll start working on it tomorrow.

**Comment by julianguyen** [comment]
Thanks for offering! I actually started working on it, but I could divide up the pages @Essential. 

How about I set up the initial structure of the new designs (header, content container, and footer) in application.html.erb, and then you can focus on converting the specific static pages over? How does that sound?

**Comment by CSumm** [comment]
I also would like to take a shot at one of the pages
