### ISSUE TITLE
Convert join page to new designs

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#934]
# Description 

Convert join page to new design

https://www.if-me.org/users/sign_up

[Designs in figma](https://github.com/ifmeorg/ifme/issues/691)

Requires: #932 to be completed first (currently being worked on by @julianguyen)

# Do you want to be the assignee to work on this?

🚫

**Comment by musangowope** [comment]
Hey julian, is it possible if I could assist helping on this page?
