### ISSUE TITLE
Add Github authetication

### ISSUE THREAD

**Issue by asquare14** [ifmeorg/ifme#961]
# Description 

I think apart from Google, Github authentication would be nice for signing up . :)

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by julianguyen** [comment]
Thanks for the suggestion! I agree with the hold off for now label on this issue. I don't think it's a huge priority, especially since most people outside of the tech community don't have Github accounts. The people who do have GIthub accounts usually sign in via GIthub if it's a developer/Github related tool or add-on.

**Comment by nelsonmfinda** [comment]
Hello, I'm participating in [Hacktoberfest.](https://hacktoberfest.digitalocean.com/) and would like to contribute to this feature. It will be my first open source contribution!

**Comment by julianguyen** [comment]
Hey @nelsonmfinda thanks for expressing interest! We're actually going to hold off this feature for now cause it's not a priority. Would you be interested in working on this one instead? https://github.com/ifmeorg/ifme/issues/796 It's also auth related.

Here's [next steps](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack) to joining our contributor community.

**Comment by CoderJolly** [comment]
> Hey @nelsonmfinda thanks for expressing interest! We're actually going to hold off this feature for now cause it's not a priority. Would you be interested in working on this one instead? #796 It's also auth related.
> 
> Here's [next steps](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack) to joining our contributor community.

Hi @julianguyen , I would love to work on this if its nt allotted, also #796 has many people working on it, would be be possible for you to find a another issue of the same category...
Thanks 👍

**Comment by julianguyen** [comment]
@CoderJolly You're welcome to work on this issue!

**Comment by PeasOfMind** [comment]
Happy to work on this if @CoderJolly is not.

**Comment by CoderJolly** [comment]
@PeasOfMind You can work on it, as it is festive season in India hence I am unable to devote time

**Comment by sbpipb** [comment]
hello hello! I would like to this on. @PeasOfMind 

I've started a bit already, please inform me.

**Comment by PeasOfMind** [comment]
yes please! go ahead @sbpipb I didn't get started at all.

**Comment by julianguyen** [comment]
Not a necessary feature
