### ISSUE TITLE
Do audit and improvements for better colour contrast and font size

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#969]
# Description 

Do audit and improvements for better colour contrast and font size. Let's aim for [Level AAA](https://www.w3.org/WAI/WCAG2AAA-Conformance) conformance for colour contrast and font size.

There's a lot of helpful a11y guides out there, this is just one of many that are great: https://a11yproject.com/

# Do you want to be the assignee to work on this?

🚫

**Comment by gpks** [comment]
Hi, I would like to do it :)

**Comment by digilou** [comment]
@julianguyen I'd be happy to take this on.

**Comment by digilou** [comment]
Can I just fork the repo and submit a PR that way, instead of joining as a contributor?

**Comment by julianguyen** [comment]
@digilou It would be preferred if you joined as a contributor so you could assign yourself to the issue. It's easier for us to keep track with assignees. 

Is there any specific reason why you just want to submit a PR right away without going through our usual process?

**Comment by digilou** [comment]
@juliamji I don't mind going through the process. It just felt like a commitment on both our parts to add me as an official contributor. But if that's your process, I'll whole-heartedly respect it.

**Comment by Amsonia** [comment]
I can help out even though I know only a little bit of C++

**Comment by digilou** [comment]
Hi @Amsonia I'll unassigned myself and you can go ahead.
