### ISSUE TITLE
Cleanup code duplication warnings identified by Codeclimate

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#971]
# Description 

Cleanup code duplication warnings identified by Codeclimate

https://codeclimate.com/github/ifmeorg/ifme/issues?category=duplication&engine_name%5B%5D=structure&engine_name%5B%5D=duplication

# Do you want to be the assignee to work on this?

🚫

**Comment by DRBragg** [comment]
I love me some refactoring and I'm happy to help. Just sent you an email request to join.

**Comment by DRBragg** [comment]
Removing myself from this for now, most of the CC issues are for React and the RoR issues is just the common_fields method being repetitive. I'd rather leave this open for another beginner who is more comfortable with JS than Ruby so they can get a PR. I can circle back around later.

**Comment by julianguyen** [comment]
@DRBragg That's very thoughtful of you to do that. There are other more advanced RoR and React issues if you're interested!

**Comment by DanielSauve** [comment]
Hey there! I would gladly pick this up, I sent an email request to join!
