### ISSUE TITLE
Run SVG files through SVGO so they're optimized

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#974]
# Description 

Run SVG files through SVGO so they're optimized

https://github.com/svg/svgo

# Do you want to be the assignee to work on this?

🚫

**Comment by kumaran-14** [comment]
Can I claim this? It would be my first ever open source pull request

**Comment by julianguyen** [comment]
Hey @kumaran-14, we would love for you to work on this! Here are next steps for joining: https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack

**Comment by kumaran-14** [comment]
@julianguyen Sure. How should I proceed on this ? Any tips / suggestions?

**Comment by julianguyen** [comment]
@kumaran-14 Yeah I would check out https://github.com/svg/svgo, set it up locally on your machine and run SVGO through our SVG files in app/assets/images. After that re-upload the new SVG images. If you need anymore help, let's sync on Slack
