### ISSUE TITLE
Use Modal component to view contributor blurbs

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#975]
# Description 

Replace current implementing of viewing blurbs on https://www.if-me.org/contribute with the Modal component (you can preview it in Storybook)

# Do you want to be the assignee to work on this?

🚫

**Comment by chsingal** [comment]
I would like to work on this!

**Comment by julianguyen** [comment]
Hey @chsingal, we would love for you to work on this! Here are next steps for joining: https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack
