### ISSUE TITLE
Add headers for security

### ISSUE THREAD

**Issue by sexybiggetje** [ifmeorg/ifme#976]
# Description 

The domain if-me.org is missing some headers which could improve it's security.

PASS(if-me.org): HTTP redirects to HTTPS using a 301
FAIL(if-me.org): Strict-Transport-Security missing
FAIL(if-me.org): X-Frame-Options missing
FAIL(if-me.org): X-Content-Type-Options missing
FAIL(if-me.org): X-XSS-Protection missing
FAIL(if-me.org): Referrer-Policy missing
FAIL(if-me.org): Content-Security-Policy missing
FAIL(if-me.org): Feature-Policy missing
PASS(if-me.org): Site sends 'Server', but probably only a vendor ID: Cowboy
PASS(if-me.org): Site doesn't send 'X-Powered-By'
FAIL(if-me.org): Site sends 'Via', probably disclosing version info: 1.1 vegur
PASS(if-me.org): Site doesn't send 'X-AspNet-Version'
PASS(if-me.org): Site doesn't send 'X-AspNetMvc-Version'
PASS(if-me.org): No SCM repository at: http://if-me.org/.git/HEAD
PASS(if-me.org): No SCM repository at: http://if-me.org/.hg/store/00manifest.i
PASS(if-me.org): No SCM repository at: http://if-me.org/.svn/entries

# Reproduction Steps

Grab a header analyzer like twa (https://github.com/woodruffw/twa). Analyse the headers and see that it outputs something similar to above.

# Do you want to be the assignee to work on this?

🚫

Not much at a pc these days.

**Comment by julianguyen** [comment]
Great call out! Thank you :)
