### ISSUE TITLE
Update screenshots in App Features section of the Wiki

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#980]
# Description 

Our new redesign has rolled out woo! Let's update our [App Features](https://github.com/ifmeorg/ifme/wiki/App-Features) document

# Do you want to be the assignee to work on this?

🚫

**Comment by ngohgia** [comment]
I would like to contribute to this project. I think working on this issue would help me familiarize with the project's features. Can I take a stab at this?

**Comment by julianguyen** [comment]
Hey @ngohgia, thanks for expressing your interest. We would love your help with this issue. Please check out https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack for next steps :)
