### ISSUE TITLE
Prevent scrolling of content behind the Modal component

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#990]
# Description 

Prevent scrolling of content behind the Modal component

# Reproduction Steps

1. Open a modal (Notifications, Categories/Mood/Strategies modal in Moments/Strategies editor
2. If the modal is not full screen (on tablet and desktop), you can scroll through the content behind the Modal component

# Do you want to be the assignee to work on this?

🚫

**Comment by LeanKhan** [comment]
Hi, can I work on this Issue?


 I might need guidelines though :)

**Comment by julianguyen** [comment]
Hi @LeanKhan! Thanks for expressing your interest, we would love for your help. Here are next steps for joining: https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack

Let's sync more after you join our Slack :)

**Comment by LeanKhan** [comment]
I won't be working on this anymore, thank you.

**Comment by DamonClark** [comment]
I'd like to work on this!

**Comment by julianguyen** [comment]
@DamonClark Awesome! Could you follow up with next steps here: https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack. Thanks!
