### ISSUE TITLE
Fix full screen modal bug in mobile web

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#991]
# Description 

In mobile Chrome, there's a bug with our modal where the address bar is blocking the top part of the modal. Let's fix this!

This [post](https://teamtreehouse.com/community/position-fixed-css-bug-in-chrome-and-firefox-for-android) may give you some insights on how to fix it.

# Reproduction Steps

1. Open mobile Chrome
2. Open any modal (Notifications for example)

# Screenshots

![image](https://user-images.githubusercontent.com/3010728/45913290-810b6180-bde4-11e8-9ce9-429ae6c74b5b.png)

# Do you want to be the assignee to work on this?

🚫

**Comment by mialahmoka** [comment]
I'd like to work on this

**Comment by julianguyen** [comment]
Hi @mialahmoka :) Thanks for expressing your interest, we would love for your help. Here are next steps for contributing: https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack

**Comment by julianguyen** [comment]
@vishalsodani Yep, once you contact us and we add you to our GitHub org, you can self-assign.

**Comment by lsurasani** [comment]
Hey! Unsure if @vishalsodani is working on it but I'd like to take a look if not!

**Comment by vishalsodani** [comment]
> Hey! Unsure if @vishalsodani is working on it but I'd like to take a look if not!
@lsurasani 
Please go ahead. I am not taking up this issue.

**Comment by julianguyen** [comment]
@lsurasani Oh no sorry to hear. Did you try [remote debugging](https://developers.google.com/web/tools/chrome-devtools/remote-debugging/) via Chrome by any chance?

**Comment by lsurasani** [comment]
I did! But it wasn't giving me any errors -- for whatever reason the stylesheets/css just weren't loading

**Comment by julianguyen** [comment]
@CSumm The screen resolution is 1080x2160 and it's on the latest version of Android.

**Comment by CSumm** [comment]
I'll see if I can recreate it on my own first with chrome and if not I'll definitely ask for the Browserstack info.
