### ISSUE TITLE
Add ability to copy to clipboard when selecting the secret share input field

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#995]
# Description 

Secret share is awesome feature our Rails Girls Summer of Code 2017 students @SophieRoseMcDonald and @jnamster worked on! It adds the ability to generate a private URL to your Moment post that you can share with anyone who is not signed into the app. You're also able to remove the generated URL when you want it to expire.

We want to add the ability when the user clicks into the input field to have the URL automatically copied to the user's clipboard. You'll want to create a special type in our Input component (React) to support copy to clipboard. You use our Tooltip component to display something like "Copied to clipboard" (please use i18n) once the user clicks the input field.

# Screenshots

![image](https://user-images.githubusercontent.com/3010728/45747192-e3344e80-bbb9-11e8-9fb6-97e9252502cc.png)

# Do you want to be the assignee to work on this?

🚫

**Comment by namila** [comment]
I will work on this and make a PR

**Comment by julianguyen** [comment]
Hey @namila, thanks for expressing your interest. We would love your help with this issue. Please check out https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack for next steps :)

**Comment by ScotianMan** [comment]
Anything happening with this? Ill knock this out this morning 👍

**Comment by ScotianMan** [comment]
not exactly as requested but it works and gets the job done for now and we can discuss.

**Comment by dandida95** [comment]
i would like to contribute
